// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    println!("Guess the number!");
    println!("Please input your guess.");
    let mut guess: String = read_line();
    println!("You guessed: {}", guess);
}
