# Auto-generated by a2p transpiler

def main():
    print("Guess the number!")
    print("Please input your guess.")
    guess = input()
    print("You guessed: " + guess)

if __name__ == "__main__":
    main()
