// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

int main(void) {
    printf("Guess the number!\n");
    printf("Please input your guess.\n");
    char guess[256];
    fgets(guess, 256, stdin);
    guess[strcspn(guess, "\n")] = '\0';
    printf("You guessed: %s\n", guess);
    return 0;
}
