// Auto-generated by a2ts transpiler

import * as readline from 'readline';

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

function main(): void {
    console.log("Guess the number!");
    console.log("Please input your guess.");
    rl.question("", (guess: string) => {
        console.log("You guessed: " + guess);
        rl.close();
    });
}

main();
