// Auto-generated by a2ts transpiler

function* makeIterator<T>(arr: T[]): Generator<T> {
    for (const item of arr) {
        yield item;
    }
}

function main(): void {
    const numbers = [1, 2, 3, 4, 5];
    const iter = makeIterator(numbers);
    console.log(iter.next().value);
    console.log(iter.next().value);
    console.log(iter.next().value);
}

main();
