# Auto-generated by a2p transpiler

def main():
    numbers = [1, 2, 3, 4, 5]
    it = iter(numbers)
    print(next(it))
    print(next(it))
    print(next(it))

if __name__ == "__main__":
    main()
