// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

typedef struct {
    int* data;
    int len;
    int pos;
} Iterator;

Iterator iter_create(int* data, int len) {
    Iterator it;
    it.data = data;
    it.len = len;
    it.pos = 0;
    return it;
}

int* iter_next(Iterator* it) {
    if (it->pos < it->len) {
        return &it->data[it->pos++];
    }
    return NULL;
}

int main(void) {
    int numbers[] = {1, 2, 3, 4, 5};
    Iterator iter = iter_create(numbers, 5);
    int* v;
    v = iter_next(&iter);
    if (v) printf("%d\n", *v);
    v = iter_next(&iter);
    if (v) printf("%d\n", *v);
    v = iter_next(&iter);
    if (v) printf("%d\n", *v);
    return 0;
}
