// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn first_word_slice(s: String) -> String {
    let bytes = s.bytes();
    let mut i: i32 = 0;
    for b in bytes {
        if b == 32 {
            return s[0..i];
        }
        i = i + 1;
    }
    return s[0..s.len()];
}

fn main() {
    let s: String = String::from("hello world");
    let word = first_word_slice(&s);
    println!("first word: {}", word);
}
