// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

fn first_word_slice(mut s: String) -> String {
    let bytes = s.bytes();
    let mut i: i64 = 0;
    for b in &bytes {
        if b == 32 {
            return s[0..(i) as usize];
        }
        i = i + 1;
    }
    return s[0..(a2r_std::value_len(&s)) as usize];
}

fn main() {
    let s: String = String::from("hello world");
    let word = first_word_slice(&s);
    println!("first word: {}", word);
}
