# Auto-generated by a2p transpiler

from typing import TypeVar, List

T = TypeVar('T')

def largest(list: List[T]) -> T:
    largest = list[0]
    for item in list:
        if item > largest:
            largest = item
    return largest

def main():
    numbers = [34, 50, 25, 100, 65]
    print(largest(numbers))
    chars = ['y', 'm', 'a', 'q']
    print(largest(chars))

if __name__ == "__main__":
    main()
