// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn largest<T: PartialOrd + Clone>(list: Vec<T>) -> T {
    let mut largest: T = list[0].clone();
    for item in list {
        if item > largest {
            largest = item;
        }
    }
    largest
}

fn main() {
    let numbers = vec![34, 50, 25, 100, 65];
    println!("{}", largest(numbers));
    let chars = vec!['y', 'm', 'a', 'q'];
    println!("{}", largest(chars));
}
