// Auto-generated by a2c transpiler

#include <stdio.h>

int largest_int(int list[], int len) {
    int largest = list[0];
    for (int i = 1; i < len; i++) {
        if (list[i] > largest) {
            largest = list[i];
        }
    }
    return largest;
}

char largest_char(char list[], int len) {
    char largest = list[0];
    for (int i = 1; i < len; i++) {
        if (list[i] > largest) {
            largest = list[i];
        }
    }
    return largest;
}

int main(void) {
    int numbers[] = {34, 50, 25, 100, 65};
    printf("%d\n", largest_int(numbers, 5));
    char chars[] = {'y', 'm', 'a', 'q'};
    printf("%c\n", largest_char(chars, 4));
    return 0;
}
