// Auto-generated by a2ts transpiler

function largest<T>(list: T[]): T {
    let largest: T = list[0];
    for (const item of list) {
        if (item > largest) {
            largest = item;
        }
    }
    return largest;
}

function main(): void {
    const numbers = [34, 50, 25, 100, 65];
    console.log(largest(numbers));
    const chars = ['y', 'm', 'a', 'q'];
    console.log(largest(chars));
}

main();
