// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

int main(void) {
    int numbers[] = {1, 2, 3, 4, 5};
    int len = 5;
    int sum = 0;
    for (int i = 0; i < len; i++) {
        sum = sum + numbers[i];
    }
    printf("%d\n", sum);
    int product = 1;
    for (int i = 0; i < len; i++) {
        product = product * numbers[i];
    }
    printf("%d\n", product);
    return 0;
}
