// Auto-generated by a2ts transpiler

function main(): void {
    const numbers = [1, 2, 3, 4, 5];
    const sum = numbers.reduce((acc: number, x: number) => acc + x, 0);
    console.log(sum);
    const product = numbers.reduce((acc: number, x: number) => acc * x, 1);
    console.log(product);
}

main();
