// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut numbers = vec![1, 2, 3, 4, 5];
    let sum: i32 = numbers.iter().fold(0, |acc: i32, x: &i32| acc + x);
    println!("{}", sum);
    let product: i32 = numbers.iter().fold(1, |acc: i32, x: &i32| acc * x);
    println!("{}", product);
}
