# Auto-generated by a2p transpiler

from functools import reduce

def main():
    numbers = [1, 2, 3, 4, 5]
    sum_val = reduce(lambda acc, x: acc + x, numbers, 0)
    print(sum_val)
    product = reduce(lambda acc, x: acc * x, numbers, 1)
    print(product)

if __name__ == "__main__":
    main()
