// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef enum ShapeKind {
    ShapeKind_Circle,
    ShapeKind_Rect,
    ShapeKind_Triangle,
} ShapeKind;

typedef struct {
    ShapeKind kind;
    union {
        struct { double r; } circle;
        struct { double w; double h; } rect;
        struct { double a; double b; double c; } triangle;
    };
} Shape;

double area(Shape shape) {
    switch (shape.kind) {
        case ShapeKind_Circle:
            return 3.14159 * shape.circle.r * shape.circle.r;
        case ShapeKind_Rect:
            return shape.rect.w * shape.rect.h;
        case ShapeKind_Triangle:
            return 0.0;
    }
    return 0.0;
}

int main(void) {
    Shape c = { .kind = ShapeKind_Circle, .circle = { .r = 5.0 } };
    printf("%f\n", area(c));
    return 0;
}
