// Auto-generated by a2ts transpiler

enum ShapeKind {
    Circle = "Circle",
    Rect = "Rect",
    Triangle = "Triangle",
}

class Shape {
    kind: ShapeKind;
    values: number[];

    constructor(kind: ShapeKind, values: number[]) {
        this.kind = kind;
        this.values = values;
    }
}

function area(shape: Shape): number {
    switch (shape.kind) {
        case ShapeKind.Circle: {
            const r = shape.values[0];
            return 3.14159 * r * r;
        }
        case ShapeKind.Rect: {
            const w = shape.values[0];
            const h = shape.values[1];
            return w * h;
        }
        case ShapeKind.Triangle: {
            return 0.0;
        }
    }
}

function main(): void {
    const c = new Shape(ShapeKind.Circle, [5.0]);
    console.log(area(c));
}

main();
