# Auto-generated by a2p transpiler

from enum import Enum
from dataclasses import dataclass

class ShapeKind(Enum):
    Circle = 1
    Rect = 2
    Triangle = 3

@dataclass
class Shape:
    kind: ShapeKind
    values: tuple

def area(shape):
    match shape.kind:
        case ShapeKind.Circle:
            r = shape.values[0]
            return 3.14159 * r * r
        case ShapeKind.Rect:
            w, h = shape.values[0], shape.values[1]
            return w * h
        case ShapeKind.Triangle:
            return 0.0

def main():
    c = Shape(kind=ShapeKind.Circle, values=(5.0,))
    print(area(c))

if __name__ == "__main__":
    main()
