// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::sync::mpsc;
use std::thread;

enum LoggerMsg {
    Log(String),
}

fn main() {
    let (tx, rx) = mpsc::channel();

    thread::spawn(move || {
        let prefix = "app";
        for msg in rx {
            match msg {
                LoggerMsg::Log(text) => {
                    println!("[{}] {}", prefix, text);
                }
            }
        }
    });

    tx.send(LoggerMsg::Log("Server started".to_string())).unwrap();
    tx.send(LoggerMsg::Log("Processing request".to_string())).unwrap();
    tx.send(LoggerMsg::Log("Server stopped".to_string())).unwrap();
}
