// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Coin {
    Penny(i32),
    Nickel(i32),
    Dime(i32),
    Quarter(i32),
}


fn value_in_cents(coin: Coin) -> i32 {
    match coin {
        Coin::Penny(v) => v,
        Coin::Nickel(v) => v,
        Coin::Dime(v) => v,
        Coin::Quarter(v) => v,
    }
}

fn main() {
    let c = Coin::Penny(1);
    println!("Value: {}", value_in_cents(c));
}
