// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Animal {
    name: String,
    age: i32,
}

struct Dog {
    animal: Animal,    // Manual composition
    breed: String,
}

fn main() {
    let dog = Dog {
        animal: Animal { name: String::from("Rex"), age: 3 },
        breed: String::from("German Shepherd"),
    };
    println!("{} is {} years old", dog.animal.name, dog.animal.age);
    println!("Breed: {}", dog.breed);
}
