# Auto-generated by a2p transpiler

from enum import Enum

class Direction(Enum):
    NORTH = 0
    SOUTH = 1
    EAST = 2
    WEST = 3

def main():
    d = Direction.NORTH
    print(d.name)

if __name__ == "__main__":
    main()
