// Auto-generated by a2c transpiler

#include <stdio.h>

typedef enum {
    Direction_North = 0,
    Direction_South = 1,
    Direction_East = 2,
    Direction_West = 3,
} Direction;

const char* direction_name(Direction d) {
    switch (d) {
        case Direction_North: return "North";
        case Direction_South: return "South";
        case Direction_East: return "East";
        case Direction_West: return "West";
        default: return "Unknown";
    }
}

int main(void) {
    Direction d = Direction_North;
    printf("%s\n", direction_name(d));
    return 0;
}
