// Auto-generated by a2ts transpiler

enum Direction {
    North = 0,
    South = 1,
    East = 2,
    West = 3,
}

function main(): void {
    let d: Direction = Direction.North;
    console.log(Direction[d]);
}

main();
