// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct CustomSmartPointer {
    data: String,
}

impl CustomSmartPointer {
    fn new(data: String) -> CustomSmartPointer {
        CustomSmartPointer { data }
    }
}

impl Drop for CustomSmartPointer {
    fn drop(&mut self) {
        println!("Dropping CustomSmartPointer with data `{}`!", self.data);
    }
}

fn main() {
    let c = CustomSmartPointer::new(String::from("my stuff"));
    let d = CustomSmartPointer::new(String::from("other stuff"));
    println!("CustomSmartPointers created");
}
