// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

#if defined(__linux__)
const char* platform_path() {
    return "/var/data";
}
#elif defined(_WIN32)
const char* platform_path() {
    return "C:\\Users\\data";
}
#endif

int main(void) {
    const char* path = platform_path();
    printf("Data path: %s\n", path);
    return 0;
}
