// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[cfg(target = "linux")]
fn platform_path() -> &'static str {
    "/var/data"
}

#[cfg(target = "windows")]
fn platform_path() -> &'static str {
    "C:\\Users\\data"
}

fn main() {
    let mut path = platform_path();
    println!("Data path: {}", path);
}
