# Auto-generated by a2p transpiler

import sys

def platform_path():
    if sys.platform == "linux":
        return "/var/data"
    elif sys.platform == "win32":
        return "C:\\Users\\data"

def main():
    path = platform_path()
    print("Data path: " + path)

if __name__ == "__main__":
    main()
