// Auto-generated by a2ts transpiler

import * as os from "os";

function platformPath(): string {
    if (os.platform() === "linux") {
        return "/var/data";
    } else if (os.platform() === "win32") {
        return "C:\\Users\\data";
    }
    return "";
}

function main(): void {
    const path: string = platformPath();
    console.log("Data path: " + path);
}

main();
