// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Config {
    query: String,
    file_path: String,
}

impl Config {
    fn build(args: Vec<String>) -> Result<Config, String> {
        if args.len() < 3 {
            Err(String::from("not enough arguments"));
        } else {
            Ok(Config { query: args[1].clone(), file_path: args[2].clone() })
        }
    }
}

fn search(query: &str, contents: &str) -> Vec<&str> {
    let mut results = Vec::new();
    for line in contents.lines() {
        if line.contains(query) {
            results.push(line);
        }
    }
    results
}

fn run(config: Config) -> Result<(), String> {
    let contents = fs::read_to_string(&config.file_path).collect();
    for line in search(&config.query, &contents) {
        println!("{}", line);
    }
    Ok(())
}

use std::env;
use std::fs;

fn main() -> Result<(), String> {
    let config = Config::build(env::args().collect())?;
    run(config)
}
