// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    println!("Guess the number!");
    println!("Please input your guess.");

    let mut guess: String = "42".to_string();
    println!("You guessed: {}", guess);
}
