// Auto-generated by a2r transpiler

fn main() {
    println!("Guess the number!");
    println!("Please input your guess.");

    let mut guess: String = "42".to_string();
    println!("You guessed: {}", guess);
}
