// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Engine {
    horsepower: i64,
}

impl Engine {
    fn start(&self) {
        println!("Engine ({}hp) started", self.horsepower);
    }
}

struct Car {
    engine: Engine,
    brand: String,
}

impl Car {
    fn start(&self) {
        self.engine.start();
    }
}

fn main() {
    let mut c = Car {
        engine: Engine { horsepower: 400 },
        brand: String::from("Tesla"),
    };
    println!("{}", c.brand);
    c.start();
}
