// Auto-generated by a2ts transpiler

class Engine {
    horsepower: number;

    constructor(horsepower: number) {
        this.horsepower = horsepower;
    }

    start(): void {
        console.log(`Engine (${this.horsepower}hp) started`);
    }
}

class Car {
    engine: Engine;
    brand: string;

    constructor(brand: string, engine: Engine) {
        this.brand = brand;
        this.engine = engine;
    }

    start(): void {
        this.engine.start();
    }
}

function main(): void {
    const c = new Car("Tesla", new Engine(400));
    console.log(c.brand);
    c.start();
}

main();
