# Auto-generated by a2p transpiler

from dataclasses import dataclass

@dataclass
class Engine:
    horsepower: int

    def start(self):
        print(f"Engine ({self.horsepower}hp) started")

@dataclass
class Car:
    engine: Engine
    brand: str

    def start(self):
        self.engine.start()

def main():
    c = Car(engine=Engine(horsepower=400), brand="Tesla")
    print(c.brand)
    c.start()

if __name__ == "__main__":
    main()
