// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct {
    long long horsepower;
} Engine;

void Engine_start(const Engine* self) {
    printf("Engine (%lldhp) started\n", self->horsepower);
}

typedef struct {
    Engine engine;
    char brand[256];
} Car;

void Car_start(const Car* self) {
    Engine_start(&self->engine);
}

int main(void) {
    Car c;
    c.engine.horsepower = 400;
    strcpy(c.brand, "Tesla");
    printf("%s\n", c.brand);
    Car_start(&c);
    return 0;
}
