# Auto-generated by a2p transpiler

def main():
    secret = 42
    print("Guess the number!")
    while True:
        guess_str = input()
        guess = int(guess_str)
        print("You guessed: " + str(guess))
        if guess == secret:
            print("You win!")
            break
        if guess < secret:
            print("Too small!")
        else:
            print("Too big!")

if __name__ == "__main__":
    main()
