// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    long long x = 5;
    const char* name = "Alice";
    double pi = 3.14159;
    printf("%lld\n", x);
    printf("%s\n", name);
    printf("%f\n", pi);
    return 0;
}
