// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut x: i64 = 5;
    let mut name: String = String::from("Alice");
    let mut pi: f64 = 3.14159;
    println!("{}", x);
    println!("{}", name);
    println!("{}", pi);
}
