// Auto-generated by a2ts transpiler

function main(): void {
    let x: number = 5;
    let name: string = "Alice";
    let pi: number = 3.14159;
    console.log(x);
    console.log(name);
    console.log(pi);
}

main();
