// Auto-generated by a2c transpiler

#include <stdio.h>

/* C does not have trait/bound support.
   Multiple interface constraints require
   manual function dispatch per concrete type. */

int main(void) {
    /* example usage */
    return 0;
}
