// Auto-generated by a2ts transpiler

interface Display {
    display(): string;
}

interface Clone<T> {
    clone(): T;
}

function showAndCopy<T extends Display & Clone<T>>(item: T): void {
    console.log(item.display());
    item.clone();
}

function main(): void {
    // example usage
}

main();
