# Auto-generated by a2p transpiler

from typing import Protocol, TypeVar

T = TypeVar('T')

class Display(Protocol):
    def display(self) -> str: ...

class Clone(Protocol):
    def clone(self) -> 'Self': ...

def show_and_copy(item: T) -> None:
    print(item.display())  # type: ignore
    item.clone()           # type: ignore

def main():
    # example usage
    pass

if __name__ == "__main__":
    main()
