// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Display {
    fn display(&self) -> String;
}

trait Clone {
    fn clone(&self) -> Self;
}

fn show_and_copy<T: Display + Clone>(item: T) {
    println!("{}", item.display());
    item.clone();
}

fn main() {
    // example usage
}
