// Auto-generated by a2c transpiler
// Note: Auto shadowing with different types requires union types in C.
// The transpiler uses a tagged union to preserve semantics.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef enum { VAL_INT, VAL_STRING } ValTag;

typedef struct {
    ValTag tag;
    union {
        long long int_val;
        const char* str_val;
    };
} Val;

Val val_from_int(long long v) {
    Val v_;
    v_.tag = VAL_INT;
    v_.int_val = v;
    return v_;
}

Val val_from_string(const char* v) {
    Val v_;
    v_.tag = VAL_STRING;
    v_.str_val = v;
    return v_;
}

void val_print(Val v) {
    switch (v.tag) {
        case VAL_INT: printf("%lld\n", v.int_val); break;
        case VAL_STRING: printf("%s\n", v.str_val); break;
    }
}

int main(void) {
    Val x = val_from_int(5);
    val_print(x);
    x = val_from_int(x.int_val + 1);
    val_print(x);
    x = val_from_string("now a string");
    val_print(x);
    return 0;
}
