// Auto-generated by a2ts transpiler

function main(): void {
    let x: number | string = 5;
    console.log(x);
    x = (x as number) + 1;
    console.log(x);
    x = "now a string";
    console.log(x);
}

main();
