// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut x: i64 = 5;
    println!("{}", x);
    let x: i64 = x + 1;
    println!("{}", x);
    let x: String = String::from("now a string");
    println!("{}", x);
}
