// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn maybe_double(x: Option<i32>) -> Option<i32> {
    match x {
        None => None,
        Some(v) => Some(v * 2),
    }
}

fn main() {
    let result1 = maybe_double(Some(21));
    let result2 = maybe_double(None);
    println!("Done");
}
