// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Guess {
    value: i32,
}

impl Guess {
    fn new(value: i32) -> Guess {
        if value < 1 {
            panic!("Guess value must be greater than or equal to 1");
        } else if value > 100 {
            panic!("Guess value must be less than or equal to 100");
        }
        Guess { value }
    }
}

#[test]
#[should_panic(expected = "less than or equal to 100")]
fn greater_than_100() {
    Guess::new(200);
}

#[test]
fn valid_guess() -> Result<(), String> {
    let g = Guess::new(50);
    assert_eq!(g.value, 50);
    Ok(())
}
