// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Rectangle {
    pub width: i64,
    pub height: i64,
}

impl Rectangle {
    fn area(&self) -> i64 {
        self.width * self.height
    }
    fn square(&self, size: i64) -> Rectangle {
        Rectangle { width: size, height: size }
    }
}

fn main() {
    let sq = Rectangle::square(3);
    println!("Square area: {}", sq.area());
}
