// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Rectangle {
    width: i32,
    height: i32,
}

impl Rectangle {
    fn area(&self) -> i32 {
        self.width * self.height
    }
    fn square(&self, size: i32) -> Rectangle {
        Rectangle { width: size, height: size };
    }
}

fn main() {
    let sq = Rectangle::square(3);
    println!("Square area: {}", sq.area());
}
