// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let x: i32 = 10;
    let y: i32 = x.unwrap_or(0);
    println!("y = {}", y);
}
