// Build script for book-listing-tests
// Walks listings/ directories, finds directories with main.at,
// checks for .expected.* files to determine test types,
// and generates #[test] functions in OUT_DIR/generated_tests.rs

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("generated_tests.rs");

    let book_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let book_path = Path::new(&book_dir);

    let mut tests: Vec<(String, String, String)> = Vec::new(); // (fn_name, listing_dir_abs, test_type)

    // Scan for listings/ directories in each book subdirectory
    if let Ok(entries) = fs::read_dir(book_path) {
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            let listings_dir = path.join("listings");
            if !listings_dir.is_dir() {
                continue;
            }
            // Get the book name (e.g., "rust", "little-c", "byte-of-python")
            let book_name = path
                .file_name()
                .unwrap_or_default()
                .to_str()
                .unwrap_or("unknown");
            scan_listings(&listings_dir, book_name, &mut tests);
        }
    }

    // Also scan a top-level listings/ directory if it exists
    let top_listings = book_path.join("listings");
    if top_listings.is_dir() {
        scan_listings(&top_listings, "top", &mut tests);
    }

    // Sort for deterministic output
    tests.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate test functions
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — DO NOT EDIT\n");
    code.push_str("// Regenerate with: cargo clean -p book-listing-tests && cargo test --no-run\n\n");

    for (fn_name, listing_dir, test_type) in &tests {
        // Normalize path separators to forward slashes for Windows
        let listing_dir_normalized = listing_dir.replace('\\', "/");
        code.push_str(&format!(
            "#[test]\nfn {fn_name}() {{\n    let p = std::path::Path::new(\"{listing_dir_normalized}\");\n    harness::run_{test_type}(p).unwrap_or_else(|e| panic!(\"{{}}\", e));\n}}\n\n",
        ));
    }

    fs::write(&dest, &code).expect("Failed to write generated_tests.rs");
    println!("cargo:rerun-if-changed=listings");
}

fn scan_listings(listings_dir: &Path, book_name: &str, tests: &mut Vec<(String, String, String)>) {
    // listings_dir structure: <book>/listings/<chapter>/<listing>/main.at
    // Recursively walk directories looking for main.at

    if let Ok(entries) = fs::read_dir(listings_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            walk_and_register(&path, book_name, tests);
        }
    }
}

fn walk_and_register(dir: &Path, book_name: &str, tests: &mut Vec<(String, String, String)>) {
    // Check if this directory has main.at — if so, it's a listing directory
    if dir.join("main.at").exists() {
        register_tests(dir, book_name, tests);
        return;
    }

    // Otherwise, recurse into subdirectories
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk_and_register(&path, book_name, tests);
            }
        }
    }
}

fn register_tests(listing_dir: &Path, book_name: &str, tests: &mut Vec<(String, String, String)>) {
    let listing_name = listing_dir
        .file_name()
        .unwrap_or_default()
        .to_str()
        .unwrap_or("unknown");

    // Get the parent (chapter) for unique naming
    let chapter = listing_dir
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("unknown");

    // Normalize the full path for use in tests
    let listing_dir_str = listing_dir.to_str().unwrap_or("").to_string();

    // Check for each expected file type and register appropriate tests
    if listing_dir.join("main.expected.rs").exists() {
        let fn_name = sanitize_fn_name(&format!("{book_name}_{chapter}_{listing_name}"));
        tests.push((fn_name, listing_dir_str.clone(), "a2r".to_string()));
    }

    if listing_dir.join("main.expected.c").exists() {
        let fn_name = sanitize_fn_name(&format!("{book_name}_{chapter}_{listing_name}_c"));
        tests.push((fn_name, listing_dir_str.clone(), "a2c".to_string()));
    }

    if listing_dir.join("main.expected.py").exists() {
        let fn_name = sanitize_fn_name(&format!("{book_name}_{chapter}_{listing_name}_py"));
        tests.push((fn_name, listing_dir_str.clone(), "a2p".to_string()));
    }

    if listing_dir.join("main.expected.ts").exists() {
        let fn_name = sanitize_fn_name(&format!("{book_name}_{chapter}_{listing_name}_ts"));
        tests.push((fn_name, listing_dir_str.clone(), "a2ts".to_string()));
    }

    // VM tests: check for .expected.out, .expected.result, or .expected.error
    if listing_dir.join("main.expected.out").exists()
        || listing_dir.join("main.expected.result").exists()
        || listing_dir.join("main.expected.error").exists()
    {
        let fn_name = sanitize_fn_name(&format!("{book_name}_{chapter}_{listing_name}_vm"));
        tests.push((fn_name, listing_dir_str, "vm".to_string()));
    }
}

/// Convert a test identifier to a valid Rust function name.
/// Replace non-alphanumeric chars with underscores.
fn sanitize_fn_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}
