// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn largest<T>(list: Vec<T>) -> T {
    let mut largest: T = list[0].clone();
    for item in list {
        if item > largest {
            largest = item;
        }
    }
    largest
}

fn main() {
    let numbers = vec![34, 50, 25, 100, 65];
    let result = largest(numbers);
    println!("The largest number is {}", result);
}
