// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::future::Future;
use std::time::Duration;
use trpl::Either;

async fn timeout<F: Future>(future_to_try: F, max_time: Duration)
    -> Result<F::Output, Duration>
where
    F: Future,
{
    match trpl::select(future_to_try, trpl::sleep(max_time)).await {
        Either::Left(output) => Ok(output),
        Either::Right(_) => Err(max_time),
    }
}

fn main() {
    trpl::block_on(async {
        let slow_task = async {
            trpl::sleep(Duration::from_secs(5)).await;
            "finally done"
        };

        match timeout(slow_task, Duration::from_secs(1)).await {
            Ok(value) => println!("Got: {}", value),
            Err(_duration) => println!("Failed: timed out"),  // This prints
        }
    })
}
