// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn identity<T: Clone>(x: T) -> T {
    x
}

fn main() {
    println!("{}", identity(42));      // monomorphized to identity::<i64>
    println!("{}", identity(String::from("hello"))); // monomorphized to identity::<String>
}
