# Auto-generated by a2p transpiler

from typing import TypeVar

T = TypeVar('T')

def identity(x: T) -> T:
    return x

def main():
    print(identity(42))      # no monomorphization in Python
    print(identity("hello"))

if __name__ == "__main__":
    main()
