// Auto-generated by a2ts transpiler

function identity<T>(x: T): T {
    return x;
}

function main(): void {
    console.log(identity(42));      // type inferred as number
    console.log(identity("hello")); // type inferred as string
}

main();
