// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

/* Monomorphized: identity for int */
long long identity_int(long long x) {
    return x;
}

/* Monomorphized: identity for string */
const char* identity_str(const char* x) {
    return x;
}

int main(void) {
    printf("%lld\n", identity_int(42));
    printf("%s\n", identity_str("hello"));
    return 0;
}
