// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    long long power;
} Engine;

void Engine_ignite(const Engine* self) {
    printf("Engine ignited: %lldhp\n", self->power);
}

typedef struct {
    Engine engine;
    char model[256];
} Car;

void Car_start(const Car* self) {
    Engine_ignite(&self->engine);
    printf("%s started\n", self->model);
}

void Car_stop(const Car* self) {
    printf("%s stopped\n", self->model);
}

typedef struct {
    Car base;
    double payload;
} Truck;

void Truck_start(const Truck* self) {
    Car_start(&self->base);
}

void Truck_stop(const Truck* self) {
    Car_stop(&self->base);
}

int main(void) {
    Truck t;
    strcpy(t.base.model, "BigRig");
    t.base.engine.power = 500;
    t.payload = 10.0;
    Truck_start(&t);
    Truck_stop(&t);
    printf("Payload: %f tons\n", t.payload);
    return 0;
}
