// Auto-generated by a2ts transpiler

interface Vehicle {
    start(): void;
    stop(): void;
}

class Engine {
    power: number;

    constructor(power: number) {
        this.power = power;
    }

    ignite(): void {
        console.log(`Engine ignited: ${this.power}hp`);
    }
}

class Car implements Vehicle {
    engine: Engine;
    model: string;

    constructor(model: string, engine: Engine) {
        this.model = model;
        this.engine = engine;
    }

    ignite(): void {
        this.engine.ignite();
    }

    start(): void {
        this.ignite();
        console.log(`${this.model} started`);
    }

    stop(): void {
        console.log(`${this.model} stopped`);
    }
}

class Truck extends Car implements Vehicle {
    payload: number;

    constructor(model: string, engine: Engine, payload: number) {
        super(model, engine);
        this.payload = payload;
    }
}

function main(): void {
    const t = new Truck("BigRig", new Engine(500), 10.0);
    t.start();
    t.stop();
    console.log(`Payload: ${t.payload} tons`);
}

main();
