// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Vehicle {
    fn start(&self);
    fn stop(&self);
}

struct Engine {
    power: i64,
}

impl Engine {
    fn ignite(&self) {
        println!("Engine ignited: {}hp", self.power);
    }
}

struct Car {
    engine: Engine,
    model: String,
}

impl Vehicle for Car {
    fn start(&self) {
        self.ignite();
        println!("{} started", self.model);
    }
    fn stop(&self) {
        println!("{} stopped", self.model);
    }
}

impl Car {
    fn ignite(&self) {
        self.engine.ignite();
    }
}

struct Truck {
    model: String,
    engine: Engine,
    payload: f64,
}

impl Truck {
    fn start(&self) {
        self.ignite();
        println!("{} started", self.model);
    }
    fn stop(&self) {
        println!("{} stopped", self.model);
    }
    fn ignite(&self) {
        self.engine.ignite();
    }
}

fn main() {
    let mut t = Truck {
        model: String::from("BigRig"),
        engine: Engine { power: 500 },
        payload: 10.0,
    };
    t.start();
    t.stop();
    println!("Payload: {} tons", t.payload);
}
