# Auto-generated by a2p transpiler

from abc import ABC, abstractmethod
from dataclasses import dataclass

class Vehicle(ABC):
    @abstractmethod
    def start(self):
        pass

    @abstractmethod
    def stop(self):
        pass

@dataclass
class Engine:
    power: int

    def ignite(self):
        print(f"Engine ({self.power}hp) ignited")

@dataclass
class Car(Vehicle):
    engine: Engine
    model: str

    def ignite(self):
        self.engine.ignite()

    def start(self):
        self.ignite()
        print(f"{self.model} started")

    def stop(self):
        print(f"{self.model} stopped")

@dataclass
class Truck(Car):
    payload: float

def main():
    t = Truck(engine=Engine(power=500), model="BigRig", payload=10.0)
    t.start()
    t.stop()
    print(f"Payload: {t.payload} tons")

if __name__ == "__main__":
    main()
