// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Rectangle {
    pub width: i64,
    pub height: i64,
}

impl Rectangle {
    fn area(&self) -> i64 {
        self.width * self.height
    }
    fn double_width(&self) -> i64 {
        self.width * 2
    }
}

fn main() {
    let rect1 = Rectangle { width: 30, height: 50 };
    println!("Area: {}", rect1.area());
    println!("Double width: {}", rect1.double_width());
}
