// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use trpl::{block_on, get, Html};

async fn page_title(url: &str) -> Option<String> {
    let response_text = trpl::get(url).await.text().await;
    Html::parse(&response_text)
        .select_first("title")
        .map(|title| title.inner_html())
}

fn main() {
    block_on(async {
        let title = page_title("https://example.com").await;
        match title {
            Some(t) => println!("Title: {t}"),
            None => println!("No title found"),
        }
    })
}
