// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Rectangle {
    width: f64,
    height: f64,
}

fn area(r: Rectangle) -> f64 {
    r.width * r.height
}

fn main() {
    let mut rect = Rectangle { width: 10.0, height: 5.0 };
    println!("{}", area(rect));
}
