// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct {
    double width;
    double height;
} Rectangle;

double area(Rectangle r) {
    return r.width * r.height;
}

int main(void) {
    Rectangle rect = {10.0, 5.0};
    printf("%f\n", area(rect));
    return 0;
}
