# Auto-generated by a2p transpiler

from dataclasses import dataclass

@dataclass
class Rectangle:
    width: float
    height: float

def area(r):
    return r.width * r.height

def main():
    rect = Rectangle(width=10.0, height=5.0)
    print(area(rect))

if __name__ == "__main__":
    main()
