// Auto-generated by a2ts transpiler

class Rectangle {
    width: number;
    height: number;

    constructor(width: number, height: number) {
        this.width = width;
        this.height = height;
    }
}

function area(r: Rectangle): number {
    return r.width * r.height;
}

function main(): void {
    const rect: Rectangle = new Rectangle(10.0, 5.0);
    console.log(area(rect));
}

main();
