# Auto-generated by a2p transpiler

def main():
    x = 5
    x = 6
    y = 10
    # y = 11  # ERROR — let is immutable (no runtime enforcement in Python)
    print(x)
    print(y)

if __name__ == "__main__":
    main()
