// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut x: i64 = 5;
    x = 6;
    let y: i64 = 10;
    println!("{}", x);
    println!("{}", y);
}
