// Auto-generated by a2ts transpiler

function main(): void {
    let x: number = 5;
    x = 6;
    const y: number = 10;
    // y = 11;  // ERROR — let is immutable
    console.log(x);
    console.log(y);
}

main();
