// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    long long x = 5;
    x = 6;
    const long long y = 10;
    /* y = 11;  // ERROR — let is immutable */
    printf("%lld\n", x);
    printf("%lld\n", y);
    return 0;
}
