// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

fn calculate_length(s: String) -> i64 {
    a2r_std::value_len(&s)
}

fn main() {
    let s1: String = String::from("hello");
    let len = calculate_length(&s1);
    println!("The length of '{}' is {}.", s1, len);
}
