// Auto-generated by a2ts transpiler

class Quit {}

class Move {
    x: number;
    y: number;
    constructor(x: number, y: number) {
        this.x = x;
        this.y = y;
    }
}

class Speak {
    msg: string;
    constructor(msg: string) {
        this.msg = msg;
    }
}

type Command = Quit | Move | Speak;

function handle(cmd: Command): void {
    if (cmd instanceof Quit) {
        console.log("Goodbye!");
    } else if (cmd instanceof Move) {
        console.log(`Moving to ${cmd.x}, ${cmd.y}`);
    } else if (cmd instanceof Speak) {
        console.log(cmd.msg);
    }
}

function main(): void {
    handle(new Quit());
    handle(new Move(10, 20));
    handle(new Speak("Hello!"));
}

main();
