// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Command {
    Quit,
    Move(i64, i64),
    Speak(String),
}

fn handle(cmd: Command) {
    match cmd {
        Command::Quit => println!("Goodbye!"),
        Command::Move(x, y) => println!("Moving to {}, {}", x, y),
        Command::Speak(msg) => println!("{}", msg),
    }
}

fn main() {
    handle(Command::Quit);
    handle(Command::Move(10, 20));
    handle(Command::Speak(String::from("Hello!")));
}
