// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct {
    int nothing;
} CommandQuit;

typedef struct {
    long long x;
    long long y;
} CommandMove;

typedef struct {
    char msg[256];
} CommandSpeak;

typedef enum {
    CommandTag_Quit = 0,
    CommandTag_Move = 1,
    CommandTag_Speak = 2,
} CommandTag;

typedef struct {
    CommandTag tag;
    union {
        CommandQuit quit;
        CommandMove move;
        CommandSpeak speak;
    };
} Command;

void handle(Command cmd) {
    switch (cmd.tag) {
        case CommandTag_Quit:
            printf("Goodbye!\n");
            break;
        case CommandTag_Move:
            printf("Moving to %lld, %lld\n", cmd.move.x, cmd.move.y);
            break;
        case CommandTag_Speak:
            printf("%s\n", cmd.speak.msg);
            break;
    }
}

int main(void) {
    Command cmd1 = { .tag = CommandTag_Quit, .quit = { .nothing = 0 } };
    handle(cmd1);
    Command cmd2 = { .tag = CommandTag_Move, .move = { .x = 10, .y = 20 } };
    handle(cmd2);
    Command cmd3 = { .tag = CommandTag_Speak };
    strcpy(cmd3.speak.msg, "Hello!");
    handle(cmd3);
    return 0;
}
