# Auto-generated by a2p transpiler

from dataclasses import dataclass
from typing import Union

class Quit:
    pass

@dataclass
class Move:
    x: int
    y: int

@dataclass
class Speak:
    msg: str

Command = Union[Quit, Move, Speak]

def handle(cmd):
    if isinstance(cmd, Quit):
        print("Goodbye!")
    elif isinstance(cmd, Move):
        print(f"Moving to {cmd.x}, {cmd.y}")
    elif isinstance(cmd, Speak):
        print(cmd.msg)

def main():
    handle(Quit())
    handle(Move(x=10, y=20))
    handle(Speak(msg="Hello!"))

if __name__ == "__main__":
    main()
