// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    const char* fruits[] = {"apple", "banana", "cherry"};
    int fruits_len = 3;
    for (int i = 0; i < fruits_len; i++) {
        printf("%s\n", fruits[i]);
    }
    return 0;
}
