// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut fruits: Vec<String> = vec![
        String::from("apple"),
        String::from("banana"),
        String::from("cherry"),
    ];
    for fruit in &fruits {
        println!("{}", fruit);
    }
}
