// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Point<T> {
    x: T,
    y: T,
}

impl<T> Point<T> {
    fn x_value(&self) -> T {
        self.x.clone()
    }
}

fn main() {
    let p = Point { x: 5, y: 10 };
    let x = p.x_value();
    println!("x = {}", x);
}
