// Auto-generated by a2ts transpiler

class Request {
    url: string;

    constructor(url: string) {
        this.url = url;
    }
}

class Response {
    data: string;
    status: number;

    constructor(data: string, status: number) {
        this.data = data;
        this.status = status;
    }
}

function httpServer(req: Request): Response {
    return new Response("OK", 200);
}

function main(): void {
    const req = new Request("/api/data");
    const resp = httpServer(req);
    console.log("Status: " + resp.status);
}

main();
