// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

#[derive(Clone)]
struct Request {
    url: String,
}

#[derive(Clone)]
struct Response {
    data: String,
    status: i64,
}

fn http_server(rx: mpsc::Receiver<Request>, main_tx: mpsc::Sender<Response>) {
    for req in rx {
        let resp = Response { data: String::from("OK"), status: 200 };
        let _ = main_tx.send(resp);
    }
}

fn main() {
    let (server_tx, server_rx) = mpsc::channel::<Request>();
    let (main_tx, main_rx) = mpsc::channel::<Response>();

    std::thread::spawn(move || {
        http_server(server_rx, main_tx);
    });

    server_tx.send(Request { url: String::from("/api/data") }).unwrap();

    match main_rx.recv() {
        Ok(resp) => {
            println!("{}", "Status: ".to_string() + &resp.status.to_string());
        }
        Err(_) => {}
    }
}
