# Auto-generated by a2p transpiler

import threading
import queue

class Request:
    def __init__(self, url: str):
        self.url = url

class Response:
    def __init__(self, data: str, status: int):
        self.data = data
        self.status = status

def http_server(in_q, out_q):
    while True:
        try:
            req = in_q.get(timeout=1.0)
            resp = Response(data="OK", status=200)
            out_q.put(resp)
        except queue.Empty:
            break

def main():
    in_q = queue.Queue()
    out_q = queue.Queue()
    t = threading.Thread(target=http_server, args=(in_q, out_q))
    t.daemon = True
    t.start()
    in_q.put(Request(url="/api/data"))
    try:
        resp = out_q.get(timeout=2.0)
        print("Status: " + str(resp.status))
    except queue.Empty:
        pass
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
