// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct Request {
    const char* url;
} Request;

typedef struct Response {
    const char* data;
    int status;
} Response;

void http_server_fn(Request req, Response* resp) {
    resp->data = "OK";
    resp->status = 200;
}

int main(void) {
    Request req = { .url = "/api/data" };
    Response resp;
    http_server_fn(req, &resp);
    printf("Status: %d\n", resp.status);
    return 0;
}
