// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone)]
struct Config {
    input_path: String,
    output_path: String,
    verbose: bool,
}

fn validate(c: Config) -> Result<Config, String> {
    if c.input_path == String::from("") {
        Err(String::from("input path cannot be empty"))
    } else {
        Ok(c)
    }
}

fn main() -> Result<(), String> {
    let config = Config { input_path: String::from("data.txt"), output_path: String::from("result.txt"), verbose: true };
    let valid = validate(config)?;
    println!("{}", valid.input_path);
    Ok(())
}
