# Auto-generated by a2p transpiler

class Config:
    def __init__(self, input_path: str, output_path: str, verbose: bool):
        self.input_path = input_path
        self.output_path = output_path
        self.verbose = verbose

class ValidationError(Exception):
    pass

def validate(c: Config) -> Config:
    if c.input_path == "":
        raise ValidationError("input path cannot be empty")
    return c

def main():
    config = Config(input_path="data.txt", output_path="result.txt", verbose=True)
    valid = validate(config)
    print(valid.input_path)

if __name__ == "__main__":
    main()
