// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct Config {
    const char* input_path;
    const char* output_path;
    bool verbose;
} Config;

typedef struct ResultConfig {
    bool is_ok;
    Config ok_value;
    const char* err_value;
} ResultConfig;

ResultConfig validate(Config c) {
    ResultConfig r;
    if (strcmp(c.input_path, "") == 0) {
        r.is_ok = false;
        r.ok_value = (Config){0};
        r.err_value = "input path cannot be empty";
    } else {
        r.is_ok = true;
        r.ok_value = c;
        r.err_value = NULL;
    }
    return r;
}

int main(void) {
    Config config = { .input_path = "data.txt", .output_path = "result.txt", .verbose = true };
    ResultConfig valid = validate(config);
    if (!valid.is_ok) {
        fprintf(stderr, "Error: %s\n", valid.err_value);
        return 1;
    }
    printf("%s\n", valid.ok_value.input_path);
    return 0;
}
