// Auto-generated by a2ts transpiler

class Config {
    input_path: string;
    output_path: string;
    verbose: boolean;

    constructor(input_path: string, output_path: string, verbose: boolean) {
        this.input_path = input_path;
        this.output_path = output_path;
        this.verbose = verbose;
    }
}

function validate(c: Config): Config {
    if (c.input_path === "") {
        throw new Error("input path cannot be empty");
    }
    return c;
}

function main(): void {
    const config = new Config("data.txt", "result.txt", true);
    const valid = validate(config);
    console.log(valid.input_path);
}

main();
