// Auto-generated by a2ts transpiler

function is_even(n: number): boolean {
    if (n % 2 === 0) {
        return true;
    } else {
        return false;
    }
}

function main(): void {
    console.log(is_even(4));
    console.log(is_even(7));
}

main();
