// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

bool is_even(long long n) {
    if (n % 2 == 0) {
        return true;
    } else {
        return false;
    }
}

int main(void) {
    printf("%s\n", is_even(4) ? "true" : "false");
    printf("%s\n", is_even(7) ? "true" : "false");
    return 0;
}
