# Auto-generated by a2p transpiler

def is_even(n):
    if n % 2 == 0:
        return True
    else:
        return False

def main():
    print(is_even(4))
    print(is_even(7))

if __name__ == "__main__":
    main()
