// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn is_even(n: i64) -> bool {
    if n % 2 == 0 {
        true
    } else {
        false
    }
}

fn main() {
    println!("{}", is_even(4));
    println!("{}", is_even(7));
}
