// Auto-generated by a2ts transpiler

class Pair<T> {
    first: T;
    second: T;

    constructor(first: T, second: T) {
        this.first = first;
        this.second = second;
    }

    swap(): Pair<T> {
        return new Pair(this.second, this.first);
    }
}

function main(): void {
    const p = new Pair(1, 2);
    const p2 = p.swap();
    console.log(p2.first);
    console.log(p2.second);
}

main();
