# Auto-generated by a2p transpiler

from typing import Generic, TypeVar

T = TypeVar('T')

class Pair(Generic[T]):
    def __init__(self, first: T, second: T):
        self.first = first
        self.second = second

    def swap(self) -> 'Pair[T]':
        return Pair(first=self.second, second=self.first)

def main():
    p = Pair(first=1, second=2)
    p2 = p.swap()
    print(p2.first)
    print(p2.second)

if __name__ == "__main__":
    main()
