// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Pair<T> {
    first: T,
    second: T,
}

impl<T: Clone> Pair<T> {
    fn swap(&self) -> Pair<T> {
        Pair { first: self.second.clone(), second: self.first.clone() }
    }
}

fn main() {
    let p = Pair { first: 1, second: 2 };
    let p2 = p.swap();
    println!("{}", p2.first);
    println!("{}", p2.second);
}
