// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct PairInt {
    long long first;
    long long second;
} PairInt;

PairInt PairInt_swap(const PairInt* self) {
    return (PairInt){ .first = self->second, .second = self->first };
}

int main(void) {
    PairInt p = { .first = 1, .second = 2 };
    PairInt p2 = PairInt_swap(&p);
    printf("%lld\n", p2.first);
    printf("%lld\n", p2.second);
    return 0;
}
