// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let number: i32 = 3;

    if number < 5 {
        println!("condition was true");
    } else {
        println!("condition was false");
    }



    let condition: bool = true;
    let x: i32 = if condition {
        5
    } else {
        6
    };
    println!("x = {}", x);
}
