// Auto-generated by a2r transpiler

fn main() {
    let number: i64 = 3;

    if number < 5 {
        println!("condition was true");
    } else {
        println!("condition was false");
    }



    let condition: bool = true;
    let x: i64 = if condition {
        5
    } else {
        6
    };
    println!("x = {}", x);
}
