// Auto-generated by a2r transpiler

fn append_world(mut s: String) {
    s.append(" world");
}

fn main() {
    let mut s1: String = String::from("hello");
    append_world(&mut s1);
    println!("{}", s1);
}
