// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn append_world(s: String) {
    s.push_str(" world");
}

fn main() {
    let mut s1: String = String::from("hello");
    append_world(&mut s1);
    println!("{}", s1);
}
