// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::time::Duration;

fn main() {
    trpl::block_on(async {
        let (tx, mut rx) = trpl::channel();

        trpl::spawn_task(async move {
            for i in 1..6 {
                tx.send(i).unwrap();
                trpl::sleep(Duration::from_secs(1)).await;
            }
        });

        while let Some(value) = rx.recv().await {
            println!("Received: {value}");
        }
    })
}
