// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[cfg(debug_assertions)]
fn log(msg: &str) {
    println!("[DEBUG] {msg}");
}

#[cfg(not(debug_assertions))]
fn log(msg: &str) {
    // No-op in release builds
}

fn main() {
    log("Starting application");
}
