// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn apply(f: fn(i32) -> i32, x: i32) -> i32 {
    f(x)
}

fn main() {
    let mut double = |x: i32| -> i32 { x * 2 };
    println!("{}", apply(double, 5));
    let mut add_one = |x: i32| -> i32 { x + 1 };
    println!("{}", apply(add_one, 10));
}
