// Auto-generated by a2ts transpiler

type FnIntToInt = (x: number) => number;

function apply(f: FnIntToInt, x: number): number {
    return f(x);
}

function main(): void {
    const double: FnIntToInt = (x: number) => x * 2;
    console.log(apply(double, 5));
    const addOne: FnIntToInt = (x: number) => x + 1;
    console.log(apply(addOne, 10));
}

main();
