# Auto-generated by a2p transpiler

def apply(f, x):
    return f(x)

def main():
    double = lambda x: x * 2
    print(apply(double, 5))
    add_one = lambda x: x + 1
    print(apply(add_one, 10))

if __name__ == "__main__":
    main()
