// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

typedef int (*FnIntToInt)(int);

int apply(FnIntToInt f, int x) {
    return f(x);
}

int double_fn(int x) {
    return x * 2;
}

int add_one_fn(int x) {
    return x + 1;
}

int main(void) {
    FnIntToInt double_f = double_fn;
    printf("%d\n", apply(double_f, 5));
    FnIntToInt add_one = add_one_fn;
    printf("%d\n", apply(add_one, 10));
    return 0;
}
