// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let s1: String = String::from("hello");
    let s2: String = s1;
    println!("{}", s2);

}
