// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let x: i32 = 10;

    match x {
        0 => println!("zero"),
        1 => println!("one"),
        _ => println!("other"),
    }
}
