// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn first_word(s: String) -> i32 {
    let bytes = s.bytes();
    let mut i: i32 = 0;
    for b in bytes {
                i = i + 1;
    }
    return s.len();
}

fn main() {
    let mut s: String = String::from("hello world");
    let word = first_word(&s);
    println!("first word ends at index {}", word);

    s.clear();

    println!("stale index = {}", word);
}
