// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

fn first_word(mut s: String) -> i64 {
    let bytes = s.bytes();
    let mut i: i64 = 0;
    for b in &bytes {
        if b == 32 {
            return i;
        }
        i = i + 1;
    }
    return a2r_std::value_len(&s);
}

fn main() {
    let mut s: String = String::from("hello world");
    let word = first_word(&s);
    println!("first word ends at index {}", word);

    s.clear();

    println!("stale index = {}", word);
}
