// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let value = "42".to_int().expect("should be a number");
    println!("Value: {}", value);
}
