// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Math {
    pub value: i64,
}

impl Math {
    fn new(value: i64) -> Math {
        Math { value: value }
    }
    fn add(&self, other: i64) -> Math {
        Math { value: self.value + other }
    }
    fn double(&self) -> Math {
        self.add(self.value)
    }
    fn result(&self) -> i64 {
        self.value
    }
}

fn main() {
    let m = Math::new(5);
    let doubled = m.double();
    println!("Result: {}", doubled.result());
}
