// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq)]
struct Math {
    value: i32,
}

impl Math {
    fn new(&self, value: i32) -> Math {
        Math { value: value };
    }
    fn add(&self, other: i32) -> Math {
        Math { value: self.value + other };
    }
    fn double(&self) -> Math {
        self.add(self.value)
    }
    fn result(&self) -> i32 {
        self.value
    }
}

fn main() {
    let m = Math::new(5);
    let doubled = m.double();
    println!("Result: {}", doubled.result());
}
