// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

void worker_fn(int n, int* result) {
    *result = n * 2;
}

int main(void) {
    int result = 0;
    worker_fn(10, &result);
    long long total = 0;
    total = total + result;
    printf("Total so far: %lld\n", total);
    return 0;
}
