# Auto-generated by a2p transpiler

import threading
import queue

def worker(in_q, out_q):
    while True:
        try:
            n = in_q.get(timeout=1.0)
            out_q.put(n * 2)
        except queue.Empty:
            break

def main():
    in_q = queue.Queue()
    out_q = queue.Queue()
    t = threading.Thread(target=worker, args=(in_q, out_q))
    t.daemon = True
    t.start()
    in_q.put(10)
    result = out_q.get(timeout=2.0)
    total = 0
    total = total + result
    print("Total so far: " + str(total))
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
