// Auto-generated by a2ts transpiler

function worker(n: number): number {
    return n * 2;
}

function main(): void {
    let total = 0;
    const result = worker(10);
    total = total + result;
    console.log("Total so far: " + total);
}

main();
