// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

fn worker(rx: mpsc::Receiver<i64>, main_tx: mpsc::Sender<i64>) {
    for n in rx {
        let _ = main_tx.send(n * 2);
    }
}

fn main() {
    let (worker_tx, worker_rx) = mpsc::channel::<i64>();
    let (main_tx, main_rx) = mpsc::channel::<i64>();

    std::thread::spawn(move || {
        worker(worker_rx, main_tx);
    });

    worker_tx.send(10).unwrap();

    match main_rx.recv() {
        Ok(result) => {
            let mut total: i64 = 0;
            total = total + result;
            println!("{}", "Total so far: ".to_string() + &total.to_string());
        }
        Err(_) => {}
    }
}
