// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {

    let mut counter: i32 = 0;
    loop {
                counter = counter + 1;
    }
    println!("counter reached {}", counter);


    let mut number: i32 = 3;
    loop {
        println!("{}", number);
        number = number - 1;
            }
    println!("LIFTOFF!");


    let a: [i32; 3] = [10, 20, 30];
    for element in a {
        println!("{}", element);
    }
}
