// Auto-generated by a2r transpiler

fn main() {

    let mut counter: i64 = 0;
    loop {
        if counter == 10 {
            break;
        }
        counter = counter + 1;
    }
    println!("counter reached {}", counter);


    let mut number: i64 = 3;
    loop {
        println!("{}", number);
        number = number - 1;
        if number == 0 {
            break;
        }
    }
    println!("LIFTOFF!");


    let a: Vec<i64> = vec![10, 20, 30];
    for element in &a {
        println!("{}", element);
    }
}
