# Auto-generated by a2p transpiler

from typing import Generic, TypeVar

T = TypeVar('T')

class Box(Generic[T]):
    def __init__(self, value: T):
        self.value = value

    @staticmethod
    def new(v: T) -> 'Box[T]':
        return Box(value=v)

    def get(self) -> T:
        return self.value

def main():
    i = Box.new(42)
    print(i.get())
    s = Box.new("hello")
    print(s.get())

if __name__ == "__main__":
    main()
