// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct BoxInt {
    long long value;
} BoxInt;

BoxInt BoxInt_new(long long v) {
    return (BoxInt){ .value = v };
}

long long BoxInt_get(const BoxInt* self) {
    return self->value;
}

typedef struct BoxStr {
    const char* value;
} BoxStr;

BoxStr BoxStr_new(const char* v) {
    return (BoxStr){ .value = v };
}

const char* BoxStr_get(const BoxStr* self) {
    return self->value;
}

int main(void) {
    BoxInt i = BoxInt_new(42);
    printf("%lld\n", BoxInt_get(&i));
    BoxStr s = BoxStr_new("hello");
    printf("%s\n", BoxStr_get(&s));
    return 0;
}
