// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Box<T> {
    value: T,
}

impl<T: Clone> Box<T> {
    fn new(v: T) -> Box<T> {
        Box { value: v }
    }
    fn get(&self) -> T {
        self.value.clone()
    }
}

fn main() {
    let i = Box::new(42);
    println!("{}", i.get());
    let s = Box::new(String::from("hello"));
    println!("{}", s.get());
}
