// Auto-generated by a2ts transpiler

class Box<T> {
    value: T;

    constructor(value: T) {
        this.value = value;
    }

    static new(v: T): Box<T> {
        return new Box(v);
    }

    get(): T {
        return this.value;
    }
}

function main(): void {
    const i = Box.new(42);
    console.log(i.get());
    const s = Box.new("hello");
    console.log(s.get());
}

main();
