// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Config {
    input_path: String,
    output_path: String,
    verbose: bool,
}

fn parse_args() -> Config {
    Config {
        input_path: String::from("input.txt"),
        output_path: String::from("output.txt"),
        verbose: false,
    }
}

fn main() {
    let config = parse_args();
    println!("{}", "Input: ".to_string() + &config.input_path);
    println!("{}", "Output: ".to_string() + &config.output_path);
}
