# Auto-generated by a2p transpiler

class Config:
    def __init__(self, input_path: str, output_path: str, verbose: bool):
        self.input_path = input_path
        self.output_path = output_path
        self.verbose = verbose

def parse_args() -> Config:
    return Config(
        input_path="input.txt",
        output_path="output.txt",
        verbose=False
    )

def main():
    config = parse_args()
    print("Input: " + config.input_path)
    print("Output: " + config.output_path)

if __name__ == "__main__":
    main()
