// Auto-generated by a2ts transpiler

class Config {
    input_path: string;
    output_path: string;
    verbose: boolean;

    constructor(input_path: string, output_path: string, verbose: boolean) {
        this.input_path = input_path;
        this.output_path = output_path;
        this.verbose = verbose;
    }
}

function parse_args(): Config {
    return new Config("input.txt", "output.txt", false);
}

function main(): void {
    const config = parse_args();
    console.log("Input: " + config.input_path);
    console.log("Output: " + config.output_path);
}

main();
