// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

typedef struct Config {
    const char* input_path;
    const char* output_path;
    bool verbose;
} Config;

Config parse_args(void) {
    Config c;
    c.input_path = "input.txt";
    c.output_path = "output.txt";
    c.verbose = false;
    return c;
}

int main(void) {
    Config config = parse_args();
    printf("Input: %s\n", config.input_path);
    printf("Output: %s\n", config.output_path);
    return 0;
}
