// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Rectangle {
    pub width: i64,
    pub height: i64,
}

impl Rectangle {
    fn area(&self) -> i64 {
        self.width * self.height
    }
    fn is_square(&self) -> bool {
        self.width == self.height
    }
}

fn main() {
    let rect1 = Rectangle { width: 30, height: 50 };
    let rect2 = Rectangle { width: 40, height: 40 };

    println!("rect1 area: {}", rect1.area());
    println!("rect1 is square: {}", rect1.is_square());
    println!("rect2 is square: {}", rect2.is_square());
}
