// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {

    let sum: i32 = 5 + 10;
    let difference: i32 = 95 - 4;
    let product: i32 = 4 * 30;
    let quotient: i32 = 56 / 32;
    let remainder = 43 % 5;

    println!("sum = {}", sum);
    println!("difference = {}", difference);
    println!("product = {}", product);
    println!("quotient = {}", quotient);
    println!("remainder = {}", remainder);


    let t: bool = true;
    let f: bool = false;
    println!("t = {}, f = {}", t, f);
}
