// Auto-generated by a2r transpiler

fn main() {

    let sum: i64 = 5 + 10;
    let difference: i64 = 95 - 4;
    let product: i64 = 4 * 30;
    let quotient: i64 = 56 / 32;
    let mut remainder = 43 % 5;

    println!("sum = {}", sum);
    println!("difference = {}", difference);
    println!("product = {}", product);
    println!("quotient = {}", quotient);
    println!("remainder = {}", remainder);


    let t: bool = true;
    let f: bool = false;
    println!("t = {}, f = {}", t, f);
}
