// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn process(value: std::fmt::Display) {
    println!("{}", value);
}

fn main() {
    process(42);
    process(3.14);
    process(String::from("hello"));
}
