// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef enum ValueType {
    ValueType_Int,
    ValueType_Float,
    ValueType_String,
} ValueType;

typedef struct {
    ValueType kind;
    union {
        long int_val;
        double float_val;
        const char* str_val;
    };
} Value;

void process(Value value) {
    switch (value.kind) {
        case ValueType_Int:
            printf("%ld\n", value.int_val);
            break;
        case ValueType_Float:
            printf("%f\n", value.float_val);
            break;
        case ValueType_String:
            printf("%s\n", value.str_val);
            break;
    }
}

int main(void) {
    process((Value){ .kind = ValueType_Int, .int_val = 42 });
    process((Value){ .kind = ValueType_Float, .float_val = 3.14 });
    process((Value){ .kind = ValueType_String, .str_val = "hello" });
    return 0;
}
