// Auto-generated by a2ts transpiler

function process(value: number | string): void {
    console.log(value);
}

function main(): void {
    process(42);
    process(3.14);
    process("hello");
}

main();
