// Auto-generated by a2r transpiler

fn main() {
    println!("Guess the number!");
    let secret_number: i64 = 7;
    println!("The secret number is: {}", secret_number);
    println!("Please input your guess.");

    let mut guess: String = "4".to_string();
    println!("You guessed: {}", guess);
}
