// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

void test_addition() {
    int result = 2 + 2;
    if (result != 4) {
        fprintf(stderr, "assertion failed: result == 4\n");
        __builtin_trap();
    }
}
