// Auto-generated by a2ts transpiler

function testAddition(): void {
    const result = 2 + 2;
    if (result !== 4) {
        throw new Error(`assertion failed: result === 4, got ${result}`);
    }
}
