// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut x: i64 = 10;
    let mut y: i64 = 20;
    println!("{}", x == y);
    println!("{}", x != y);
    println!("{}", x < y);
    println!("{}", x > y);
    println!("{}", x <= 10);
    println!("{}", x >= 20);
}
