// Auto-generated by a2ts transpiler

function main(): void {
    let x: number = 10;
    let y: number = 20;
    console.log(x === y);
    console.log(x !== y);
    console.log(x < y);
    console.log(x > y);
    console.log(x <= 10);
    console.log(x >= 20);
}

main();
