// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

int main(void) {
    long long x = 10;
    long long y = 20;
    printf("%s\n", (x == y) ? "true" : "false");
    printf("%s\n", (x != y) ? "true" : "false");
    printf("%s\n", (x < y) ? "true" : "false");
    printf("%s\n", (x > y) ? "true" : "false");
    printf("%s\n", (x <= 10) ? "true" : "false");
    printf("%s\n", (x >= 20) ? "true" : "false");
    return 0;
}
