# Auto-generated by a2p transpiler

def main():
    x = 10
    y = 20
    print(x == y)
    print(x != y)
    print(x < y)
    print(x > y)
    print(x <= 10)
    print(x >= 20)

if __name__ == "__main__":
    main()
