// Auto-generated by a2r transpiler

fn main() {
    let s1: String = "Hello".to_string();
    let s2: String = "world".to_string();
    let s3: String = format!("{}, {}!", s1, s2);
    println!("{}", s3);
}
