// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let s1: String = "Hello".to_string();
    let s2: String = "world".to_string();
    let s3: String = format!("{}, {}!", s1, s2);
    println!("{}", s3);
}
