// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

// Listing 21-4 is an HTML file, not transpilable Auto code.
// The file hello.html is served directly by the web server.
