// Auto-generated by a2ts transpiler

class Animal {
    name: string;

    constructor(name: string) {
        this.name = name;
    }

    speak(): void {
        console.log(`${this.name} makes a sound`);
    }
}

class Dog extends Animal {
    breed: string;

    constructor(name: string, breed: string) {
        super(name);
        this.breed = breed;
    }

    speak(): void {
        console.log(`${this.name} barks!`);
    }
}

function main(): void {
    const d = new Dog("Rex", "Labrador");
    d.speak();
}

main();
