// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    char name[256];
} Animal;

void Animal_speak(const Animal* self) {
    printf("%s makes a sound\n", self->name);
}

typedef struct {
    Animal base;
    char breed[256];
} Dog;

void Dog_speak(const Dog* self) {
    printf("%s barks!\n", self->base.name);
}

int main(void) {
    Dog d;
    strcpy(d.base.name, "Rex");
    strcpy(d.breed, "Labrador");
    Dog_speak(&d);
    return 0;
}
