// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Animal {
    name: String,
}

impl Animal {
    fn speak(&self) {
        println!("{} makes a sound", self.name);
    }
}

struct Dog {
    name: String,
    breed: String,
}

impl Dog {
    fn speak(&self) {
        println!("{} barks!", self.name);
    }
}

fn main() {
    let mut d = Dog {
        name: String::from("Rex"),
        breed: String::from("Labrador"),
    };
    d.speak();
}
