# Auto-generated by a2p transpiler

from dataclasses import dataclass

@dataclass
class Animal:
    name: str

    def speak(self):
        print(f"{self.name} makes a sound")

@dataclass
class Dog(Animal):
    breed: str

    def speak(self):
        print(f"{self.name} barks!")

def main():
    d = Dog(name="Rex", breed="Labrador")
    d.speak()

if __name__ == "__main__":
    main()
