// Auto-generated by a2ts transpiler

function main(): void {
    let count: number = 0;
    const name: string = "Alice";
    let pi: number = 3.14159;
    const active: boolean = true;
    console.log(count);
    console.log(name);
    console.log(pi);
    console.log(active);
}

main();
