// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

int main(void) {
    long long count = 0;
    const char* name = "Alice";
    double pi = 3.14159;
    const bool active = true;
    printf("%lld\n", count);
    printf("%s\n", name);
    printf("%f\n", pi);
    printf("%s\n", active ? "true" : "false");
    return 0;
}
