# Auto-generated by a2p transpiler

def main():
    count: int = 0
    name: str = "Alice"
    pi: float = 3.14159
    active: bool = True
    print(count)
    print(name)
    print(pi)
    print(active)

if __name__ == "__main__":
    main()
