// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut count: i64 = 0;
    let name: String = String::from("Alice");
    let mut pi: f64 = 3.14159;
    let active: bool = true;
    println!("{}", count);
    println!("{}", name);
    println!("{}", pi);
    println!("{}", active);
}
