// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

int MathUtils_add(int a, int b) {
    return a + b;
}

void test_add() {
    if (MathUtils_add(2, 3) != 5) {
        fprintf(stderr, "assertion failed: MathUtils_add(2, 3) == 5\n");
        __builtin_trap();
    }
}

int main(void) {
    printf("Run tests with: automan test\n");
    return 0;
}
