// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait MathUtils {
    fn add(a: i32, b: i32) -> i32;
}

impl MathUtils for MathUtils {
    fn add(a: i32, b: i32) -> i32 { a + b }
}

#[test]
fn test_add() {
    assert_eq!(MathUtils::add(2, 3), 5);
}

fn main() {
    println!("Run tests with: automan test");
}
