# Auto-generated by a2p transpiler

from abc import ABC, abstractmethod

class MathUtils(ABC):
    @staticmethod
    @abstractmethod
    def add(a, b):
        pass

class MathUtilsImpl(MathUtils):
    @staticmethod
    def add(a, b):
        return a + b

def test_add():
    assert MathUtilsImpl.add(2, 3) == 5

def main():
    print("Run tests with: automan test")

if __name__ == "__main__":
    main()
