// Auto-generated by a2ts transpiler

abstract class MathUtils {
    static add(a: number, b: number): number {
        throw new Error("Not implemented");
    }
}

class MathUtilsImpl extends MathUtils {
    static add(a: number, b: number): number {
        return a + b;
    }
}

function testAdd(): void {
    if (MathUtilsImpl.add(2, 3) !== 5) {
        throw new Error(`assertion failed: MathUtilsImpl.add(2, 3) === 5`);
    }
}

function main(): void {
    console.log("Run tests with: automan test");
}

main();
