// Auto-generated by a2ts transpiler

import * as fs from "fs";

function readConfig(path: string): string {
    const content = fs.readFileSync(path, "utf-8");
    return content;
}

function main(): void {
    const config = readConfig("config.txt");
    console.log(config);
}

main();
