// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    char value[4096];
    int _ok;
    char error[256];
} StringResult;

StringResult read_file(const char* path) {
    StringResult r;
    FILE* f = fopen(path, "r");
    if (f == NULL) {
        r._ok = 0;
        snprintf(r.error, sizeof(r.error), "file not found: %s", path);
        return r;
    }
    fgets(r.value, sizeof(r.value), f);
    fclose(f);
    r._ok = 1;
    return r;
}

StringResult read_config(const char* path) {
    StringResult content = read_file(path);
    if (!content._ok) {
        return content;
    }
    return content;
}

int main(void) {
    StringResult config = read_config("config.txt");
    if (config._ok) {
        printf("%s\n", config.value);
    } else {
        printf("Error: %s\n", config.error);
    }
    return 0;
}
