// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn read_config(path: String) -> Result<String, String> {
    let mut content = read_file(&path)?;
    Ok(content)
}

fn main() {
    let mut config = read_config(String::from("config.txt")).unwrap();
    println!("{}", config);
}
