# Auto-generated by a2p transpiler

def read_config(path: str) -> str:
    with open(path, "r") as f:
        content = f.read()
    return content

def main():
    config = read_config("config.txt")
    print(config)

if __name__ == "__main__":
    main()
