// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

#define MAX_CLIENTS 64
#define MAX_ROOM_MEMBERS 64
#define MAX_ROOMS 8
#define MAX_NAME 64
#define MAX_FIELD 256

typedef enum MessageKind {
    MsgKind_Connect,
    MsgKind_Disconnect,
    MsgKind_Chat,
    MsgKind_PrivateMsg,
    MsgKind_System,
    MsgKind_JoinRoom,
    MsgKind_LeaveRoom,
    MsgKind_RoomMsg,
} MessageKind;

typedef struct Message {
    MessageKind kind;
    char field1[MAX_FIELD];
    char field2[MAX_FIELD];
    char field3[MAX_FIELD];
} Message;

typedef struct {
    char name[MAX_NAME];
    char members[MAX_ROOM_MEMBERS][MAX_NAME];
    int member_count;
} Room;

Room rooms[MAX_ROOMS];
int room_count = 0;
int client_count = 0;

Room* find_room(const char* name) {
    for (int i = 0; i < room_count; i++) {
        if (strcmp(rooms[i].name, name) == 0) return &rooms[i];
    }
    return NULL;
}

void add_room(const char* name) {
    strncpy(rooms[room_count].name, name, MAX_NAME - 1);
    rooms[room_count].member_count = 0;
    room_count++;
}

void server_handle(Message* msg) {
    switch (msg->kind) {
        case MsgKind_Connect:
            client_count++;
            printf("[SYS] %s joined. Online: %d\n", msg->field1, client_count);
            break;
        case MsgKind_Disconnect:
            client_count--;
            printf("[SYS] %s left. Online: %d\n", msg->field1, client_count);
            break;
        case MsgKind_Chat:
            printf("%s: %s\n", msg->field1, msg->field2);
            break;
        case MsgKind_PrivateMsg:
            printf("[PM] %s -> %s: %s\n", msg->field1, msg->field2, msg->field3);
            break;
        case MsgKind_System:
            printf("[SYS] %s\n", msg->field1);
            break;
        case MsgKind_JoinRoom:
            printf("[SYS] %s joined #%s\n", msg->field1, msg->field2);
            break;
        case MsgKind_LeaveRoom:
            printf("[SYS] %s left #%s\n", msg->field1, msg->field2);
            break;
        case MsgKind_RoomMsg:
            printf("[#%s] %s: %s\n", msg->field1, msg->field2, msg->field3);
            break;
    }
}

int main(void) {
    int port = 8080;
    printf("Starting chat server on port %d\n", port);
    add_room("general");
    add_room("random");
    printf("Chat server is running.\n");
    printf("Type /quit to stop the server.\n");
    printf("Server is running on port %d\n", port);
    printf("Shutting down server...\n");
    return 0;
}
