// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;
use std::collections::HashMap;

enum Message {
    Connect(String),
    Disconnect(String),
    Chat(String, String),
    PrivateMsg(String, String, String),
    System(String),
    JoinRoom(String, String),
    LeaveRoom(String, String),
    RoomMsg(String, String, String),
}

fn server(rx: mpsc::Receiver<Message>) {
    let mut clients: HashMap<String, i64> = HashMap::new();
    let mut rooms: HashMap<String, Vec<String>> = HashMap::new();
    rooms.insert(String::from("general"), Vec::new());
    rooms.insert(String::from("random"), Vec::new());
    for msg in rx {
        match msg {
            Message::Connect(name) => {
                clients.insert(name.clone(), 1);
                rooms.get_mut("general").unwrap().push(name.clone());
                println!("[SYS] {} joined. Online: {}", name, clients.len());
            }
            Message::Disconnect(name) => {
                clients.remove(&name);
                for (_room_name, members) in rooms.iter_mut() {
                    members.retain(|m| m != &name);
                }
                println!("[SYS] {} left. Online: {}", name, clients.len());
            }
            Message::Chat(from, text) => {
                println!("{}: {}", from, text);
            }
            Message::PrivateMsg(from, to, text) => {
                println!("[PM] {} -> {}: {}", from, to, text);
            }
            Message::System(text) => {
                println!("[SYS] {}", text);
            }
            Message::JoinRoom(name, room_name) => {
                if let Some(members) = rooms.get_mut(&room_name) {
                    members.push(name.clone());
                    println!("[SYS] {} joined #{}", name, room_name);
                }
            }
            Message::LeaveRoom(name, room_name) => {
                if let Some(members) = rooms.get_mut(&room_name) {
                    members.retain(|m| m != &name);
                }
                println!("[SYS] {} left #{}", name, room_name);
            }
            Message::RoomMsg(room_name, from, text) => {
                println!("[#{}] {}: {}", room_name, from, text);
            }
        }
    }
}

fn main() {
    let port: i64 = 8080;
    println!("Starting chat server on port {}", port);
    let (tx, rx) = mpsc::channel::<Message>();
    std::thread::spawn(move || {
        server(rx);
    });
    println!("Chat server is running.");
    println!("Type /quit to stop the server.");
    // Simulated: read "/status" then "/quit"
    println!("Server is running on port {}", port);
    println!("Shutting down server...");
}
