// Auto-generated by a2ts transpiler

type Message =
    | { kind: "Connect"; field1: string }
    | { kind: "Disconnect"; field1: string }
    | { kind: "Chat"; field1: string; field2: string }
    | { kind: "PrivateMsg"; field1: string; field2: string; field3: string }
    | { kind: "System"; field1: string }
    | { kind: "JoinRoom"; field1: string; field2: string }
    | { kind: "LeaveRoom"; field1: string; field2: string }
    | { kind: "RoomMsg"; field1: string; field2: string; field3: string };

function server(messages: Message[]): void {
    const clients = new Map<string, number>();
    const rooms = new Map<string, string[]>();
    rooms.set("general", []);
    rooms.set("random", []);

    for (const msg of messages) {
        switch (msg.kind) {
            case "Connect":
                clients.set(msg.field1, 1);
                rooms.get("general")!.push(msg.field1);
                console.log(`[SYS] ${msg.field1} joined. Online: ${clients.size}`);
                break;
            case "Disconnect":
                clients.delete(msg.field1);
                console.log(`[SYS] ${msg.field1} left. Online: ${clients.size}`);
                break;
            case "Chat":
                console.log(`${msg.field1}: ${msg.field2}`);
                break;
            case "PrivateMsg":
                console.log(`[PM] ${msg.field1} -> ${msg.field2}: ${msg.field3}`);
                break;
            case "System":
                console.log(`[SYS] ${msg.field1}`);
                break;
            case "JoinRoom":
                rooms.get(msg.field2)?.push(msg.field1);
                console.log(`[SYS] ${msg.field1} joined #${msg.field2}`);
                break;
            case "LeaveRoom":
                console.log(`[SYS] ${msg.field1} left #${msg.field2}`);
                break;
            case "RoomMsg":
                console.log(`[#${msg.field1}] ${msg.field2}: ${msg.field3}`);
                break;
        }
    }
}

function main(): void {
    const port = 8080;
    console.log(`Starting chat server on port ${port}`);
    console.log("Chat server is running.");
    console.log("Type /quit to stop the server.");
    console.log(`Server is running on port ${port}`);
    console.log("Shutting down server...");
}

main();
