// Auto-generated by a2ts transpiler

class State {
    count: number;
    name: string;

    constructor(count: number, name: string) {
        this.count = count;
        this.name = name;
    }
}

function statefulActor(messages: string[]): void {
    const state = new State(0, "counter");
    for (const cmd of messages) {
        if (cmd === "inc") {
            state.count = state.count + 1;
            console.log(state.name + ": " + state.count);
        } else {
            console.log("Unknown command: " + cmd);
        }
    }
}

function main(): void {
    const messages: string[] = ["inc", "inc", "hello"];
    statefulActor(messages);
}

main();
