// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct State {
    int count;
    const char* name;
} State;

void stateful_actor_fn(void) {
    State state = { .count = 0, .name = "counter" };
    // Simulated message loop
    state.count = state.count + 1;
    printf("%s: %d\n", state.name, state.count);
    state.count = state.count + 1;
    printf("%s: %d\n", state.name, state.count);
    printf("Unknown command: %s\n", "hello");
}

int main(void) {
    stateful_actor_fn();
    return 0;
}
