// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

#[derive(Clone)]
struct State {
    count: i64,
    name: String,
}

fn stateful_actor(rx: mpsc::Receiver<String>) {
    let mut state = State { count: 0, name: String::from("counter") };
    for cmd in rx {
        if cmd == String::from("inc") {
            state.count = state.count + 1;
            println!("{}", state.name.to_string() + ": " + &state.count.to_string());
        } else {
            println!("{}", "Unknown command: ".to_string() + &cmd);
        }
    }
}

fn main() {
    let (tx, rx) = mpsc::channel::<String>();
    std::thread::spawn(move || {
        stateful_actor(rx);
    });
    tx.send(String::from("inc")).unwrap();
    tx.send(String::from("inc")).unwrap();
    tx.send(String::from("hello")).unwrap();
}
