# Auto-generated by a2p transpiler

import threading
import queue

class State:
    def __init__(self, count: int, name: str):
        self.count = count
        self.name = name

def stateful_actor(q):
    state = State(count=0, name="counter")
    while True:
        try:
            cmd = q.get(timeout=1.0)
            if cmd == "inc":
                state.count = state.count + 1
                print(state.name + ": " + str(state.count))
            else:
                print("Unknown command: " + cmd)
        except queue.Empty:
            break

def main():
    q = queue.Queue()
    t = threading.Thread(target=stateful_actor, args=(q,))
    t.daemon = True
    t.start()
    q.put("inc")
    q.put("inc")
    q.put("hello")
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
