// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use rand::Rng;

fn main() {
    let mut secret: i64 = rand::thread_rng().gen_range(1..=100);
    println!("Guess the number between 1 and 100!");
    loop {
        let mut guess_str: String = read_line();
        let mut guess: i64 = guess_str.trim().parse().unwrap();
        println!("You guessed: {}", guess);
        if guess == secret {
            println!("You win!");
            break;
        }
        if guess < secret {
            println!("Too small!");
        } else {
            println!("Too big!");
        }
    }
}
