// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

int main(void) {
    srand(time(NULL));
    long long secret = (rand() % 100) + 1;
    printf("Guess the number between 1 and 100!\n");
    while (1) {
        char guess_str[256];
        fgets(guess_str, 256, stdin);
        guess_str[strcspn(guess_str, "\n")] = '\0';
        long long guess = atoll(guess_str);
        printf("You guessed: %lld\n", guess);
        if (guess == secret) {
            printf("You win!\n");
            break;
        }
        if (guess < secret) {
            printf("Too small!\n");
        } else {
            printf("Too big!\n");
        }
    }
    return 0;
}
