# Auto-generated by a2p transpiler

import random

def main():
    secret = random.randint(1, 100)
    print("Guess the number between 1 and 100!")
    while True:
        guess_str = input()
        guess = int(guess_str)
        print("You guessed: " + str(guess))
        if guess == secret:
            print("You win!")
            break
        if guess < secret:
            print("Too small!")
        else:
            print("Too big!")

if __name__ == "__main__":
    main()
