// Auto-generated by a2ts transpiler

import * as readline from 'readline';

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

function main(): void {
    let secret: number = Math.floor(Math.random() * 100) + 1;
    console.log("Guess the number between 1 and 100!");
    const loop = (): void => {
        rl.question("", (guess_str: string) => {
            let guess: number = parseInt(guess_str, 10);
            console.log("You guessed: " + guess);
            if (guess === secret) {
                console.log("You win!");
                rl.close();
            } else if (guess < secret) {
                console.log("Too small!");
                loop();
            } else {
                console.log("Too big!");
                loop();
            }
        });
    };
    loop();
}

main();
