// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef enum MessageKind {
    MessageKind_Connect,
    MessageKind_Disconnect,
    MessageKind_Chat,
    MessageKind_PrivateMsg,
    MessageKind_System,
} MessageKind;

typedef struct Message {
    MessageKind kind;
    const char* field1;
    const char* field2;
    const char* field3;
} Message;

Message msg_connect(const char* name) {
    Message m;
    m.kind = MessageKind_Connect;
    m.field1 = name;
    m.field2 = NULL;
    m.field3 = NULL;
    return m;
}

Message msg_chat(const char* from, const char* text) {
    Message m;
    m.kind = MessageKind_Chat;
    m.field1 = from;
    m.field2 = text;
    m.field3 = NULL;
    return m;
}

Message msg_private(const char* from, const char* to, const char* text) {
    Message m;
    m.kind = MessageKind_PrivateMsg;
    m.field1 = from;
    m.field2 = to;
    m.field3 = text;
    return m;
}

Message msg_system(const char* text) {
    Message m;
    m.kind = MessageKind_System;
    m.field1 = text;
    m.field2 = NULL;
    m.field3 = NULL;
    return m;
}

Message msg_disconnect(const char* name) {
    Message m;
    m.kind = MessageKind_Disconnect;
    m.field1 = name;
    m.field2 = NULL;
    m.field3 = NULL;
    return m;
}

void print_message(Message* m) {
    switch (m->kind) {
        case MessageKind_Connect:
            printf("%s connected\n", m->field1);
            break;
        case MessageKind_Disconnect:
            printf("%s disconnected\n", m->field1);
            break;
        case MessageKind_Chat:
            printf("%s: %s\n", m->field1, m->field2);
            break;
        case MessageKind_PrivateMsg:
            printf("[PM] %s -> %s: %s\n", m->field1, m->field2, m->field3);
            break;
        case MessageKind_System:
            printf("[SYS] %s\n", m->field1);
            break;
    }
}

int main(void) {
    Message m1 = msg_connect("Alice");
    Message m2 = msg_chat("Alice", "Hello everyone!");
    Message m3 = msg_private("Alice", "Bob", "Hi Bob!");
    Message m4 = msg_system("Alice has joined the lobby.");
    Message m5 = msg_disconnect("Alice");

    print_message(&m1);
    print_message(&m2);
    print_message(&m3);
    print_message(&m4);
    print_message(&m5);

    return 0;
}
