// Auto-generated by a2ts transpiler

type Message =
    | { kind: "Connect"; name: string }
    | { kind: "Disconnect"; name: string }
    | { kind: "Chat"; from: string; text: string }
    | { kind: "PrivateMsg"; from: string; to: string; text: string }
    | { kind: "System"; text: string };

function printMessage(msg: Message): void {
    switch (msg.kind) {
        case "Connect":
            console.log(msg.name + " connected");
            break;
        case "Disconnect":
            console.log(msg.name + " disconnected");
            break;
        case "Chat":
            console.log(msg.from + ": " + msg.text);
            break;
        case "PrivateMsg":
            console.log("[PM] " + msg.from + " -> " + msg.to + ": " + msg.text);
            break;
        case "System":
            console.log("[SYS] " + msg.text);
            break;
    }
}

function main(): void {
    const m1: Message = { kind: "Connect", name: "Alice" };
    const m2: Message = { kind: "Chat", from: "Alice", text: "Hello everyone!" };
    const m3: Message = { kind: "PrivateMsg", from: "Alice", to: "Bob", text: "Hi Bob!" };
    const m4: Message = { kind: "System", text: "Alice has joined the lobby." };
    const m5: Message = { kind: "Disconnect", name: "Alice" };

    printMessage(m1);

    if (m2.kind === "Chat") {
        console.log(m2.from + ": " + m2.text);
    }

    if (m3.kind === "PrivateMsg") {
        console.log("[PM] " + m3.from + " -> " + m3.to + ": " + m3.text);
    }

    if (m4.kind === "System") {
        console.log("[SYS] " + m4.text);
    }

    if (m5.kind === "Disconnect") {
        console.log(m5.name + " disconnected");
    }
}

main();
