# Auto-generated by a2p transpiler

from enum import Enum
from dataclasses import dataclass
from typing import Union

class MessageKind(Enum):
    Connect = 1
    Disconnect = 2
    Chat = 3
    PrivateMsg = 4
    System = 5

@dataclass
class Connect:
    name: str

@dataclass
class Disconnect:
    name: str

@dataclass
class Chat:
    from_: str
    text: str

@dataclass
class PrivateMsg:
    from_: str
    to: str
    text: str

@dataclass
class System:
    text: str

Message = Union[Connect, Disconnect, Chat, PrivateMsg, System]

def match_message(msg):
    if isinstance(msg, Connect):
        print(msg.name + " connected")
    elif isinstance(msg, Disconnect):
        print(msg.name + " disconnected")
    elif isinstance(msg, Chat):
        print(msg.from_ + ": " + msg.text)
    elif isinstance(msg, PrivateMsg):
        print("[PM] " + msg.from_ + " -> " + msg.to + ": " + msg.text)
    elif isinstance(msg, System):
        print("[SYS] " + msg.text)

def main():
    m1 = Connect(name="Alice")
    m2 = Chat(from_="Alice", text="Hello everyone!")
    m3 = PrivateMsg(from_="Alice", to="Bob", text="Hi Bob!")
    m4 = System(text="Alice has joined the lobby.")
    m5 = Disconnect(name="Alice")

    match_message(m1)

    if isinstance(m2, Chat):
        print(m2.from_ + ": " + m2.text)

    if isinstance(m3, PrivateMsg):
        print("[PM] " + m3.from_ + " -> " + m3.to + ": " + m3.text)

    if isinstance(m4, System):
        print("[SYS] " + m4.text)

    if isinstance(m5, Disconnect):
        print(m5.name + " disconnected")

if __name__ == "__main__":
    main()
