// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Message {
    Connect(String),
    Disconnect(String),
    Chat(String, String),
    PrivateMsg(String, String, String),
    System(String),
}

fn main() {
    let m1 = Message::Connect(String::from("Alice"));
    let m2 = Message::Chat(String::from("Alice"), String::from("Hello everyone!"));
    let m3 = Message::PrivateMsg(String::from("Alice"), String::from("Bob"), String::from("Hi Bob!"));
    let m4 = Message::System(String::from("Alice has joined the lobby."));
    let m5 = Message::Disconnect(String::from("Alice"));

    match m1 {
        Message::Connect(name) => println!("{} connected", name),
        Message::Disconnect(name) => println!("{} disconnected", name),
        Message::Chat(from, text) => println!("{}: {}", from, text),
        Message::PrivateMsg(from, to, text) => println!("[PM] {} -> {}: {}", from, to, text),
        Message::System(text) => println!("[SYS] {}", text),
    }

    match m2 {
        Message::Chat(from, text) => println!("{}: {}", from, text),
        _ => (),
    }

    match m3 {
        Message::PrivateMsg(from, to, text) => println!("[PM] {} -> {}: {}", from, to, text),
        _ => (),
    }

    match m4 {
        Message::System(text) => println!("[SYS] {}", text),
        _ => (),
    }

    match m5 {
        Message::Disconnect(name) => println!("{} disconnected", name),
        _ => (),
    }
}
