# Auto-generated by a2p transpiler

from abc import ABC, abstractmethod
from dataclasses import dataclass

class Reader(ABC):
    @abstractmethod
    def read(self) -> str:
        pass

@dataclass
class File:
    path: str

    def read(self) -> str:
        return f"Contents of {self.path}"

def main():
    f = File(path="hello.txt")
    print(f.read())

if __name__ == "__main__":
    main()
