// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Reader {
    fn read(&self) -> String;
}

struct File {
    path: String,
}

impl Reader for File {
    fn read(&self) -> String {
        format!("Contents of {}", self.path)
    }
}

fn main() {
    let mut f = File { path: String::from("hello.txt") };
    println!("{}", f.read());
}
