// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    char path[256];
} File;

const char* File_read(const File* self) {
    static char buf[512];
    snprintf(buf, sizeof(buf), "Contents of %s", self->path);
    return buf;
}

int main(void) {
    File f;
    strcpy(f.path, "hello.txt");
    printf("%s\n", File_read(&f));
    return 0;
}
