// Auto-generated by a2ts transpiler

interface Reader {
    read(): string;
}

class File implements Reader {
    path: string;

    constructor(path: string) {
        this.path = path;
    }

    read(): string {
        return `Contents of ${this.path}`;
    }
}

function main(): void {
    const f = new File("hello.txt");
    console.log(f.read());
}

main();
