// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    trpl::block_on(async {
        let (tx, mut rx) = trpl::channel();

        let tx1 = tx.clone();
        let tx_fut1 = async move {
            tx1.send("from task 1".to_string()).unwrap();
        };

        let tx_fut2 = async move {
            tx.send("from task 2".to_string()).unwrap();
        };

        let rx_fut = async {
            while let Some(msg) = rx.recv().await {
                println!("Received: {}", msg);
            }
        };

        trpl::join!(tx_fut1, tx_fut2, rx_fut);
    })
}
