// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut v = List::new();
    v.push(10);
    v.push(20);
    v.push(30);

    let third: i32 = v[2].unwrap_or(0);
    let missing: i32 = v[100].unwrap_or(0);
    println!("Third: {}", third);
    println!("Missing: {}", missing);
}
