// Auto-generated by a2r transpiler

fn main() {
    let mut v = Vec::new();
    v.push(10);
    v.push(20);
    v.push(30);

    let third: i64 = v[2].clone().unwrap_or(0);
    let missing: i64 = v[100].clone().unwrap_or(0);
    println!("Third: {}", third);
    println!("Missing: {}", missing);
}
