// Auto-generated by a2r transpiler

#[cfg(test)]
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[test]
fn test_greeting() {
    let mut greeting = String::from("Hello");
    assert!(greeting.contains("Hello"));
}

fn main() {
    println!("Run: automan test");
}
