# Auto-generated by a2p transpiler

import unittest

class TestGreeting(unittest.TestCase):
    def test_greeting(self):
        greeting = "Hello"
        self.assertIn("Hello", greeting)

def main():
    print("Run: automan test")

if __name__ == "__main__":
    main()
