// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>

void test_greeting() {
    const char* greeting = "Hello";
    assert(strstr(greeting, "Hello") != NULL);
}

int main(void) {
    printf("Run: automan test\n");
    return 0;
}
