// Auto-generated by a2ts transpiler

import assert from "assert";

function testGreeting(): void {
    const greeting: string = "Hello";
    assert.ok(greeting.includes("Hello"));
}

function main(): void {
    console.log("Run: automan test");
}

main();
