// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Counter {
    count: i64,
}

impl Counter {
    fn increment(&mut self) {
        self.count = self.count + 1;
    }
    fn get(&self) -> i64 {
        self.count
    }
}

fn main() {
    let mut c = Counter { count: 0 };
    c.increment();
    c.increment();
    c.increment();
    println!("{}", c.get());  // 3
}
