# Auto-generated by a2p transpiler

class Counter:
    def __init__(self, count: int):
        self.count = count

    def increment(self) -> None:
        self.count = self.count + 1

    def get(self) -> int:
        return self.count

def main():
    c = Counter(count=0)
    c.increment()
    c.increment()
    c.increment()
    print(c.get())  # 3

if __name__ == "__main__":
    main()
