// Auto-generated by a2ts transpiler

class Counter {
    count: number;

    constructor(count: number) {
        this.count = count;
    }

    increment(): void {
        this.count = this.count + 1;
    }

    get(): number {
        return this.count;
    }
}

function main(): void {
    const c = new Counter(0);
    c.increment();
    c.increment();
    c.increment();
    console.log(c.get());  // 3
}

main();
