// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct Counter {
    long long count;
} Counter;

void Counter_increment(Counter* self) {
    self->count = self->count + 1;
}

long long Counter_get(const Counter* self) {
    return self->count;
}

int main(void) {
    Counter c = { .count = 0 };
    Counter_increment(&c);
    Counter_increment(&c);
    Counter_increment(&c);
    printf("%lld\n", Counter_get(&c));  /* 3 */
    return 0;
}
