// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef enum ValueType {
    ValueType_Int,
    ValueType_String,
} ValueType;

typedef struct {
    ValueType kind;
    union {
        long int_val;
        const char* str_val;
    };
} Value;

void describe(Value value) {
    if (value.kind == ValueType_Int) {
        printf("Integer: %ld\n", value.int_val);
    } else {
        printf("String: %s\n", value.str_val);
    }
}

int main(void) {
    describe((Value){ .kind = ValueType_Int, .int_val = 42 });
    describe((Value){ .kind = ValueType_String, .str_val = "hello" });
    return 0;
}
