# Auto-generated by a2p transpiler

def describe(value):
    if isinstance(value, int):
        print("Integer: " + str(value))
    else:
        print("String: " + value)

def main():
    describe(42)
    describe("hello")

if __name__ == "__main__":
    main()
