// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn describe(value: std::fmt::Display) {
    if value is i64 {
        println!("{}", "Integer: ".to_string() + &value.to_string());
    } else {
        println!("{}", "String: ".to_string() + &value);
    }
}

fn main() {
    describe(42);
    describe(String::from("hello"));
}
