// Auto-generated by a2ts transpiler

function describe(value: number | string): void {
    if (typeof value === "number") {
        console.log("Integer: " + value);
    } else {
        console.log("String: " + value);
    }
}

function main(): void {
    describe(42);
    describe("hello");
}

main();
