// Auto-generated by a2ts transpiler

// from utils
function utilsHelper(): void {
    console.log("public helper");
}

// from network/server
function serverStart(port: number): void {
    console.log(`Server started on port ${port}`);
}

function main(): void {
    utilsHelper();
    serverStart(8080);
}

main();
