# Auto-generated by a2p transpiler

from utils import utils_helper
from network.server import server_start

def main():
    utils_helper()
    server_start(8080)

if __name__ == "__main__":
    main()
