// Auto-generated by a2c transpiler

#include <stdio.h>

/* from utils */
void utils_helper(void) {
    printf("public helper\n");
}

/* from network/server */
void server_start(long long port) {
    printf("Server started on port %lld\n", port);
}

int main(void) {
    utils_helper();
    server_start(8080);
    return 0;
}
