// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

mod utils;
mod network {
    pub mod server;
}

fn main() {
    utils::helper();
    network::server::start(8080);
}
