// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Point {
    x: f64,
    y: f64,
}

fn make_point() -> Point {
    Point { x: 1.0, y: 2.0 }
}

fn main() {
    let p = make_point();
    println!("{}", p.x);
    println!("{}", p.y);
}
