// Auto-generated by a2ts transpiler

class Point {
    x: number;
    y: number;

    constructor(x: number, y: number) {
        this.x = x;
        this.y = y;
    }
}

function makePoint(): Point {
    return new Point(1.0, 2.0);
}

function main(): void {
    const p = makePoint();
    console.log(p.x);
    console.log(p.y);
}

main();
