# Auto-generated by a2p transpiler

class Point:
    def __init__(self, x: float, y: float):
        self.x = x
        self.y = y

def make_point() -> Point:
    return Point(x=1.0, y=2.0)

def main():
    p = make_point()
    print(p.x)
    print(p.y)

if __name__ == "__main__":
    main()
