// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct Point {
    double x;
    double y;
} Point;

Point make_point(void) {
    return (Point){ .x = 1.0, .y = 2.0 };
}

int main(void) {
    Point p = make_point();
    printf("%f\n", p.x);
    printf("%f\n", p.y);
    return 0;
}
