// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {

    let x: i32 = 5;
    println!("x = {}", x);


    let mut y: i32 = 10;
    println!("y = {}", y);
    y = 20;
    println!("y = {}", y);
}
