// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct Point {
    double x;
    double y;
} Point;

const char* Point_to_string(const Point* self) {
    static char buf[64];
    snprintf(buf, sizeof(buf), "(%f, %f)", self->x, self->y);
    return buf;
}

void print_it_Point(Point item) {
    printf("%s\n", Point_to_string(&item));
}

int main(void) {
    Point p = { .x = 3.0, .y = 4.0 };
    print_it_Point(p);
    return 0;
}
