// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Printable {
    fn to_string(&self) -> String;
}

fn print_it<T: Printable>(item: T) {
    println!("{}", item.to_string());
}

struct Point {
    x: f64,
    y: f64,
}

impl Printable for Point {
    fn to_string(&self) -> String {
        format!("({}, {})", self.x, self.y)
    }
}

fn main() {
    let p = Point { x: 3.0, y: 4.0 };
    print_it(p);
}
