// Auto-generated by a2ts transpiler

interface Printable {
    toString(): string;
}

function printIt<T extends Printable>(item: T): void {
    console.log(item.toString());
}

class Point implements Printable {
    x: number;
    y: number;

    constructor(x: number, y: number) {
        this.x = x;
        this.y = y;
    }

    toString(): string {
        return "(" + this.x + ", " + this.y + ")";
    }
}

function main(): void {
    const p = new Point(3.0, 4.0);
    printIt(p);
}

main();
