# Auto-generated by a2p transpiler

from typing import Protocol

class Printable(Protocol):
    def to_string(self) -> str: ...

def print_it(item: Printable) -> None:
    print(item.to_string())

class Point:
    def __init__(self, x: float, y: float):
        self.x = x
        self.y = y

    def to_string(self) -> str:
        return "(" + str(self.x) + ", " + str(self.y) + ")"

def main():
    p = Point(x=3.0, y=4.0)
    print_it(p)

if __name__ == "__main__":
    main()
