// Auto-generated by a2ts transpiler

// Extension method for String
declare global {
    interface String {
        shout(): string;
    }
}

String.prototype.shout = function(): string {
    return this.toUpperCase() + "!";
};

function main(): void {
    console.log("hello".shout());
}

main();
