// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>
#include <ctype.h>

void string_shout(const char* s, char* out) {
    int i;
    for (i = 0; s[i]; i++) {
        out[i] = toupper((unsigned char)s[i]);
    }
    out[i] = '!';
    out[i + 1] = '\0';
}

int main(void) {
    char result[256];
    string_shout("hello", result);
    printf("%s\n", result);
    return 0;
}
