# Auto-generated by a2p transpiler

# Extension method for str
def shout(self):
    return self.upper() + "!"

# Monkey-patch the built-in str type
str.shout = shout

def main():
    print("hello".shout())

if __name__ == "__main__":
    main()
