// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

// Extension method for String
fn string_shout(s: &str) -> String {
    format!("{}!", s.to_uppercase())
}

fn main() {
    println!("{}", string_shout("hello"));
}
