// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn search_case_insensitive(query: &str, contents: &str) -> Vec<&str> {
    let mut results = Vec::new();
    let query_lower = query.to_lowercase();
    for line in contents.lines() {
        if line.to_lowercase().contains(&query_lower) {
            results.push(line);
        }
    }
    results
}

fn main() -> Result<(), String> {
    let args: Vec<String> = env::args().collect();
    let query = &args[1];
    let file_path = &args[2];
    let ignore_case = env::var("IGNORE_CASE").is_ok();

    let contents = fs::read_to_string(file_path).collect();

    if ignore_case {
        for line in search_case_insensitive(query, &contents) {
            println!("{}", line);
        }
    } else {
        for line in search(query, &contents) {
            println!("{}", line);
        }
    }
    Ok(())
}

use std::env;
use std::fs;
