// Auto-generated by a2ts transpiler

function add(a: number, b: number): number {
    return a + b;
}

function main(): void {
    let result: number = add(3, 4);
    console.log(result);
}

main();
