// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn add(a: i64, b: i64) -> i64 {
    a + b
}

fn main() {
    let mut result: i64 = add(3, 4);
    println!("{}", result);
}
