// Auto-generated by a2c transpiler

#include <stdio.h>

long long add(long long a, long long b) {
    return a + b;
}

int main(void) {
    long long result = add(3, 4);
    printf("%lld\n", result);
    return 0;
}
