// Auto-generated by a2ts transpiler

function takeOwnership(s: string): void {
    console.log(s);
}

function main(): void {
    const greeting = "Hello";
    takeOwnership(greeting.slice());  // clone
    console.log(greeting);  // OK -- we cloned it
}

main();
