// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn take_ownership(s: String) {
    println!("{}", s);
}

fn main() {
    let greeting = String::from("Hello");
    take_ownership(greeting.clone());
    println!("{}", greeting);  // OK -- we cloned it
}
