# Auto-generated by a2p transpiler

def take_ownership(s: str) -> None:
    print(s)

def main():
    greeting = "Hello"
    take_ownership(greeting[:])  # clone
    print(greeting)  # OK -- we cloned it

if __name__ == "__main__":
    main()
