// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::sync::{Arc, Mutex};
use std::thread;

struct Accumulator {
    total: i32,
}

fn main() {
    let acc = Arc::new(Mutex::new(Accumulator { total: 0 }));
    let acc1 = Arc::clone(&acc);
    let acc2 = Arc::clone(&acc);
    let acc3 = Arc::clone(&acc);

    let h1 = thread::spawn(move || {
        let mut a = acc1.lock().unwrap();
        a.total += 10;
    });
    let h2 = thread::spawn(move || {
        let mut a = acc2.lock().unwrap();
        a.total += 20;
    });
    let h3 = thread::spawn(move || {
        let mut a = acc3.lock().unwrap();
        a.total += 5;
    });

    h1.join().unwrap();
    h2.join().unwrap();
    h3.join().unwrap();

    println!("Total: {}", acc.lock().unwrap().total);
}
