// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq)]
struct User {
    active: bool,
    username: String,
    email: String,
    sign_in_count: i32,
}

fn main() {
    let user1 = User { active: true, username: "someusername123", email: "someone@example.com", sign_in_count: 1 };
    println!("email: {}", user1.email);
}
