// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct User {
    pub active: bool,
    pub username: String,
    pub email: String,
    pub sign_in_count: i64,
}

fn main() {
    let user1 = User { active: true, username: "someusername123".to_string(), email: "someone@example.com".to_string(), sign_in_count: 1 };
    println!("email: {}", user1.email);
}
