// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

enum Message {
    Connect(String),
    Disconnect(String),
    Chat(String, String),
    PrivateMsg(String, String, String),
    System(String),
}

fn client_handler(name: String, server_tx: mpsc::Sender<Message>) {
    println!("Welcome, {}! Type /quit to disconnect.", name);
    server_tx.send(Message::Connect(name.clone())).unwrap();
    // Simulated input loop
    let input = String::from("Hello everyone!");
    server_tx.send(Message::Chat(name.clone(), input)).unwrap();
    let input2 = String::from("/msg Bob Hi there");
    let parts: Vec<&str> = input2.split_whitespace().collect();
    let target = parts[1].to_string();
    let text = parts[2..].join(" ");
    server_tx.send(Message::PrivateMsg(name.clone(), target, text)).unwrap();
    server_tx.send(Message::Disconnect(name.clone())).unwrap();
    println!("Goodbye, {}!", name);
}

fn main() {
    let (tx, _rx) = mpsc::channel::<Message>();
    let tx1 = tx.clone();
    let tx2 = tx.clone();
    std::thread::spawn(move || {
        client_handler(String::from("Alice"), tx1);
    });
    std::thread::spawn(move || {
        client_handler(String::from("Bob"), tx2);
    });
}
