# Auto-generated by a2p transpiler

import threading
import queue
from dataclasses import dataclass

class MessageKind:
    Connect = "Connect"
    Disconnect = "Disconnect"
    Chat = "Chat"
    PrivateMsg = "PrivateMsg"
    System = "System"

@dataclass
class Message:
    kind: str
    field1: str = ""
    field2: str = ""
    field3: str = ""

def client_handler(name, server_q):
    print(f"Welcome, {name}! Type /quit to disconnect.")
    server_q.put(Message(kind=MessageKind.Connect, field1=name))
    # Simulated inputs
    inputs = ["Hello everyone!", "/msg Bob Hi there", "/quit"]
    for inp in inputs:
        if inp == "/quit":
            server_q.put(Message(kind=MessageKind.Disconnect, field1=name))
            print(f"Goodbye, {name}!")
            return
        elif inp.startswith("/msg"):
            parts = inp.split(" ")
            if len(parts) >= 3:
                target = parts[1]
                text = " ".join(parts[2:])
                server_q.put(Message(kind=MessageKind.PrivateMsg, field1=name, field2=target, field3=text))
            else:
                print("Usage: /msg <name> <message>")
        elif len(inp) > 0:
            server_q.put(Message(kind=MessageKind.Chat, field1=name, field2=inp))

def main():
    server_q = queue.Queue()
    t1 = threading.Thread(target=client_handler, args=("Alice", server_q))
    t2 = threading.Thread(target=client_handler, args=("Bob", server_q))
    t1.daemon = True
    t2.daemon = True
    t1.start()
    t2.start()
    t1.join(timeout=2.0)
    t2.join(timeout=2.0)

if __name__ == "__main__":
    main()
