// Auto-generated by a2ts transpiler

type Message =
    | { kind: "Connect"; field1: string }
    | { kind: "Disconnect"; field1: string }
    | { kind: "Chat"; field1: string; field2: string }
    | { kind: "PrivateMsg"; field1: string; field2: string; field3: string }
    | { kind: "System"; field1: string };

function clientHandler(name: string, sendToServer: (msg: Message) => void): void {
    console.log(`Welcome, ${name}! Type /quit to disconnect.`);
    sendToServer({ kind: "Connect", field1: name });

    const inputs = ["Hello everyone!", "/msg Bob Hi there", "/quit"];
    for (const input of inputs) {
        if (input === "/quit") {
            sendToServer({ kind: "Disconnect", field1: name });
            console.log(`Goodbye, ${name}!`);
            return;
        } else if (input.startsWith("/msg")) {
            const parts = input.split(" ");
            if (parts.length >= 3) {
                const target = parts[1];
                const text = parts.slice(2).join(" ");
                sendToServer({ kind: "PrivateMsg", field1: name, field2: target, field3: text });
            } else {
                console.log("Usage: /msg <name> <message>");
            }
        } else if (input.length > 0) {
            sendToServer({ kind: "Chat", field1: name, field2: input });
        }
    }
}

function main(): void {
    const messages: Message[] = [];
    const sendToServer = (msg: Message) => messages.push(msg);
    clientHandler("Alice", sendToServer);
    clientHandler("Bob", sendToServer);
}

main();
