// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef enum MessageKind {
    MsgKind_Connect,
    MsgKind_Disconnect,
    MsgKind_Chat,
    MsgKind_PrivateMsg,
    MsgKind_System,
} MessageKind;

typedef struct Message {
    MessageKind kind;
    char field1[64];
    char field2[256];
    char field3[256];
} Message;

void client_handler(const char* name) {
    printf("Welcome, %s! Type /quit to disconnect.\n", name);

    // Simulated input processing
    const char* inputs[] = {
        "Hello everyone!",
        "/msg Bob Hi there",
        "/quit"
    };

    for (int i = 0; i < 3; i++) {
        const char* input = inputs[i];
        if (strcmp(input, "/quit") == 0) {
            Message msg;
            msg.kind = MsgKind_Disconnect;
            strncpy(msg.field1, name, 63);
            printf("Goodbye, %s!\n", name);
            return;
        } else if (strncmp(input, "/msg", 4) == 0) {
            char buf[256];
            strncpy(buf, input, sizeof(buf) - 1);
            buf[sizeof(buf) - 1] = '\0';
            char* parts[8];
            int count = 0;
            char* tok = strtok(buf, " ");
            while (tok != NULL && count < 8) {
                parts[count++] = tok;
                tok = strtok(NULL, " ");
            }
            if (count >= 3) {
                printf("[PM] %s -> %s: %s\n", name, parts[1], parts[2]);
            } else {
                printf("Usage: /msg <name> <message>\n");
            }
        } else if (strlen(input) > 0) {
            printf("%s: %s\n", name, input);
        }
    }
}

int main(void) {
    // Simulate two client handlers
    printf("=== Alice ===\n");
    client_handler("Alice");
    printf("=== Bob ===\n");
    client_handler("Bob");
    return 0;
}
