// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Config {
    pub verbose: bool,
    pub level: i64,
}

impl Config {
    fn new(verbose: bool, level: i64) -> Config {
        Config { verbose: verbose, level: level }
    }
    fn describe(&self) -> String {
        if self.verbose {
            format!("Config(level={})", self.level)
        } else {
            "Config"
        }

    }
}

fn main() {
    let config = Config::new(true, 3);
    println!("{}", config.describe());
}
