// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq)]
struct Config {
    verbose: bool,
    level: i32,
}

impl Config {
    fn new(&self, verbose: bool, level: i32) -> Config {
        Config { verbose: verbose, level: level };
    }
    fn describe(&self) -> String {
        if self.verbose {
            format!("Config(level={})", self.level)
        } else {
            "Config"
        }

    }
}

fn main() {
    let config = Config::new(true, 3);
    println!("{}", config.describe());
}
