# Auto-generated by a2p transpiler

from enum import Enum

class Color(Enum):
    RED = 0
    GREEN = 1
    BLUE = 2

def color_name(c):
    if c == Color.RED:
        return "red"
    elif c == Color.GREEN:
        return "green"
    elif c == Color.BLUE:
        return "blue"

def main():
    print(color_name(Color.RED))
    print(color_name(Color.GREEN))

if __name__ == "__main__":
    main()
