// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Color {
    Red = 0,
    Green = 1,
    Blue = 2,
}

fn color_name(c: Color) -> &'static str {
    match c {
        Color::Red => "red",
        Color::Green => "green",
        Color::Blue => "blue",
    }
}

fn main() {
    println!("{}", color_name(Color::Red));
    println!("{}", color_name(Color::Green));
}
