// Auto-generated by a2ts transpiler

enum Color {
    Red = 0,
    Green = 1,
    Blue = 2,
}

function color_name(c: Color): string {
    switch (c) {
        case Color.Red: return "red";
        case Color.Green: return "green";
        case Color.Blue: return "blue";
    }
}

function main(): void {
    console.log(color_name(Color.Red));
    console.log(color_name(Color.Green));
}

main();
