// Auto-generated by a2c transpiler

#include <stdio.h>

typedef enum {
    Color_Red = 0,
    Color_Green = 1,
    Color_Blue = 2,
} Color;

const char* color_name(Color c) {
    switch (c) {
        case Color_Red: return "red";
        case Color_Green: return "green";
        case Color_Blue: return "blue";
        default: return "unknown";
    }
}

int main(void) {
    printf("%s\n", color_name(Color_Red));
    printf("%s\n", color_name(Color_Green));
    return 0;
}
