// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    char city[256];
} Address;

typedef struct {
    Address address;
    int _address_some;
} User;

int main(void) {
    User alice;
    strcpy(alice.address.city, "Shanghai");
    alice._address_some = 1;

    User bob;
    bob._address_some = 0;

    if (alice._address_some) {
        printf("%s\n", alice.address.city);
    }
    if (bob._address_some) {
        printf("%s\n", bob.address.city);
    } else {
        printf("None\n");
    }
    return 0;
}
