// Auto-generated by a2ts transpiler

class Address {
    city: string;

    constructor(city: string) {
        this.city = city;
    }
}

class User {
    address: Address | null;

    constructor(address: Address | null) {
        this.address = address;
    }
}

function main(): void {
    const alice = new User(new Address("Shanghai"));
    const bob = new User(null);
    if (alice.address !== null) {
        console.log(alice.address.city);
    }
    if (bob.address !== null) {
        console.log(bob.address.city);
    } else {
        console.log(null);
    }
}

main();
