# Auto-generated by a2p transpiler

from dataclasses import dataclass
from typing import Optional

@dataclass
class Address:
    city: str

@dataclass
class User:
    address: Optional[Address]

def main():
    alice = User(address=Address(city="Shanghai"))
    bob = User(address=None)
    if alice.address is not None:
        print(alice.address.city)
    if bob.address is not None:
        print(bob.address.city)
    else:
        print(None)

if __name__ == "__main__":
    main()
