// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Address {
    city: String,
}

struct User {
    address: Option<Address>,
}

fn main() {
    let mut alice = User {
        address: Some(Address {
            city: String::from("Shanghai"),
        }),
    };
    let mut bob = User { address: None };
    if let Some(ref addr) = alice.address {
        println!("{}", addr.city);
    }
    if let Some(ref addr) = bob.address {
        println!("{}", addr.city);
    } else {
        println!("None");
    }
}
