// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    trpl::block_on(async {
        let vals = vec![1, 2, 3, 4, 5];
        let mut stream = trpl::stream_from_iter(vals);

        while let Some(value) = stream.next().await {
            println!("The value was: {value}");
        }
    })
}
