// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn add(a: i32, b: i32) -> i32 {
    a + b
}

fn five() -> i32 {
    5
}

fn main() {
    let result = add(5, 3);
    println!("5 + 3 = {}", result);

    let x = five();
    println!("five() = {}", x);
}
