// Auto-generated by a2r transpiler

fn add(a: i64, b: i64) -> i64 {
    a + b
}

fn five() -> i64 {
    5
}

fn main() {
    let result = add(5, 3);
    println!("5 + 3 = {}", result);

    let x = five();
    println!("five() = {}", x);
}
