// Auto-generated by a2ts transpiler

type Result<T> = { ok: true; value: T } | { ok: false; error: string };

function divide(a: number, b: number): Result<number> {
    if (b === 0.0) {
        return { ok: false, error: "division by zero" };
    }
    return { ok: true, value: a / b };
}

function testDivideByZero(): void {
    const result = divide(10.0, 0.0);
    if (result.ok) {
        throw new Error("assertion failed: expected error");
    }
}

function testDivideSuccess(): void {
    const result = divide(10.0, 2.0);
    if (result.ok) {
        if (result.value !== 5.0) {
            throw new Error(`assertion failed: value === 5.0, got ${result.value}`);
        }
    } else {
        throw new Error("assertion failed: expected ok");
    }
}
