# Auto-generated by a2p transpiler

class Result:
    def __init__(self, ok=False, value=None, error=None):
        self.ok = ok
        self.value = value
        self.error = error

def divide(a, b):
    if b == 0.0:
        return Result(ok=False, error="division by zero")
    return Result(ok=True, value=a / b)

def test_divide_by_zero():
    result = divide(10.0, 0.0)
    if result.ok:
        assert False
    else:
        assert True

def test_divide_success():
    result = divide(10.0, 2.0)
    if result.ok:
        assert result.value == 5.0
    else:
        assert False
