// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn divide(a: f64, b: f64) -> Result<f64, String> {
    if b == 0.0 { Err(String::from("division by zero")) } else { Ok(a / b) }
}

#[test]
fn test_divide_by_zero() {
    let mut result = divide(10.0, 0.0);
    match result {
        Ok(_) => assert!(false),
        Err(_e) => assert!(true),
    }
}

#[test]
fn test_divide_success() {
    let mut result = divide(10.0, 2.0);
    match result {
        Ok(v) => assert_eq!(v, 5.0),
        Err(_) => assert!(false),
    }
}
