// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct {
    bool is_ok;
    union {
        double ok_value;
        const char* err_value;
    };
} ResultFloat;

ResultFloat divide(double a, double b) {
    ResultFloat r;
    if (b == 0.0) {
        r.is_ok = false;
        r.err_value = "division by zero";
    } else {
        r.is_ok = true;
        r.ok_value = a / b;
    }
    return r;
}

void test_divide_by_zero() {
    ResultFloat result = divide(10.0, 0.0);
    if (result.is_ok) {
        fprintf(stderr, "assertion failed: expected error\n");
        __builtin_trap();
    }
}

void test_divide_success() {
    ResultFloat result = divide(10.0, 2.0);
    if (result.is_ok) {
        if (result.ok_value != 5.0) {
            fprintf(stderr, "assertion failed: value == 5.0\n");
            __builtin_trap();
        }
    } else {
        fprintf(stderr, "assertion failed: expected ok\n");
        __builtin_trap();
    }
}
