# Auto-generated by a2p transpiler

import random

def main():
    secret = random.randint(1, 100)
    attempts = 0
    print("Guess the number between 1 and 100!")
    while True:
        print("Please input your guess.")
        guess_str = input()
        try:
            guess = int(guess_str)
        except ValueError:
            print("Please enter a valid number!")
            continue
        attempts = attempts + 1
        if guess == secret:
            print("You win! You got it in " + str(attempts) + " tries!")
            break
        if guess < secret:
            print("Too small!")
        else:
            print("Too big!")

if __name__ == "__main__":
    main()
