// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

int main(void) {
    srand(time(NULL));
    long long secret = (rand() % 100) + 1;
    long long attempts = 0;
    printf("Guess the number between 1 and 100!\n");
    while (1) {
        printf("Please input your guess.\n");
        char guess_str[256];
        fgets(guess_str, 256, stdin);
        guess_str[strcspn(guess_str, "\n")] = '\0';
        char* endptr;
        long long guess = strtoll(guess_str, &endptr, 10);
        if (*endptr != '\0') {
            printf("Please enter a valid number!\n");
            continue;
        }
        attempts = attempts + 1;
        if (guess == secret) {
            printf("You win! You got it in %lld tries!\n", attempts);
            break;
        }
        if (guess < secret) {
            printf("Too small!\n");
        } else {
            printf("Too big!\n");
        }
    }
    return 0;
}
