// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use rand::Rng;

fn main() {
    let mut secret: i64 = rand::thread_rng().gen_range(1..=100);
    let mut attempts: i64 = 0;
    println!("Guess the number between 1 and 100!");
    loop {
        println!("Please input your guess.");
        let mut guess_str: String = read_line();
        let guess: Option<i64> = guess_str.trim().parse().ok();
        if guess.is_none() {
            println!("Please enter a valid number!");
            continue;
        }
        let mut guess: i64 = guess.unwrap();
        attempts = attempts + 1;
        if guess == secret {
            println!("You win! You got it in {} tries!", attempts);
            break;
        }
        if guess < secret {
            println!("Too small!");
        } else {
            println!("Too big!");
        }
    }
}
