// Auto-generated by a2ts transpiler

import * as readline from 'readline';

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

function main(): void {
    let secret: number = Math.floor(Math.random() * 100) + 1;
    let attempts: number = 0;
    console.log("Guess the number between 1 and 100!");
    const loop = (): void => {
        console.log("Please input your guess.");
        rl.question("", (guess_str: string) => {
            const guess: number = parseInt(guess_str, 10);
            if (isNaN(guess)) {
                console.log("Please enter a valid number!");
                loop();
                return;
            }
            attempts = attempts + 1;
            if (guess === secret) {
                console.log("You win! You got it in " + attempts + " tries!");
                rl.close();
            } else if (guess < secret) {
                console.log("Too small!");
                loop();
            } else {
                console.log("Too big!");
                loop();
            }
        });
    };
    loop();
}

main();
