// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn greet(name: String) -> String {
    format!("Hello, {}!", name)
}

#[test]
fn greeting_contains_name() {
    let result = greet(String::from("Carol"));
    assert!(
        result.contains("Carol"),
        "Greeting did not contain name, value was '{}'",
        result
    );
}
