// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum CellValue {
    Int(i32),
    Text(String),
    Float(f64),
}


fn main() {
    let mut row = List::new();
    row.push(CellValue::Int(1));
    row.push(CellValue::Text("hello"));
    row.push(CellValue::Float(3.14));
    println!("Row length: {}", row.len());
}
