// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq)]
enum CellValue {
    Int(i64),
    Text(String),
    Float(f64),
}


fn main() {
    let mut row = Vec::new();
    row.push(CellValue::Int(1));
    row.push(CellValue::Text("hello".to_string()));
    row.push(CellValue::Float(3.14));
    println!("Row length: {}", (row.len() as i64));
}
