// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

int main(void) {
    int numbers[] = {1, 2, 3, 4, 5};
    int len = 5;
    int* doubled = (int*)malloc(len * sizeof(int));
    for (int i = 0; i < len; i++) {
        doubled[i] = numbers[i] * 2;
    }
    for (int i = 0; i < len; i++) {
        printf("%d\n", doubled[i]);
    }
    free(doubled);
    return 0;
}
