// Auto-generated by a2ts transpiler

function main(): void {
    const numbers = [1, 2, 3, 4, 5];
    const doubled = numbers.map((x: number) => x * 2);
    for (const n of doubled) {
        console.log(n);
    }
}

main();
