// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    long long count = 0;
    while (count < 5) {
        printf("%lld\n", count);
        count = count + 1;
    }
    return 0;
}
