// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut count: i64 = 0;
    while count < 5 {
        println!("{}", count);
        count = count + 1;
    }
}
