// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

typedef struct {
    double radius;
} ShapeCircle;

typedef struct {
    double width;
    double height;
} ShapeRect;

typedef enum {
    ShapeTag_Circle = 0,
    ShapeTag_Rect = 1,
} ShapeTag;

typedef struct {
    ShapeTag tag;
    union {
        ShapeCircle circle;
        ShapeRect rect;
    };
} Shape;

void shape_print(const Shape* s) {
    switch (s->tag) {
        case ShapeTag_Circle:
            printf("Circle(%f)\n", s->circle.radius);
            break;
        case ShapeTag_Rect:
            printf("Rect(%f, %f)\n", s->rect.width, s->rect.height);
            break;
    }
}

int main(void) {
    Shape c = { .tag = ShapeTag_Circle, .circle = { .radius = 5.0 } };
    Shape r = { .tag = ShapeTag_Rect, .rect = { .width = 3.0, .height = 4.0 } };
    shape_print(&c);
    shape_print(&r);
    return 0;
}
