// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Shape {
    Circle(f64),
    Rect(f64, f64),
}

impl std::fmt::Display for Shape {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Shape::Circle(r) => write!(f, "Circle({})", r),
            Shape::Rect(w, h) => write!(f, "Rect({}, {})", w, h),
        }
    }
}

fn main() {
    let mut c = Shape::Circle(5.0);
    let mut r = Shape::Rect(3.0, 4.0);
    println!("{}", c);
    println!("{}", r);
}
