# Auto-generated by a2p transpiler

from dataclasses import dataclass
from typing import Union

@dataclass
class Circle:
    radius: float

@dataclass
class Rect:
    width: float
    height: float

Shape = Union[Circle, Rect]

def main():
    c = Circle(radius=5.0)
    r = Rect(width=3.0, height=4.0)
    print(c)
    print(r)

if __name__ == "__main__":
    main()
