// Auto-generated by a2ts transpiler

class Circle {
    radius: number;
    constructor(radius: number) {
        this.radius = radius;
    }
    toString(): string {
        return `Circle(${this.radius})`;
    }
}

class Rect {
    width: number;
    height: number;
    constructor(width: number, height: number) {
        this.width = width;
        this.height = height;
    }
    toString(): string {
        return `Rect(${this.width}, ${this.height})`;
    }
}

type Shape = Circle | Rect;

function main(): void {
    let c: Shape = new Circle(5.0);
    let r: Shape = new Rect(3.0, 4.0);
    console.log(c.toString());
    console.log(r.toString());
}

main();
