// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct {
    double total;
} Calculator;

Calculator Calculator_new() {
    Calculator c;
    c.total = 0.0;
    return c;
}

void Calculator_add(Calculator* self, double value) {
    self->total = self->total + value;
}

void Calculator_clear(Calculator* self) {
    self->total = 0.0;
}

void test_calculator_workflow() {
    Calculator calc = Calculator_new();
    Calculator_add(&calc, 10.0);
    Calculator_add(&calc, 20.0);
    if (calc.total != 30.0) {
        fprintf(stderr, "assertion failed: calc.total == 30.0\n");
        __builtin_trap();
    }
    Calculator_clear(&calc);
    if (calc.total != 0.0) {
        fprintf(stderr, "assertion failed: calc.total == 0.0\n");
        __builtin_trap();
    }
}
