// Auto-generated by a2ts transpiler

class Calculator {
    total: number;

    static new(): Calculator {
        return new Calculator();
    }

    constructor(total: number = 0.0) {
        this.total = total;
    }

    add(value: number): void {
        this.total = this.total + value;
    }

    clear(): void {
        this.total = 0.0;
    }
}

function testCalculatorWorkflow(): void {
    const calc = Calculator.new();
    calc.add(10.0);
    calc.add(20.0);
    if (calc.total !== 30.0) {
        throw new Error(`assertion failed: calc.total === 30.0, got ${calc.total}`);
    }
    calc.clear();
    if (calc.total !== 0.0) {
        throw new Error(`assertion failed: calc.total === 0.0, got ${calc.total}`);
    }
}
