# Auto-generated by a2p transpiler

class Calculator:
    def __init__(self, total=0.0):
        self.total = total

    @staticmethod
    def new():
        return Calculator(total=0.0)

    def add(self, value):
        self.total = self.total + value

    def clear(self):
        self.total = 0.0

def test_calculator_workflow():
    calc = Calculator.new()
    calc.add(10.0)
    calc.add(20.0)
    assert calc.total == 30.0
    calc.clear()
    assert calc.total == 0.0
