// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Calculator {
    total: f64,
}

impl Calculator {
    fn new() -> Calculator {
        Calculator { total: 0.0 }
    }
    fn add(&mut self, value: f64) {
        self.total = self.total + value;
    }
    fn clear(&mut self) {
        self.total = 0.0;
    }
}

#[test]
fn test_calculator_workflow() {
    let mut calc = Calculator::new();
    calc.add(10.0);
    calc.add(20.0);
    assert_eq!(calc.total, 30.0);
    calc.clear();
    assert_eq!(calc.total, 0.0);
}
