// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Value {
    Int(i64),
    Float(f64),
    Str(String),
}

fn describe(v: Value) -> String {
    match v {
        Value::Int(n) if n > 0 => String::from("positive integer"),
        Value::Int(n) if n < 0 => String::from("negative integer"),
        Value::Int(_) => String::from("zero"),
        Value::Float(f) => format!("float: {}", f),
        Value::Str(s) => format!("string: {}", s),
    }
}

fn main() {
    println!("{}", describe(Value::Int(42)));
    println!("{}", describe(Value::Int(-1)));
    println!("{}", describe(Value::Int(0)));
    println!("{}", describe(Value::Float(3.14)));
    println!("{}", describe(Value::Str(String::from("hello"))));
}
