# Auto-generated by a2p transpiler

from dataclasses import dataclass
from typing import Union

@dataclass
class ValueInt:
    n: int

@dataclass
class ValueFloat:
    f: float

@dataclass
class ValueStr:
    s: str

Value = Union[ValueInt, ValueFloat, ValueStr]

def describe(v):
    if isinstance(v, ValueInt):
        if v.n > 0:
            return "positive integer"
        elif v.n < 0:
            return "negative integer"
        else:
            return "zero"
    elif isinstance(v, ValueFloat):
        return f"float: {v.f}"
    elif isinstance(v, ValueStr):
        return f"string: {v.s}"

def main():
    print(describe(ValueInt(n=42)))
    print(describe(ValueInt(n=-1)))
    print(describe(ValueInt(n=0)))
    print(describe(ValueFloat(f=3.14)))
    print(describe(ValueStr(s="hello")))

if __name__ == "__main__":
    main()
