// Auto-generated by a2ts transpiler

class ValueInt {
    n: number;
    constructor(n: number) {
        this.n = n;
    }
}

class ValueFloat {
    f: number;
    constructor(f: number) {
        this.f = f;
    }
}

class ValueStr {
    s: string;
    constructor(s: string) {
        this.s = s;
    }
}

type Value = ValueInt | ValueFloat | ValueStr;

function describe(v: Value): string {
    if (v instanceof ValueInt) {
        if (v.n > 0) return "positive integer";
        else if (v.n < 0) return "negative integer";
        else return "zero";
    } else if (v instanceof ValueFloat) {
        return `float: ${v.f}`;
    } else if (v instanceof ValueStr) {
        return `string: ${v.s}`;
    }
    return "unknown";
}

function main(): void {
    console.log(describe(new ValueInt(42)));
    console.log(describe(new ValueInt(-1)));
    console.log(describe(new ValueInt(0)));
    console.log(describe(new ValueFloat(3.14)));
    console.log(describe(new ValueStr("hello")));
}

main();
