// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    long long n;
} ValueInt;

typedef struct {
    double f;
} ValueFloat;

typedef struct {
    char s[256];
} ValueStr;

typedef enum {
    ValueTag_Int = 0,
    ValueTag_Float = 1,
    ValueTag_Str = 2,
} ValueTag;

typedef struct {
    ValueTag tag;
    union {
        ValueInt int_val;
        ValueFloat float_val;
        ValueStr str_val;
    };
} Value;

const char* describe(Value v) {
    switch (v.tag) {
        case ValueTag_Int:
            if (v.int_val.n > 0) return "positive integer";
            else if (v.int_val.n < 0) return "negative integer";
            else return "zero";
        case ValueTag_Float: {
            static char buf[512];
            snprintf(buf, sizeof(buf), "float: %f", v.float_val.f);
            return buf;
        }
        case ValueTag_Str: {
            static char buf[512];
            snprintf(buf, sizeof(buf), "string: %s", v.str_val.s);
            return buf;
        }
        default: return "unknown";
    }
}

int main(void) {
    Value v1 = { .tag = ValueTag_Int, .int_val = { .n = 42 } };
    printf("%s\n", describe(v1));
    Value v2 = { .tag = ValueTag_Int, .int_val = { .n = -1 } };
    printf("%s\n", describe(v2));
    Value v3 = { .tag = ValueTag_Int, .int_val = { .n = 0 } };
    printf("%s\n", describe(v3));
    Value v4 = { .tag = ValueTag_Float, .float_val = { .f = 3.14 } };
    printf("%s\n", describe(v4));
    Value v5 = { .tag = ValueTag_Str };
    strcpy(v5.str_val.s, "hello");
    printf("%s\n", describe(v5));
    return 0;
}
