// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

struct KVStore {
    data: HashMap<String, String>,
}

fn main() {
    let store = Arc::new(Mutex::new(KVStore {
        data: HashMap::new(),
    }));

    {
        let mut s = store.lock().unwrap();
        s.data.insert("name".to_string(), "Auto".to_string());
        s.data.insert("version".to_string(), "0.1".to_string());
    }

    {
        let s = store.lock().unwrap();
        println!("name = {:?}", s.data.get("name"));
        println!("count = {}", s.data.len());
    }

    {
        let mut s = store.lock().unwrap();
        s.data.remove("version");
    }

    println!("count = {}", store.lock().unwrap().data.len());
}
