// Auto-generated by a2ts transpiler

class Point {
    x: number;
    y: number;

    constructor(x: number, y: number) {
        this.x = x;
        this.y = y;
    }

    distance(): number {
        return Math.sqrt(this.x * this.x + this.y * this.y);
    }

    translate(dx: number, dy: number): Point {
        return new Point(this.x + dx, this.y + dy);
    }
}

function main(): void {
    const p: Point = new Point(3.0, 4.0);
    console.log(p.distance());
    const p2: Point = p.translate(1.0, 2.0);
    console.log(p2.x);
}

main();
