// Auto-generated by a2c transpiler

#include <stdio.h>
#include <math.h>

typedef struct {
    double x;
    double y;
} Point;

double point_distance(Point* self) {
    return sqrt(self->x * self->x + self->y * self->y);
}

Point point_translate(Point* self, double dx, double dy) {
    Point result = {self->x + dx, self->y + dy};
    return result;
}

int main(void) {
    Point p = {3.0, 4.0};
    printf("%f\n", point_distance(&p));
    Point p2 = point_translate(&p, 1.0, 2.0);
    printf("%f\n", p2.x);
    return 0;
}
