// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Point {
    x: f64,
    y: f64,
}

impl Point {
    fn distance(&self) -> f64 {
        (self.x * self.x + self.y * self.y).sqrt()
    }
    fn translate(&self, dx: f64, dy: f64) -> Point {
        Point { x: self.x + dx, y: self.y + dy }
    }
}

fn main() {
    let mut p = Point { x: 3.0, y: 4.0 };
    println!("{}", p.distance());
    let mut p2 = p.translate(1.0, 2.0);
    println!("{}", p2.x);
}
