# Auto-generated by a2p transpiler

from dataclasses import dataclass
import math

@dataclass
class Point:
    x: float
    y: float

    def distance(self) -> float:
        return math.sqrt(self.x * self.x + self.y * self.y)

    def translate(self, dx: float, dy: float):
        return Point(x=self.x + dx, y=self.y + dy)

def main():
    p = Point(x=3.0, y=4.0)
    print(p.distance())
    p2 = p.translate(1.0, 2.0)
    print(p2.x)

if __name__ == "__main__":
    main()
