// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Engine {
    horsepower: i32,
}

impl Engine {
    fn start(&self) {
        println!("Engine started!");
    }

    fn stop(&self) {
        println!("Engine stopped!");
    }
}

struct Car {
    engine: Engine,
    make: String,
    model: String,
}

impl Car {
    fn start(&self) {
        self.engine.start();    // Manual delegation
    }

    fn stop(&self) {
        self.engine.stop();     // Manual delegation
    }
}

fn main() {
    let car = Car {
        engine: Engine { horsepower: 200 },
        make: String::from("Toyota"),
        model: String::from("Camry"),
    };
    car.start();
    car.stop();
}
