// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Pair {
    x: i64,
    y: i64,
}

fn swap(p: Pair) -> Pair {
    Pair { x: p.y, y: p.x }
}

fn main() {
    let mut p = Pair { x: 1, y: 2 };
    let mut p2 = swap(p);
    println!("{}", p2.x);
    println!("{}", p2.y);
}
