// Auto-generated by a2ts transpiler

class Pair {
    x: number;
    y: number;

    constructor(x: number, y: number) {
        this.x = x;
        this.y = y;
    }
}

function swap(p: Pair): Pair {
    return new Pair(p.y, p.x);
}

function main(): void {
    let p: Pair = new Pair(1, 2);
    let p2: Pair = swap(p);
    console.log(p2.x);
    console.log(p2.y);
}

main();
