# Auto-generated by a2p transpiler

from dataclasses import dataclass

@dataclass
class Pair:
    x: int
    y: int

def swap(p):
    return Pair(x=p.y, y=p.x)

def main():
    p = Pair(x=1, y=2)
    p2 = swap(p)
    print(p2.x)
    print(p2.y)

if __name__ == "__main__":
    main()
