// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct {
    long long x;
    long long y;
} Pair;

Pair swap(Pair p) {
    Pair result;
    result.x = p.y;
    result.y = p.x;
    return result;
}

int main(void) {
    Pair p = { .x = 1, .y = 2 };
    Pair p2 = swap(p);
    printf("%lld\n", p2.x);
    printf("%lld\n", p2.y);
    return 0;
}
