// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;
use std::collections::HashMap;

enum Message {
    Connect(String),
    Disconnect(String),
    Chat(String, String),
    PrivateMsg(String, String, String),
    System(String),
    JoinRoom(String, String),
    LeaveRoom(String, String),
    RoomMsg(String, String, String),
}

fn server(rx: mpsc::Receiver<Message>) {
    let mut clients: HashMap<String, i64> = HashMap::new();
    let mut rooms: HashMap<String, Vec<String>> = HashMap::new();
    rooms.insert(String::from("general"), Vec::new());
    rooms.insert(String::from("random"), Vec::new());
    for msg in rx {
        match msg {
            Message::Connect(name) => {
                clients.insert(name.clone(), 1);
                rooms.get_mut("general").unwrap().push(name.clone());
                println!("[SYS] {} joined. Online: {}", name, clients.len());
            }
            Message::Disconnect(name) => {
                clients.remove(&name);
                for (_room_name, members) in rooms.iter_mut() {
                    members.retain(|m| m != &name);
                }
                println!("[SYS] {} left. Online: {}", name, clients.len());
            }
            Message::JoinRoom(name, room_name) => {
                if let Some(members) = rooms.get_mut(&room_name) {
                    if !members.contains(&name) {
                        members.push(name.clone());
                        println!("[SYS] {} joined #{}", name, room_name);
                    }
                } else {
                    println!("[SYS] Room #{} does not exist", room_name);
                }
            }
            Message::LeaveRoom(name, room_name) => {
                if let Some(members) = rooms.get_mut(&room_name) {
                    members.retain(|m| m != &name);
                }
                println!("[SYS] {} left #{}", name, room_name);
            }
            Message::RoomMsg(room_name, from, text) => {
                let members = rooms.get(&room_name).unwrap();
                println!("[#{}] {}: {}", room_name, from, text);
                println!("  (delivered to {} members)", members.len());
            }
            Message::Chat(from, text) => {
                println!("{}: {}", from, text);
            }
            Message::PrivateMsg(from, to, text) => {
                println!("[PM] {} -> {}: {}", from, to, text);
            }
            Message::System(text) => {
                println!("[SYS] {}", text);
            }
        }
    }
}

fn main() {
    let (tx, rx) = mpsc::channel::<Message>();
    std::thread::spawn(move || {
        server(rx);
    });
    tx.send(Message::Connect(String::from("Alice"))).unwrap();
    tx.send(Message::Connect(String::from("Bob"))).unwrap();
    tx.send(Message::JoinRoom(String::from("Alice"), String::from("random"))).unwrap();
    tx.send(Message::JoinRoom(String::from("Bob"), String::from("random"))).unwrap();
    tx.send(Message::RoomMsg(String::from("random"), String::from("Alice"), String::from("Anyone here?"))).unwrap();
    tx.send(Message::RoomMsg(String::from("random"), String::from("Bob"), String::from("Yes!"))).unwrap();
    tx.send(Message::LeaveRoom(String::from("Alice"), String::from("random"))).unwrap();
}
