// Auto-generated by a2ts transpiler

type Message =
    | { kind: "Connect"; field1: string }
    | { kind: "Disconnect"; field1: string }
    | { kind: "Chat"; field1: string; field2: string }
    | { kind: "PrivateMsg"; field1: string; field2: string; field3: string }
    | { kind: "System"; field1: string }
    | { kind: "JoinRoom"; field1: string; field2: string }
    | { kind: "LeaveRoom"; field1: string; field2: string }
    | { kind: "RoomMsg"; field1: string; field2: string; field3: string };

function server(messages: Message[]): void {
    const clients = new Map<string, number>();
    const rooms = new Map<string, string[]>();
    rooms.set("general", []);
    rooms.set("random", []);

    for (const msg of messages) {
        switch (msg.kind) {
            case "Connect": {
                clients.set(msg.field1, 1);
                rooms.get("general")!.push(msg.field1);
                console.log(`[SYS] ${msg.field1} joined. Online: ${clients.size}`);
                break;
            }
            case "Disconnect": {
                clients.delete(msg.field1);
                for (const [, members] of rooms) {
                    const idx = members.indexOf(msg.field1);
                    if (idx >= 0) members.splice(idx, 1);
                }
                console.log(`[SYS] ${msg.field1} left. Online: ${clients.size}`);
                break;
            }
            case "JoinRoom": {
                const members = rooms.get(msg.field2);
                if (members) {
                    if (!members.includes(msg.field1)) {
                        members.push(msg.field1);
                        console.log(`[SYS] ${msg.field1} joined #${msg.field2}`);
                    }
                } else {
                    console.log(`[SYS] Room #${msg.field2} does not exist`);
                }
                break;
            }
            case "LeaveRoom": {
                const members = rooms.get(msg.field2);
                if (members) {
                    const idx = members.indexOf(msg.field1);
                    if (idx >= 0) members.splice(idx, 1);
                }
                console.log(`[SYS] ${msg.field1} left #${msg.field2}`);
                break;
            }
            case "RoomMsg": {
                const members = rooms.get(msg.field1) || [];
                console.log(`[#${msg.field1}] ${msg.field2}: ${msg.field3}`);
                console.log(`  (delivered to ${members.length} members)`);
                break;
            }
            case "Chat":
                console.log(`${msg.field1}: ${msg.field2}`);
                break;
            case "PrivateMsg":
                console.log(`[PM] ${msg.field1} -> ${msg.field2}: ${msg.field3}`);
                break;
            case "System":
                console.log(`[SYS] ${msg.field1}`);
                break;
        }
    }
}

function main(): void {
    const messages: Message[] = [
        { kind: "Connect", field1: "Alice" },
        { kind: "Connect", field1: "Bob" },
        { kind: "JoinRoom", field1: "Alice", field2: "random" },
        { kind: "JoinRoom", field1: "Bob", field2: "random" },
        { kind: "RoomMsg", field1: "random", field2: "Alice", field3: "Anyone here?" },
        { kind: "RoomMsg", field1: "random", field2: "Bob", field3: "Yes!" },
        { kind: "LeaveRoom", field1: "Alice", field2: "random" },
    ];
    server(messages);
}

main();
