# Auto-generated by a2p transpiler

import threading
import queue
from dataclasses import dataclass

class MessageKind:
    Connect = "Connect"
    Disconnect = "Disconnect"
    Chat = "Chat"
    PrivateMsg = "PrivateMsg"
    System = "System"
    JoinRoom = "JoinRoom"
    LeaveRoom = "LeaveRoom"
    RoomMsg = "RoomMsg"

@dataclass
class Message:
    kind: str
    field1: str = ""
    field2: str = ""
    field3: str = ""

def server(q):
    clients = {}
    rooms = {"general": [], "random": []}
    while True:
        try:
            msg = q.get(timeout=1.0)
            if msg.kind == MessageKind.Connect:
                name = msg.field1
                clients[name] = 1
                rooms["general"].append(name)
                print(f"[SYS] {name} joined. Online: {len(clients)}")
            elif msg.kind == MessageKind.Disconnect:
                name = msg.field1
                clients.pop(name, None)
                for members in rooms.values():
                    if name in members:
                        members.remove(name)
                print(f"[SYS] {name} left. Online: {len(clients)}")
            elif msg.kind == MessageKind.JoinRoom:
                name, room_name = msg.field1, msg.field2
                if room_name in rooms:
                    if name not in rooms[room_name]:
                        rooms[room_name].append(name)
                        print(f"[SYS] {name} joined #{room_name}")
                else:
                    print(f"[SYS] Room #{room_name} does not exist")
            elif msg.kind == MessageKind.LeaveRoom:
                name, room_name = msg.field1, msg.field2
                if name in rooms.get(room_name, []):
                    rooms[room_name].remove(name)
                print(f"[SYS] {name} left #{room_name}")
            elif msg.kind == MessageKind.RoomMsg:
                room_name, from_, text = msg.field1, msg.field2, msg.field3
                members = rooms.get(room_name, [])
                print(f"[#{room_name}] {from_}: {text}")
                print(f"  (delivered to {len(members)} members)")
            elif msg.kind == MessageKind.Chat:
                print(f"{msg.field1}: {msg.field2}")
            elif msg.kind == MessageKind.PrivateMsg:
                print(f"[PM] {msg.field1} -> {msg.field2}: {msg.field3}")
            elif msg.kind == MessageKind.System:
                print(f"[SYS] {msg.field1}")
        except queue.Empty:
            break

def main():
    q = queue.Queue()
    t = threading.Thread(target=server, args=(q,))
    t.daemon = True
    t.start()
    q.put(Message(kind=MessageKind.Connect, field1="Alice"))
    q.put(Message(kind=MessageKind.Connect, field1="Bob"))
    q.put(Message(kind=MessageKind.JoinRoom, field1="Alice", field2="random"))
    q.put(Message(kind=MessageKind.JoinRoom, field1="Bob", field2="random"))
    q.put(Message(kind=MessageKind.RoomMsg, field1="random", field2="Alice", field3="Anyone here?"))
    q.put(Message(kind=MessageKind.RoomMsg, field1="random", field2="Bob", field3="Yes!"))
    q.put(Message(kind=MessageKind.LeaveRoom, field1="Alice", field2="random"))
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
