// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

#define MAX_CLIENTS 64
#define MAX_ROOM_MEMBERS 64
#define MAX_ROOMS 8
#define MAX_NAME 64
#define MAX_FIELD 256

typedef enum MessageKind {
    MsgKind_Connect,
    MsgKind_Disconnect,
    MsgKind_Chat,
    MsgKind_PrivateMsg,
    MsgKind_System,
    MsgKind_JoinRoom,
    MsgKind_LeaveRoom,
    MsgKind_RoomMsg,
} MessageKind;

typedef struct Message {
    MessageKind kind;
    char field1[MAX_FIELD];
    char field2[MAX_FIELD];
    char field3[MAX_FIELD];
} Message;

typedef struct {
    char name[MAX_NAME];
    char members[MAX_ROOM_MEMBERS][MAX_NAME];
    int member_count;
} Room;

Room rooms[MAX_ROOMS];
int room_count = 0;
int client_count = 0;

Room* find_room(const char* name) {
    for (int i = 0; i < room_count; i++) {
        if (strcmp(rooms[i].name, name) == 0) return &rooms[i];
    }
    return NULL;
}

void add_room(const char* name) {
    strncpy(rooms[room_count].name, name, MAX_NAME - 1);
    rooms[room_count].member_count = 0;
    room_count++;
}

void server_handle(Message* msg) {
    switch (msg->kind) {
        case MsgKind_Connect: {
            client_count++;
            Room* general = find_room("general");
            if (general) {
                strncpy(general->members[general->member_count], msg->field1, MAX_NAME - 1);
                general->member_count++;
            }
            printf("[SYS] %s joined. Online: %d\n", msg->field1, client_count);
            break;
        }
        case MsgKind_Disconnect: {
            client_count--;
            for (int i = 0; i < room_count; i++) {
                for (int j = rooms[i].member_count - 1; j >= 0; j--) {
                    if (strcmp(rooms[i].members[j], msg->field1) == 0) {
                        for (int k = j; k < rooms[i].member_count - 1; k++) {
                            strncpy(rooms[i].members[k], rooms[i].members[k + 1], MAX_NAME - 1);
                        }
                        rooms[i].member_count--;
                        break;
                    }
                }
            }
            printf("[SYS] %s left. Online: %d\n", msg->field1, client_count);
            break;
        }
        case MsgKind_JoinRoom: {
            Room* room = find_room(msg->field2);
            if (room) {
                strncpy(room->members[room->member_count], msg->field1, MAX_NAME - 1);
                room->member_count++;
                printf("[SYS] %s joined #%s\n", msg->field1, msg->field2);
            } else {
                printf("[SYS] Room #%s does not exist\n", msg->field2);
            }
            break;
        }
        case MsgKind_LeaveRoom: {
            Room* room = find_room(msg->field2);
            if (room) {
                for (int j = 0; j < room->member_count; j++) {
                    if (strcmp(room->members[j], msg->field1) == 0) {
                        for (int k = j; k < room->member_count - 1; k++) {
                            strncpy(room->members[k], room->members[k + 1], MAX_NAME - 1);
                        }
                        room->member_count--;
                        break;
                    }
                }
            }
            printf("[SYS] %s left #%s\n", msg->field1, msg->field2);
            break;
        }
        case MsgKind_RoomMsg: {
            Room* room = find_room(msg->field1);
            int members = room ? room->member_count : 0;
            printf("[#%s] %s: %s\n", msg->field1, msg->field2, msg->field3);
            printf("  (delivered to %d members)\n", members);
            break;
        }
        case MsgKind_Chat:
            printf("%s: %s\n", msg->field1, msg->field2);
            break;
        case MsgKind_PrivateMsg:
            printf("[PM] %s -> %s: %s\n", msg->field1, msg->field2, msg->field3);
            break;
        case MsgKind_System:
            printf("[SYS] %s\n", msg->field1);
            break;
    }
}

int main(void) {
    add_room("general");
    add_room("random");

    Message msgs[] = {
        { MsgKind_Connect, "Alice", "", "" },
        { MsgKind_Connect, "Bob", "", "" },
        { MsgKind_JoinRoom, "Alice", "random", "" },
        { MsgKind_JoinRoom, "Bob", "random", "" },
        { MsgKind_RoomMsg, "random", "Alice", "Anyone here?" },
        { MsgKind_RoomMsg, "random", "Bob", "Yes!" },
        { MsgKind_LeaveRoom, "Alice", "random", "" },
    };
    int num_msgs = sizeof(msgs) / sizeof(msgs[0]);
    for (int i = 0; i < num_msgs; i++) {
        server_handle(&msgs[i]);
    }
    return 0;
}
