// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn dice_roll(value: i32) {
    match value {
        3 => println!("Lucky number 3!"),
        7 => println!("Got a 7!"),
        _ => println!("Rolled: {}", value),
    }
}

fn main() {
    dice_roll(3);
    dice_roll(7);
    dice_roll(5);
}
