// Auto-generated by a2r transpiler

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Direction {
    North = 0,
    South = 1,
    East = 2,
    West = 3,
}

impl std::fmt::Display for Direction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Direction::North => write!(f, "North"),
            Direction::South => write!(f, "South"),
            Direction::East => write!(f, "East"),
            Direction::West => write!(f, "West"),
        }
    }
}
impl Direction {
    pub fn from_id(id: &str) -> Self {
        match id {
            "North" | "north" => Direction::North,
            "South" | "south" => Direction::South,
            "East" | "east" => Direction::East,
            "West" | "west" => Direction::West,
            _ => Direction::North
        }
    }
}

fn main() {
    let heading = Direction::North;
    println!("Heading: {}", heading);
}
