// Auto-generated by a2c transpiler

#include <stdio.h>
#include <math.h>

typedef struct {
    double x;
    double y;
} Point;

Point Point_new(double x, double y) {
    Point p;
    p.x = x;
    p.y = y;
    return p;
}

double Point_distance(const Point* self, Point other) {
    double dx = self->x - other.x;
    double dy = self->y - other.y;
    return sqrt(dx * dx + dy * dy);
}

int main(void) {
    Point a = Point_new(0.0, 0.0);
    Point b = Point_new(3.0, 4.0);
    printf("%f\n", Point_distance(&a, b));
    return 0;
}
