# Auto-generated by a2p transpiler

from dataclasses import dataclass
import math

@dataclass
class Point:
    x: float
    y: float

    @staticmethod
    def new(x: float, y: float) -> 'Point':
        return Point(x=x, y=y)

    def distance(self, other: 'Point') -> float:
        dx = self.x - other.x
        dy = self.y - other.y
        return math.sqrt(dx * dx + dy * dy)

def main():
    a = Point.new(0.0, 0.0)
    b = Point.new(3.0, 4.0)
    print(a.distance(b))

if __name__ == "__main__":
    main()
