// Auto-generated by a2ts transpiler

class Point {
    x: number;
    y: number;

    constructor(x: number, y: number) {
        this.x = x;
        this.y = y;
    }

    static new(x: number, y: number): Point {
        return new Point(x, y);
    }

    distance(other: Point): number {
        const dx = this.x - other.x;
        const dy = this.y - other.y;
        return Math.sqrt(dx * dx + dy * dy);
    }
}

function main(): void {
    const a = Point.new(0.0, 0.0);
    const b = Point.new(3.0, 4.0);
    console.log(a.distance(b));
}

main();
