// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn area(width: i32, height: i32) -> i32 {
    width * height
}

fn main() {
    let width1: i32 = 30;
    let height1: i32 = 50;
    println!("The area of the rectangle is {} square pixels.", area(width1, height1));
}
