// Auto-generated by a2r transpiler

fn area(width: i64, height: i64) -> i64 {
    width * height
}

fn main() {
    let width1: i64 = 30;
    let height1: i64 = 50;
    println!("The area of the rectangle is {} square pixels.", area(width1, height1));
}
