// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

#define MAX_CLIENTS 64

typedef enum MessageKind {
    MsgKind_Connect,
    MsgKind_Disconnect,
    MsgKind_Chat,
    MsgKind_PrivateMsg,
    MsgKind_System,
} MessageKind;

typedef struct Message {
    MessageKind kind;
    const char* field1;
    const char* field2;
    const char* field3;
} Message;

typedef struct {
    char names[MAX_CLIENTS][64];
    int count;
} ClientList;

ClientList clients = { .count = 0 };

void server_handle(Message* msg) {
    switch (msg->kind) {
        case MsgKind_Connect: {
            strncpy(clients.names[clients.count], msg->field1, 63);
            clients.names[clients.count][63] = '\0';
            clients.count++;
            printf("[SYS] %s joined. Online: %d\n", msg->field1, clients.count);
            break;
        }
        case MsgKind_Disconnect: {
            int found = -1;
            for (int i = 0; i < clients.count; i++) {
                if (strcmp(clients.names[i], msg->field1) == 0) {
                    found = i;
                    break;
                }
            }
            if (found >= 0) {
                for (int i = found; i < clients.count - 1; i++) {
                    strncpy(clients.names[i], clients.names[i + 1], 63);
                }
                clients.count--;
            }
            printf("[SYS] %s left. Online: %d\n", msg->field1, clients.count);
            break;
        }
        case MsgKind_Chat:
            printf("%s: %s\n", msg->field1, msg->field2);
            break;
        case MsgKind_PrivateMsg:
            printf("[PM] %s -> %s: %s\n", msg->field1, msg->field2, msg->field3);
            break;
        case MsgKind_System:
            printf("[SYS] %s\n", msg->field1);
            break;
    }
}

int main(void) {
    Message msgs[] = {
        { MsgKind_Connect, "Alice", NULL, NULL },
        { MsgKind_Connect, "Bob", NULL, NULL },
        { MsgKind_Chat, "Alice", "Hello Bob!", NULL },
        { MsgKind_PrivateMsg, "Bob", "Alice", "Hi Alice!" },
        { MsgKind_Disconnect, "Bob", NULL, NULL },
    };
    int num_msgs = sizeof(msgs) / sizeof(msgs[0]);
    for (int i = 0; i < num_msgs; i++) {
        server_handle(&msgs[i]);
    }
    return 0;
}
