# Auto-generated by a2p transpiler

import threading
import queue
from dataclasses import dataclass
from typing import Union

class MessageKind:
    Connect = "Connect"
    Disconnect = "Disconnect"
    Chat = "Chat"
    PrivateMsg = "PrivateMsg"
    System = "System"

@dataclass
class Message:
    kind: str
    field1: str = ""
    field2: str = ""
    field3: str = ""

def server(q):
    clients = {}
    while True:
        try:
            msg = q.get(timeout=1.0)
            if msg.kind == MessageKind.Connect:
                name = msg.field1
                clients[name] = 1
                print(f"[SYS] {name} joined. Online: {len(clients)}")
            elif msg.kind == MessageKind.Disconnect:
                name = msg.field1
                clients.pop(name, None)
                print(f"[SYS] {name} left. Online: {len(clients)}")
            elif msg.kind == MessageKind.Chat:
                print(f"{msg.field1}: {msg.field2}")
            elif msg.kind == MessageKind.PrivateMsg:
                print(f"[PM] {msg.field1} -> {msg.field2}: {msg.field3}")
            elif msg.kind == MessageKind.System:
                print(f"[SYS] {msg.field1}")
        except queue.Empty:
            break

def main():
    q = queue.Queue()
    t = threading.Thread(target=server, args=(q,))
    t.daemon = True
    t.start()
    q.put(Message(kind=MessageKind.Connect, field1="Alice"))
    q.put(Message(kind=MessageKind.Connect, field1="Bob"))
    q.put(Message(kind=MessageKind.Chat, field1="Alice", field2="Hello Bob!"))
    q.put(Message(kind=MessageKind.PrivateMsg, field1="Bob", field2="Alice", field3="Hi Alice!"))
    q.put(Message(kind=MessageKind.Disconnect, field1="Bob"))
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
