// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;
use std::collections::HashMap;

enum Message {
    Connect(String),
    Disconnect(String),
    Chat(String, String),
    PrivateMsg(String, String, String),
    System(String),
}

fn server(rx: mpsc::Receiver<Message>) {
    let mut clients: HashMap<String, i64> = HashMap::new();
    for msg in rx {
        match msg {
            Message::Connect(name) => {
                clients.insert(name.clone(), 1);
                println!("[SYS] {} joined. Online: {}", name, clients.len());
            }
            Message::Disconnect(name) => {
                clients.remove(&name);
                println!("[SYS] {} left. Online: {}", name, clients.len());
            }
            Message::Chat(from, text) => {
                println!("{}: {}", from, text);
            }
            Message::PrivateMsg(from, to, text) => {
                println!("[PM] {} -> {}: {}", from, to, text);
            }
            Message::System(text) => {
                println!("[SYS] {}", text);
            }
        }
    }
}

fn main() {
    let (tx, rx) = mpsc::channel::<Message>();
    std::thread::spawn(move || {
        server(rx);
    });
    tx.send(Message::Connect(String::from("Alice"))).unwrap();
    tx.send(Message::Connect(String::from("Bob"))).unwrap();
    tx.send(Message::Chat(String::from("Alice"), String::from("Hello Bob!"))).unwrap();
    tx.send(Message::PrivateMsg(String::from("Bob"), String::from("Alice"), String::from("Hi Alice!"))).unwrap();
    tx.send(Message::Disconnect(String::from("Bob"))).unwrap();
}
