// Auto-generated by a2ts transpiler

type Message =
    | { kind: "Connect"; field1: string }
    | { kind: "Disconnect"; field1: string }
    | { kind: "Chat"; field1: string; field2: string }
    | { kind: "PrivateMsg"; field1: string; field2: string; field3: string }
    | { kind: "System"; field1: string };

function server(messages: Message[]): void {
    const clients: Map<string, number> = new Map();
    for (const msg of messages) {
        switch (msg.kind) {
            case "Connect":
                clients.set(msg.field1, 1);
                console.log(`[SYS] ${msg.field1} joined. Online: ${clients.size}`);
                break;
            case "Disconnect":
                clients.delete(msg.field1);
                console.log(`[SYS] ${msg.field1} left. Online: ${clients.size}`);
                break;
            case "Chat":
                console.log(`${msg.field1}: ${msg.field2}`);
                break;
            case "PrivateMsg":
                console.log(`[PM] ${msg.field1} -> ${msg.field2}: ${msg.field3}`);
                break;
            case "System":
                console.log(`[SYS] ${msg.field1}`);
                break;
        }
    }
}

function main(): void {
    const messages: Message[] = [
        { kind: "Connect", field1: "Alice" },
        { kind: "Connect", field1: "Bob" },
        { kind: "Chat", field1: "Alice", field2: "Hello Bob!" },
        { kind: "PrivateMsg", field1: "Bob", field2: "Alice", field3: "Hi Alice!" },
        { kind: "Disconnect", field1: "Bob" },
    ];
    server(messages);
}

main();
