// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

#define log(msg) printf("[LOG] " msg "\n")

int main(void) {
    log("Starting up");
    log("Processing data");
    return 0;
}
