// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

macro_rules! log {
    ($msg:expr) => {
        println!("[LOG] {}", $msg);
    };
}

fn main() {
    log!("Starting up");
    log!("Processing data");
}
