// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

typedef struct SetEntry {
    long long value;
    struct SetEntry* next;
} SetEntry;

typedef struct {
    SetEntry* head;
    int size;
} HashSet;

void set_insert(HashSet* set, long long value) {
    SetEntry* entry = set->head;
    while (entry != NULL) {
        if (entry->value == value) {
            return;
        }
        entry = entry->next;
    }
    SetEntry* new_entry = (SetEntry*)malloc(sizeof(SetEntry));
    new_entry->value = value;
    new_entry->next = set->head;
    set->head = new_entry;
    set->size++;
}

bool set_contains(HashSet* set, long long value) {
    SetEntry* entry = set->head;
    while (entry != NULL) {
        if (entry->value == value) {
            return true;
        }
        entry = entry->next;
    }
    return false;
}

int main(void) {
    HashSet unique = {NULL, 0};
    set_insert(&unique, 1);
    set_insert(&unique, 2);
    set_insert(&unique, 3);
    set_insert(&unique, 2);
    set_insert(&unique, 1);
    printf("%d\n", unique.size);
    set_insert(&unique, 4);
    printf("%s\n", set_contains(&unique, 3) ? "true" : "false");
    return 0;
}
