// Auto-generated by a2r transpiler

use std::collections::HashSet;

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut unique: HashSet<i64> = HashSet::new();
    unique.insert(1);
    unique.insert(2);
    unique.insert(3);
    unique.insert(2);
    unique.insert(1);
    println!("{}", unique.len());
    unique.insert(4);
    println!("{}", unique.contains(&3));
}
