// Auto-generated by a2ts transpiler

function main(): void {
    let unique: Set<number> = new Set([1, 2, 3, 2, 1]);
    console.log(unique.size);
    unique.add(4);
    console.log(unique.has(3));
}

main();
