// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn increment(n: &mut i64) {
    *n = *n + 1;
}

fn main() {
    let mut x = 5;
    increment(&mut x);
    println!("{}", x);  // x is now 6
}
