// Auto-generated by a2ts transpiler

function increment(n: { value: number }): void {
    n.value = n.value + 1;
}

function main(): void {
    const x = { value: 5 };
    increment(x);
    console.log(x.value);  // x is now 6
}

main();
