// Auto-generated by a2c transpiler

#include <stdio.h>

void increment(long long* n) {
    *n = *n + 1;
}

int main(void) {
    long long x = 5;
    increment(&x);
    printf("%lld\n", x);  /* x is now 6 */
    return 0;
}
