// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::time::Duration;

fn main() {
    trpl::block_on(async {
        let fut1 = async {
            println!("Task 1 starting...");
            trpl::sleep(Duration::from_millis(1000)).await;
            println!("Task 1 done!");
            42
        };

        let fut2 = async {
            println!("Task 2 starting...");
            trpl::sleep(Duration::from_millis(500)).await;
            println!("Task 2 done!");
            "hello"
        };

        let (result1, result2) = trpl::join(fut1, fut2).await;
        println!("Results: {}, {}", result1, result2);
    })
}
