// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

fn read_number(text: String) -> Result<i64, Box<dyn std::error::Error>> {
    let result = a2r_std::value_to_int(&text);
    let value = result.collect();
    value
}

fn main() {
    let n = read_number("42");
    println!("Number: {:?}", n);
}
