// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn read_number(text: String) -> Result<i32, String> {
    let result = text.to_int();
    let value = result.collect();
    value
}

fn main() {
    let n = read_number("42");
    println!("Number: {}", n);
}
