// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn format_value(v: std::fmt::Display) -> String {
    if v is String {
        v.to_uppercase()
    } else {
        String::from("Not a string")
    }
}

fn main() {
    println!("{}", format_value(String::from("hello")));
    println!("{}", format_value(42));
}
