# Auto-generated by a2p transpiler

def format_value(v):
    if isinstance(v, str):
        return v.upper()
    else:
        return "Not a string"

def main():
    print(format_value("hello"))
    print(format_value(42))

if __name__ == "__main__":
    main()
