// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <ctype.h>

typedef enum ValueType {
    ValueType_Int,
    ValueType_Float,
    ValueType_String,
} ValueType;

typedef struct {
    ValueType kind;
    union {
        long int_val;
        double float_val;
        const char* str_val;
    };
} Value;

const char* format_value(Value v) {
    if (v.kind == ValueType_String) {
        static char buf[256];
        strcpy(buf, v.str_val);
        for (int i = 0; buf[i]; i++) {
            buf[i] = toupper((unsigned char)buf[i]);
        }
        return buf;
    } else {
        return "Not a string";
    }
}

int main(void) {
    printf("%s\n", format_value((Value){ .kind = ValueType_String, .str_val = "hello" }));
    printf("%s\n", format_value((Value){ .kind = ValueType_Int, .int_val = 42 }));
    return 0;
}
