// Auto-generated by a2ts transpiler

function formatValue(v: number | string): string {
    if (typeof v === "string") {
        return v.toUpperCase();
    } else {
        return "Not a string";
    }
}

function main(): void {
    console.log(formatValue("hello"));
    console.log(formatValue(42));
}

main();
