// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let x: i32 = 5;
    let x: i32 = x + 1;
    println!("x = {}", x);


    let spaces: String = "   ".to_string();
    println!("spaces string len = {}", spaces.len());

    let spaces = spaces.len();
    println!("spaces count = {}", spaces);
}
