// Auto-generated by a2r transpiler

fn main() {
    let x: i64 = 5;
    let x: i64 = x + 1;
    println!("x = {}", x);


    let spaces: String = "   ".to_string();
    println!("spaces string len = {}", (spaces.len() as i64));

    let spaces = (spaces.len() as i64);
    println!("spaces count = {}", spaces);
}
