// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut a: bool = true;
    let mut b: bool = false;
    println!("{}", a && b);
    println!("{}", a || b);
    println!("{}", !a);
}
