// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

int main(void) {
    bool a = true;
    bool b = false;
    printf("%s\n", (a && b) ? "true" : "false");
    printf("%s\n", (a || b) ? "true" : "false");
    printf("%s\n", (!a) ? "true" : "false");
    return 0;
}
