// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let example_closure = |x| x;
    let s = example_closure(String::from("hello"));
    println!("{}", s);
}
