// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::rc::Rc;
use std::cell::RefCell;

#[derive(Debug)]
struct Item {
    value: i64,
    next: Option<Rc<RefCell<Item>>>,
}

fn main() {
    let third = Rc::new(RefCell::new(Item {
        value: 30,
        next: None,
    }));
    let second = Rc::new(RefCell::new(Item {
        value: 20,
        next: Some(Rc::clone(&third)),
    }));
    let first = Rc::new(RefCell::new(Item {
        value: 10,
        next: Some(Rc::clone(&second)),
    }));
    println!("{}", first.borrow().value);
    println!("{}", first.borrow().next.as_ref().unwrap().borrow().value);
}
