// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::fs;

fn main() -> Result<(), String> {
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        panic!("not enough arguments");
    }
    let query = &args[1];
    let file_path = &args[2];

    let contents = fs::read_to_string(file_path).collect();
    println!("{}", contents);
    Ok(())
}
