// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    println!("Guess the number!");
    let secret_number: i32 = 7;

    loop {
        println!("Please input your guess.");
        let guess: i32 = 7;
                if guess < secret_number { println!("Too small!"); }
        if guess > secret_number { println!("Too big!"); }
        if guess == secret_number { println!("You win!"); break; }
    }
}
