// Auto-generated by a2r transpiler

fn main() {
    println!("Guess the number!");
    let secret_number: i64 = 7;

    loop {
        println!("Please input your guess.");
        let guess: i64 = 7;
        
        if guess < secret_number {
            println!("Too small!");
        }
        if guess > secret_number {
            println!("Too big!");
        }
        if guess == secret_number {
            println!("You win!");
            break;
        }
    }
}
