# Auto-generated by a2p transpiler

Point = tuple[float, float]
Id = int

def main():
    origin: Point = (0.0, 0.0)
    user_id: Id = 42
    print(origin)
    print(user_id)

if __name__ == "__main__":
    main()
