// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct {
    double _0;
    double _1;
} Point;

typedef long long Id;

int main(void) {
    Point origin = {0.0, 0.0};
    Id user_id = 42;
    printf("(%f, %f)\n", origin._0, origin._1);
    printf("%lld\n", user_id);
    return 0;
}
