// Auto-generated by a2ts transpiler

type Point = [number, number];
type Id = number;

function main(): void {
    let origin: Point = [0.0, 0.0];
    let user_id: Id = 42;
    console.log(origin);
    console.log(user_id);
}

main();
