// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

type Point = (f64, f64);
type Id = i64;

fn main() {
    let mut origin: Point = (0.0, 0.0);
    let mut user_id: Id = 42;
    println!("{:?}", origin);
    println!("{}", user_id);
}
