// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    long long sum = 5 + 3;
    long long diff = 10 - 4;
    long long product = 6 * 7;
    long long quotient = 15 / 4;
    long long remainder = 17 % 5;
    printf("%lld\n", sum);
    printf("%lld\n", diff);
    printf("%lld\n", product);
    printf("%lld\n", quotient);
    printf("%lld\n", remainder);
    return 0;
}
