// Auto-generated by a2ts transpiler

function main(): void {
    let sum: number = 5 + 3;
    let diff: number = 10 - 4;
    let product: number = 6 * 7;
    let quotient: number = Math.trunc(15 / 4);
    let remainder: number = 17 % 5;
    console.log(sum);
    console.log(diff);
    console.log(product);
    console.log(quotient);
    console.log(remainder);
}

main();
