# Auto-generated by a2p transpiler

def main():
    sum = 5 + 3
    diff = 10 - 4
    product = 6 * 7
    quotient = 15 // 4
    remainder = 17 % 5
    print(sum)
    print(diff)
    print(product)
    print(quotient)
    print(remainder)

if __name__ == "__main__":
    main()
