// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut sum: i64 = 5 + 3;
    let mut diff: i64 = 10 - 4;
    let mut product: i64 = 6 * 7;
    let mut quotient: i64 = 15 / 4;
    let mut remainder: i64 = 17 % 5;
    println!("{}", sum);
    println!("{}", diff);
    println!("{}", product);
    println!("{}", quotient);
    println!("{}", remainder);
}
