// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn greet(name: String) {
    println!("Hello, {}!", name);
}

fn main() {
    greet(String::from("Alice"));
    greet(String::from("Bob"));
}
