// Auto-generated by a2r transpiler

fn main() {
    let s1 = "hello".to_string();
    let s2 = String::from("world");
    println!("s1: {}", s1);
    println!("s2: {}", s2);

    let mut s3 = String::from("foo");
    s3.push_str("bar");
    println!("s3: {}", s3);
}
