# Auto-generated by a2p transpiler

def main():
    numbers = [1, 2, 3, 4, 5]
    print(numbers[0])
    print(len(numbers))
    names = ["Alice", "Bob", "Charlie"]
    for name in names:
        print(name)

if __name__ == "__main__":
    main()
