// Auto-generated by a2ts transpiler

function main(): void {
    let numbers: number[] = [1, 2, 3, 4, 5];
    console.log(numbers[0]);
    console.log(numbers.length);
    let names: string[] = ["Alice", "Bob", "Charlie"];
    for (let name of names) {
        console.log(name);
    }
}

main();
