// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut numbers: Vec<i64> = vec![1, 2, 3, 4, 5];
    println!("{}", numbers[0]);
    println!("{}", numbers.len());
    let mut names: Vec<String> = vec![
        String::from("Alice"),
        String::from("Bob"),
        String::from("Charlie"),
    ];
    for name in &names {
        println!("{}", name);
    }
}
