// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    long long numbers[] = {1, 2, 3, 4, 5};
    int numbers_len = 5;
    printf("%lld\n", numbers[0]);
    printf("%d\n", numbers_len);

    const char* names[] = {"Alice", "Bob", "Charlie"};
    int names_len = 3;
    for (int i = 0; i < names_len; i++) {
        printf("%s\n", names[i]);
    }
    return 0;
}
