// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::sync::mpsc;
use std::thread;

fn main() {
    let data = ["task-a", "task-b", "task-c"];

    let handles: Vec<_> = (0..3)
        .map(|i| {
            let data = data[i].to_string();
            thread::spawn(move || {
                println!("Worker {} processing: {}", i + 1, data);
            })
        })
        .collect();

    for handle in handles {
        handle.join().unwrap();
    }
}
