# Auto-generated by a2p transpiler

from dataclasses import dataclass
from typing import Optional

@dataclass
class User:
    name: str
    age: int

def find_user(id: int) -> Optional[User]:
    if id == 1:
        return User(name="Alice", age=30)
    else:
        return None

def main():
    user = find_user(1)
    if user is not None:
        print(user.name)
    missing = find_user(2)
    print(missing)

if __name__ == "__main__":
    main()
