// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct User {
    name: String,
    age: i64,
}

fn find_user(id: i64) -> Option<User> {
    if id == 1 {
        Some(User {
            name: String::from("Alice"),
            age: 30,
        })
    } else {
        None
    }
}

fn main() {
    let mut user = find_user(1).unwrap();
    println!("{}", user.name);
    let mut missing = find_user(2);
    println!("{:?}", missing);
}
