// Auto-generated by a2ts transpiler

class User {
    name: string;
    age: number;

    constructor(name: string, age: number) {
        this.name = name;
        this.age = age;
    }
}

function findUser(id: number): User | null {
    if (id === 1) {
        return new User("Alice", 30);
    } else {
        return null;
    }
}

function main(): void {
    const user = findUser(1);
    if (user !== null) {
        console.log(user.name);
    }
    const missing = findUser(2);
    console.log(missing);
}

main();
