// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    char name[256];
    long long age;
    int _some;
} User;

User find_user(long long id) {
    User result;
    if (id == 1) {
        strcpy(result.name, "Alice");
        result.age = 30;
        result._some = 1;
    } else {
        result._some = 0;
    }
    return result;
}

int main(void) {
    User user = find_user(1);
    if (user._some) {
        printf("%s\n", user.name);
    }
    User missing = find_user(2);
    if (missing._some) {
        printf("%s\n", missing.name);
    } else {
        printf("None\n");
    }
    return 0;
}
