// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

fn delayed_greeting(name: String, caller_tx: mpsc::Sender<String>) {
    let _ = caller_tx.send("Hello, ".to_string() + &name + "!");
}

fn main() {
    let (caller_tx, caller_rx) = mpsc::channel::<String>();

    std::thread::spawn(move || {
        delayed_greeting(String::from("Alice"), caller_tx);
    });

    match caller_rx.recv() {
        Ok(msg) => {
            println!("{}", msg);
        }
        Err(_) => {}
    }
}
