// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

void delayed_greeting_fn(const char* name, char* result) {
    sprintf(result, "Hello, %s!", name);
}

int main(void) {
    char msg[256];
    delayed_greeting_fn("Alice", msg);
    printf("%s\n", msg);
    return 0;
}
