# Auto-generated by a2p transpiler

import threading
import queue

def delayed_greeting(name, out_q):
    out_q.put("Hello, " + name + "!")

def main():
    out_q = queue.Queue()
    t = threading.Thread(target=delayed_greeting, args=("Alice", out_q))
    t.daemon = True
    t.start()
    try:
        msg = out_q.get(timeout=2.0)
        print(msg)
    except queue.Empty:
        pass
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
