// Auto-generated by a2ts transpiler

function delayedGreeting(name: string): Promise<string> {
    return new Promise((resolve) => {
        resolve("Hello, " + name + "!");
    });
}

function main(): void {
    delayedGreeting("Alice").then((msg) => {
        console.log(msg);
    });
}

main();
