// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Drawable {
    fn draw(&self);
}

struct Circle {
    radius: f64,
}

impl Drawable for Circle {
    fn draw(&self) {
        println!("Drawing circle with radius {}", self.radius);
    }
}

struct Square {
    side: f64,
}

impl Drawable for Square {
    fn draw(&self) {
        println!("Drawing square with side {}", self.side);
    }
}

fn render<T: Drawable>(d: &T) {
    d.draw();
}

fn main() {
    let mut c = Circle { radius: 5.0 };
    let mut s = Square { side: 3.0 };
    render(&c);
    render(&s);
}
