# Auto-generated by a2p transpiler

from abc import ABC, abstractmethod
from dataclasses import dataclass

class Drawable(ABC):
    @abstractmethod
    def draw(self):
        pass

@dataclass
class Circle:
    radius: float

    def draw(self):
        print(f"Drawing circle with radius {self.radius}")

@dataclass
class Square:
    side: float

    def draw(self):
        print(f"Drawing square with side {self.side}")

def render(d: Drawable):
    d.draw()

def main():
    c = Circle(radius=5.0)
    s = Square(side=3.0)
    render(c)
    render(s)

if __name__ == "__main__":
    main()
