// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct {
    void (*draw)(const void*);
} DrawableVtable;

typedef struct {
    double radius;
    const DrawableVtable* vtable;
} Circle;

void Circle_draw(const void* self) {
    const Circle* c = (const Circle*)self;
    printf("Drawing circle with radius %f\n", c->radius);
}

static const DrawableVtable Circle_vtable = {
    .draw = Circle_draw,
};

typedef struct {
    double side;
    const DrawableVtable* vtable;
} Square;

void Square_draw(const void* self) {
    const Square* s = (const Square*)self;
    printf("Drawing square with side %f\n", s->side);
}

static const DrawableVtable Square_vtable = {
    .draw = Square_draw,
};

void render(const void* d) {
    const DrawableVtable* vt = *(const DrawableVtable**)d;
    vt->draw(d);
}

int main(void) {
    Circle c = { .radius = 5.0, .vtable = &Circle_vtable };
    Square s = { .side = 3.0, .vtable = &Square_vtable };
    render(&c);
    render(&s);
    return 0;
}
