// Auto-generated by a2ts transpiler

interface Drawable {
    draw(): void;
}

class Circle implements Drawable {
    radius: number;

    constructor(radius: number) {
        this.radius = radius;
    }

    draw(): void {
        console.log(`Drawing circle with radius ${this.radius}`);
    }
}

class Square implements Drawable {
    side: number;

    constructor(side: number) {
        this.side = side;
    }

    draw(): void {
        console.log(`Drawing square with side ${this.side}`);
    }
}

function render(d: Drawable): void {
    d.draw();
}

function main(): void {
    const c = new Circle(5.0);
    const s = new Square(3.0);
    render(c);
    render(s);
}

main();
