// Auto-generated by a2ts transpiler

function main(): void {
    let person: { name: string; age: number } = { name: "Alice", age: 30 };
    console.log(person.name);
    console.log(person.age);
    person.age = 31;
    console.log(person.age);
}

main();
