# Auto-generated by a2p transpiler

def main():
    person = {"name": "Alice", "age": 30}
    print(person["name"])
    print(person["age"])
    person["age"] = 31
    print(person["age"])

if __name__ == "__main__":
    main()
