// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut person = AutoObject::new();
    person.set("name", AutoValue::from("Alice"));
    person.set("age", AutoValue::from(30));
    println!("{}", person.get("name").as_str());
    println!("{}", person.get("age").as_i64());
    person.set("age", AutoValue::from(31));
    println!("{}", person.get("age").as_i64());
}
