// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    char name[256];
    long long age;
} Person;

int main(void) {
    Person person;
    strcpy(person.name, "Alice");
    person.age = 30;
    printf("%s\n", person.name);
    printf("%lld\n", person.age);
    person.age = 31;
    printf("%lld\n", person.age);
    return 0;
}
