// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    trpl::block_on(async {
        let vals = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
        let mut results = trpl::stream_from_iter(vals)
            .filter(|x| x % 2 == 0)
            .map(|x| x * 3)
            .take(3);

        while let Some(value) = results.next().await {
            println!("{value}");  // 6, 12, 18
        }
    })
}
