# Auto-generated by a2p transpiler

def fib(n):
    if n <= 1:
        return n
    else:
        return fib(n - 1) + fib(n - 2)

FIB_10 = fib(10)

def main():
    print("Fibonacci(10) = " + str(FIB_10))

if __name__ == "__main__":
    main()
