// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn fib(n: i32) -> i32 {
    if n <= 1 {
        n
    } else {
        fib(n - 1) + fib(n - 2)
    }
}

const FIB_10: i32 = {
    fn fib(n: i32) -> i32 {
        if n <= 1 { n } else { fib(n - 1) + fib(n - 2) }
    }
    fib(10)
};

fn main() {
    println!("Fibonacci(10) = {}", FIB_10);
}
