// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

int fib(int n) {
    if (n <= 1) {
        return n;
    } else {
        return fib(n - 1) + fib(n - 2);
    }
}

#define FIB_10 55

int main(void) {
    printf("Fibonacci(10) = %d\n", FIB_10);
    return 0;
}
