// Auto-generated by a2ts transpiler

function fib(n: number): number {
    if (n <= 1) {
        return n;
    } else {
        return fib(n - 1) + fib(n - 2);
    }
}

const FIB_10: number = fib(10);

function main(): void {
    console.log("Fibonacci(10) = " + FIB_10);
}

main();
