// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut list: Vec<i64> = vec![10, 20, 30];
    list.push(40);
    println!("{:?}", list);
    let last: Option<i64> = list.pop();
    println!("{}", last.unwrap());
    println!("{}", list.contains(&20));
    list.sort();
    println!("{:?}", list);
}
