// Auto-generated by a2ts transpiler

function main(): void {
    let list: number[] = [10, 20, 30];
    list.push(40);
    console.log(list);
    let last: number | undefined = list.pop();
    console.log(last);
    console.log(list.includes(20));
    list.sort((a, b) => a - b);
    console.log(list);
}

main();
