# Auto-generated by a2p transpiler

def main():
    list = [10, 20, 30]
    list.append(40)
    print(list)
    last = list.pop()
    print(last)
    print(20 in list)
    list.sort()
    print(list)

if __name__ == "__main__":
    main()
