// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

typedef struct {
    long long* data;
    int size;
    int capacity;
} Vec;

void vec_push(Vec* v, long long value) {
    if (v->size >= v->capacity) {
        v->capacity = v->capacity == 0 ? 4 : v->capacity * 2;
        v->data = (long long*)realloc(v->data, v->capacity * sizeof(long long));
    }
    v->data[v->size++] = value;
}

long long vec_pop(Vec* v) {
    return v->data[--v->size];
}

bool vec_contains(Vec* v, long long value) {
    for (int i = 0; i < v->size; i++) {
        if (v->data[i] == value) return true;
    }
    return false;
}

int compare(const void* a, const void* b) {
    long long diff = *(long long*)a - *(long long*)b;
    return (diff > 0) - (diff < 0);
}

void vec_print(Vec* v) {
    printf("[");
    for (int i = 0; i < v->size; i++) {
        if (i > 0) printf(", ");
        printf("%lld", v->data[i]);
    }
    printf("]\n");
}

int main(void) {
    Vec list = {NULL, 0, 0};
    vec_push(&list, 10);
    vec_push(&list, 20);
    vec_push(&list, 30);
    vec_push(&list, 40);
    vec_print(&list);
    long long last = vec_pop(&list);
    printf("%lld\n", last);
    printf("%s\n", vec_contains(&list, 20) ? "true" : "false");
    qsort(list.data, list.size, sizeof(long long), compare);
    vec_print(&list);
    free(list.data);
    return 0;
}
