// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn slow(name: &str) {
    let mut count = 0;
    for i in 0..1_000_000 {
        count += i;
        if i % 100_000 == 0 {
            trpl::yield_now().await;
        }
    }
    println!("{name}: count = {count}");
}

fn main() {
    trpl::block_on(async {
        let a = async { slow("A") };
        let b = async { slow("B") };
        trpl::join(a, b).await;
    })
}
