// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let x: i32 = 5;
    let y: i32 = x;
    println!("x = {}, y = {}", x, y);
}
