// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn find_item(index: i32) -> Option<i32> {
    if index < 0 {
        return None;
    }
    Some(index * 10)
}

fn main() {
    let result1 = find_item(5);
    let result2 = find_item(-1);

    let value: i32 = result1.unwrap_or(0);
    println!("Value: {}", value);

    let default: i32 = result2.unwrap_or(99);
    println!("Default: {}", default);
}
