// Auto-generated by a2r transpiler

fn find_item(index: i64) -> Option<i64> {
    if index < 0 {
        return None;
    }
    Some(index * 10)
}

fn main() {
    let result1 = find_item(5);
    let result2 = find_item(-1);

    let value: i64 = result1.unwrap_or(0);
    println!("Value: {}", value);

    let default: i64 = result2.unwrap_or(99);
    println!("Default: {}", default);
}
