// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Renderable {
    fn render(&self) -> String;
}

struct Button {
    label: String,
}

impl Renderable for Button {
    fn render(&self) -> String {
        "[Button: ".to_string() + &self.label + "]"
    }
}

struct TextField {
    text: String,
}

impl Renderable for TextField {
    fn render(&self) -> String {
        "[TextField: ".to_string() + &self.text + "]"
    }
}

fn render_all(items: Vec<&dyn Renderable>) {
    for item in items {
        println!("{}", item.render());
    }
}

fn main() {
    let mut b = Button { label: String::from("Click me") };
    let mut t = TextField { text: String::from("Type here") };
    render_all(vec![&b, &t]);
}
