# Auto-generated by a2p transpiler

from abc import ABC, abstractmethod
from dataclasses import dataclass

class Renderable(ABC):
    @abstractmethod
    def render(self) -> str:
        pass

@dataclass
class Button:
    label: str

    def render(self) -> str:
        return "[Button: " + self.label + "]"

@dataclass
class TextField:
    text: str

    def render(self) -> str:
        return "[TextField: " + self.text + "]"

def render_all(items):
    for item in items:
        print(item.render())

def main():
    b = Button(label="Click me")
    t = TextField(text="Type here")
    render_all([b, t])

if __name__ == "__main__":
    main()
