// Auto-generated by a2ts transpiler

interface Renderable {
    render(): string;
}

class Button implements Renderable {
    label: string;

    constructor(label: string) {
        this.label = label;
    }

    render(): string {
        return `[Button: ${this.label}]`;
    }
}

class TextField implements Renderable {
    text: string;

    constructor(text: string) {
        this.text = text;
    }

    render(): string {
        return `[TextField: ${this.text}]`;
    }
}

function renderAll(items: Renderable[]): void {
    for (const item of items) {
        console.log(item.render());
    }
}

function main(): void {
    const b = new Button("Click me");
    const t = new TextField("Type here");
    renderAll([b, t]);
}

main();
