// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct {
    const char* (*render)(const void*);
} RenderableVtable;

typedef struct {
    char label[256];
    const RenderableVtable* vtable;
} Button;

const char* Button_render(const void* self) {
    static char buf[512];
    const Button* b = (const Button*)self;
    snprintf(buf, sizeof(buf), "[Button: %s]", b->label);
    return buf;
}

static const RenderableVtable Button_vtable = {
    .render = Button_render,
};

typedef struct {
    char text[256];
    const RenderableVtable* vtable;
} TextField;

const char* TextField_render(const void* self) {
    static char buf[512];
    const TextField* t = (const TextField*)self;
    snprintf(buf, sizeof(buf), "[TextField: %s]", t->text);
    return buf;
}

static const RenderableVtable TextField_vtable = {
    .render = TextField_render,
};

void render_all(const void* items[], int count) {
    for (int i = 0; i < count; i++) {
        const RenderableVtable* vt = *(const RenderableVtable**)items[i];
        printf("%s\n", vt->render(items[i]));
    }
}

int main(void) {
    Button b = { .label = "Click me", .vtable = &Button_vtable };
    TextField t = { .text = "Type here", .vtable = &TextField_vtable };
    const void* items[] = { &b, &t };
    render_all(items, 2);
    return 0;
}
