// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Message {
    Quit,
    Write(String),
}


fn main() {
    let msg = Message::Write("hello".to_string());
    println!("Message created");
}
