// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Message {
    Quit(()),
    Write(String),
}


fn main() {
    let msg = Message::Write("hello");
    println!("Message created");
}
