# Auto-generated by a2p transpiler

class Buffer:
    def __init__(self, data: int):
        self.data = data

    @staticmethod
    def new(size: int) -> Buffer:
        return Buffer(data=size)

def main():
    b1 = Buffer.new(1024)
    b2 = Buffer.new(2048)
    # Automatically freed when b1 and b2 go out of scope
    print("Buffers allocated and auto-freed")

if __name__ == "__main__":
    main()
