// Auto-generated by a2ts transpiler

class Buffer {
    data: number;

    constructor(data: number) {
        this.data = data;
    }

    static new(size: number): Buffer {
        return new Buffer(size);
    }
}

function main(): void {
    const b1 = Buffer.new(1024);
    const b2 = Buffer.new(2048);
    // Automatically freed when b1 and b2 go out of scope
    console.log("Buffers allocated and auto-freed");
}

main();
