// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct Buffer {
    long long data;
} Buffer;

Buffer Buffer_new(long long size) {
    return (Buffer){ .data = size };
}

int main(void) {
    Buffer b1 = Buffer_new(1024);
    Buffer b2 = Buffer_new(2048);
    /* Automatically freed when b1 and b2 go out of scope */
    printf("Buffers allocated and auto-freed\n");
    return 0;
}
