// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Buffer {
    data: i64,
}

impl Buffer {
    fn new(size: i64) -> Buffer {
        Buffer { data: size }
    }
}

fn main() {
    let b1 = Buffer::new(1024);
    let b2 = Buffer::new(2048);
    // Automatically freed when b1 and b2 go out of scope
    println!("Buffers allocated and auto-freed");
}
