// Auto-generated by a2ts transpiler

function utilsHelper(): void {
    console.log("public helper");
}

// private
function utilsInternal(): void {
    console.log("internal only");
}

function main(): void {
    utilsHelper();
    // utilsInternal();  // ERROR: private
}

main();
