// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

mod utils {
    pub fn helper() {
        println!("public helper");
    }

    fn internal() {
        println!("internal only");
    }
}

fn main() {
    utils::helper();
    // utils::internal();  // ERROR: private
}
