# Auto-generated by a2p transpiler

def utils_helper() -> None:
    print("public helper")

def utils_internal() -> None:
    print("internal only")

def main():
    utils_helper()
    # utils_internal()  # ERROR: private

if __name__ == "__main__":
    main()
