// Auto-generated by a2c transpiler

#include <stdio.h>

void utils_helper(void) {
    printf("public helper\n");
}

/* static */ void utils_internal(void) {
    printf("internal only\n");
}

int main(void) {
    utils_helper();
    /* utils_internal();  // ERROR: private */
    return 0;
}
