# Auto-generated by a2p transpiler

import threading
import queue

class Request:
    def __init__(self, url: str, reply_to: int):
        self.url = url
        self.reply_to = reply_to

def fetcher(q):
    while True:
        try:
            req = q.get(timeout=1.0)
            result = "Response from " + req.url
            print("Fetched: " + req.url)
        except queue.Empty:
            break

def main():
    q = queue.Queue()
    t = threading.Thread(target=fetcher, args=(q,))
    t.daemon = True
    t.start()
    q.put(Request(url="https://auto.dev", reply_to=0))
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
