// Auto-generated by a2ts transpiler

class Request {
    url: string;
    reply_to: number;

    constructor(url: string, reply_to: number) {
        this.url = url;
        this.reply_to = reply_to;
    }
}

function fetcher(messages: Request[]): void {
    for (const req of messages) {
        const result = "Response from " + req.url;
        console.log("Fetched: " + req.url);
    }
}

function main(): void {
    const messages: Request[] = [
        new Request("https://auto.dev", 0),
    ];
    fetcher(messages);
}

main();
