// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

#[derive(Clone)]
struct Request {
    url: String,
    reply_to: i64,
}

fn fetcher(rx: mpsc::Receiver<Request>) {
    for req in rx {
        let _result = "Response from ".to_string() + &req.url;
        println!("{}", "Fetched: ".to_string() + &req.url);
    }
}

fn main() {
    let (tx, rx) = mpsc::channel::<Request>();
    std::thread::spawn(move || {
        fetcher(rx);
    });
    tx.send(Request { url: String::from("https://auto.dev"), reply_to: 0 }).unwrap();
}
