// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct Request {
    const char* url;
    int reply_to;
} Request;

void fetcher_fn(void) {
    // Simulated message loop
    Request req = { .url = "https://auto.dev", .reply_to = 0 };
    const char* result = "Response from ";
    printf("Fetched: %s\n", req.url);
}

int main(void) {
    fetcher_fn();
    return 0;
}
