// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

void test_string_operations() {
    const char* s = "hello";
    if (strlen(s) != 5) {
        fprintf(stderr, "assertion failed: s.len() == 5\n");
        __builtin_trap();
    }
    if (strcmp(s, "world") == 0) {
        fprintf(stderr, "assertion failed: s != \"world\"\n");
        __builtin_trap();
    }
    if (strstr(s, "ell") == NULL) {
        fprintf(stderr, "assertion failed: s.contains(\"ell\")\n");
        __builtin_trap();
    }
}
