// Auto-generated by a2ts transpiler

function testStringOperations(): void {
    const s = "hello";
    if (s.length !== 5) {
        throw new Error(`assertion failed: s.length === 5, got ${s.length}`);
    }
    if (s === "world") {
        throw new Error('assertion failed: s !== "world"');
    }
    if (!s.includes("ell")) {
        throw new Error('assertion failed: s.includes("ell")');
    }
}
