// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[test]
fn test_string_operations() {
    let mut s = String::from("hello");
    assert_eq!(s.len(), 5);
    assert_ne!(s, String::from("world"));
    assert!(s.contains("ell"));
}
