// Auto-generated by a2ts transpiler

function main(): void {
    const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    const evens = numbers.filter((x: number) => x % 2 === 0);
    for (const n of evens) {
        console.log(n);
    }
}

main();
