// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

int main(void) {
    int numbers[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    int len = 10;
    int evens[10];
    int evens_len = 0;
    for (int i = 0; i < len; i++) {
        if (numbers[i] % 2 == 0) {
            evens[evens_len++] = numbers[i];
        }
    }
    for (int i = 0; i < evens_len; i++) {
        printf("%d\n", evens[i]);
    }
    return 0;
}
