# Auto-generated by a2p transpiler

def main():
    numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    evens = [x for x in numbers if x % 2 == 0]
    for n in evens:
        print(n)

if __name__ == "__main__":
    main()
