// Auto-generated by a2ts transpiler

class User {
    name: string;
    age: number;
    active: boolean;

    constructor(name: string, age: number, active: boolean) {
        this.name = name;
        this.age = age;
        this.active = active;
    }
}

function main(): void {
    const alice: User = new User("Alice", 30, true);
    console.log(alice.name);
    console.log(alice.age);
}

main();
