// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct {
    char name[256];
    long long age;
    bool active;
} User;

int main(void) {
    User alice;
    strcpy(alice.name, "Alice");
    alice.age = 30;
    alice.active = true;
    printf("%s\n", alice.name);
    printf("%lld\n", alice.age);
    return 0;
}
