// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct User {
    name: String,
    age: i64,
    active: bool,
}

fn main() {
    let mut alice = User { name: String::from("Alice"), age: 30, active: true };
    println!("{}", alice.name);
    println!("{}", alice.age);
}
