# Auto-generated by a2p transpiler

from dataclasses import dataclass

@dataclass
class User:
    name: str
    age: int
    active: bool

def main():
    alice = User(name="Alice", age=30, active=True)
    print(alice.name)
    print(alice.age)

if __name__ == "__main__":
    main()
