// Auto-generated by a2r transpiler

fn divide(a: i64, b: i64) -> Option<i64> {
    if b == 0 {
        return None;
    }
    Some(a / b)
}

fn main() {
    let result1 = divide(10, 3);
    let result2 = divide(10, 0);
    println!("Done");
}
