// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let expensive_closure = |num: i32| -> i32 {
        println!("calculating slowly...");
        num
    };
    let result = expensive_closure(10);
    println!("{}", result);
}
