// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let s: String = String::from("Hello, Auto!");
    println!("{}", s.len());
    println!("{}", s.chars().nth(0).unwrap());
    let parts: Vec<&str> = s.split(", ").collect();
    println!("{:?}", parts);
    let upper: String = s.to_uppercase();
    println!("{}", upper);
}
