// Auto-generated by a2ts transpiler

function main(): void {
    let s: string = "Hello, Auto!";
    console.log(s.length);
    console.log(s[0]);
    let parts: string[] = s.split(", ");
    console.log(parts);
    let upper: string = s.toUpperCase();
    console.log(upper);
}

main();
