# Auto-generated by a2p transpiler

def main():
    s = "Hello, Auto!"
    print(len(s))
    print(s[0])
    parts = s.split(", ")
    print(parts)
    upper = s.upper()
    print(upper)

if __name__ == "__main__":
    main()
