// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>

int main(void) {
    const char* s = "Hello, Auto!";
    printf("%zu\n", strlen(s));
    printf("%c\n", s[0]);

    // split by ", "
    const char* sep = ", ";
    char buf[256];
    strcpy(buf, s);
    char* token = strtok(buf, sep);
    printf("[");
    int first = 1;
    while (token != NULL) {
        if (!first) printf(", ");
        printf("\"%s\"", token);
        first = 0;
        token = strtok(NULL, sep);
    }
    printf("]\n");

    char upper[256];
    strcpy(upper, s);
    for (int i = 0; upper[i]; i++) {
        upper[i] = toupper((unsigned char)upper[i]);
    }
    printf("%s\n", upper);
    return 0;
}
