// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn validate(input: &str) -> Option<&str> {
    if !input.is_empty() {
        Some(input)
    } else {
        None
    }
}

fn uppercase(input: &str) -> String {
    input.to_uppercase()
}

fn main() {
    let input = "hello";
    if let Some(data) = validate(input) {
        let result = uppercase(data);
        println!("Result: {}", result);
    }
}
