// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn longest(a: String, b: String) -> String {
    if a.len() > b.len() {
        a
    } else {
        b
    }
}

fn main() {
    let result = longest(String::from("long string"), String::from("xyz"));
    println!("The longest string is {}", result);
}
