// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

typedef struct ResultFloat {
    bool is_ok;
    double ok_value;
    const char* err_value;
} ResultFloat;

ResultFloat divide(double a, double b) {
    ResultFloat r;
    if (b == 0.0) {
        r.is_ok = false;
        r.ok_value = 0.0;
        r.err_value = "division by zero";
    } else {
        r.is_ok = true;
        r.ok_value = a / b;
        r.err_value = NULL;
    }
    return r;
}

int main(void) {
    ResultFloat r1 = divide(10.0, 3.0);
    if (r1.is_ok) {
        printf("Result: %f\n", r1.ok_value);
    } else {
        printf("Error: %s\n", r1.err_value);
    }
    ResultFloat r2 = divide(10.0, 0.0);
    if (r2.is_ok) {
        printf("Result: %f\n", r2.ok_value);
    } else {
        printf("Error: %s\n", r2.err_value);
    }
    return 0;
}
