// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Result<T, E> {
    Ok(T),
    Err(E),
}

fn divide(a: f64, b: f64) -> Result<f64, String> {
    if b == 0.0 {
        Result::Err(String::from("division by zero"))
    } else {
        Result::Ok(a / b)
    }
}

fn main() {
    let r1 = divide(10.0, 3.0);
    match r1 {
        Result::Ok(v) => println!("Result: {}", v),
        Result::Err(e) => println!("Error: {}", e),
    }
    let r2 = divide(10.0, 0.0);
    match r2 {
        Result::Ok(v) => println!("Result: {}", v),
        Result::Err(e) => println!("Error: {}", e),
    }
}
