// Auto-generated by a2ts transpiler

type Result<T, E> =
    | { tag: "Ok"; value: T }
    | { tag: "Err"; value: E };

function divide(a: number, b: number): Result<number, string> {
    if (b === 0.0) {
        return { tag: "Err", value: "division by zero" };
    } else {
        return { tag: "Ok", value: a / b };
    }
}

function main(): void {
    const r1 = divide(10.0, 3.0);
    if (r1.tag === "Ok") {
        console.log("Result: " + r1.value);
    } else {
        console.log("Error: " + r1.value);
    }
    const r2 = divide(10.0, 0.0);
    if (r2.tag === "Ok") {
        console.log("Result: " + r2.value);
    } else {
        console.log("Error: " + r2.value);
    }
}

main();
