# Auto-generated by a2p transpiler

from typing import Union

def divide(a: float, b: float) -> Union[float, str]:
    if b == 0.0:
        return "division by zero"
    else:
        return a / b

def main():
    r1 = divide(10.0, 3.0)
    if isinstance(r1, float):
        print("Result: " + str(r1))
    else:
        print("Error: " + r1)
    r2 = divide(10.0, 0.0)
    if isinstance(r2, float):
        print("Result: " + str(r2))
    else:
        print("Error: " + r2)

if __name__ == "__main__":
    main()
