// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut x: i64 = 42;
    let p: *mut i64 = &mut x;
    println!("{}", unsafe { *p });    // 42
    unsafe { *p = 100; }
    println!("{}", x);     // 100
}
