// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    long long x = 42;
    long long* p = &x;
    printf("%lld\n", *p);    /* 42 */
    *p = 100;
    printf("%lld\n", x);     /* 100 */
    return 0;
}
