// Auto-generated by a2ts transpiler

function main(): void {
    let x: { value: number } = { value: 42 };
    let p: { value: number } = x;
    console.log(p.value);    // 42
    p.value = 100;
    console.log(x.value);     // 100
}

main();
