// Auto-generated by a2c transpiler

#include <stdio.h>

void classify(long long n) {
    if (n > 0) {
        printf("positive\n");
    } else if (n < 0) {
        printf("negative\n");
    } else {
        printf("zero\n");
    }
}

int main(void) {
    classify(5);
    classify(-3);
    classify(0);
    return 0;
}
