# Auto-generated by a2p transpiler

def classify(n):
    if n > 0:
        print("positive")
    elif n < 0:
        print("negative")
    else:
        print("zero")

def main():
    classify(5)
    classify(-3)
    classify(0)

if __name__ == "__main__":
    main()
