// Auto-generated by a2ts transpiler

function classify(n: number): void {
    if (n > 0) {
        console.log("positive");
    } else if (n < 0) {
        console.log("negative");
    } else {
        console.log("zero");
    }
}

function main(): void {
    classify(5);
    classify(-3);
    classify(0);
}

main();
