// Auto-generated by a2ts transpiler

function main(): void {
    let x = { value: 5 };
    let r1: { value: number } = x;    // OK -- one mutable reference
    // let r2: { value: number } = x;  // ERROR -- only one mutable ref (not enforced in TS)
    console.log(r1.value);
    console.log(x.value);
}

main();
