// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut x = 5;
    let r1: &mut i64 = &mut x;    // OK -- one mutable reference
    // let r2: &mut i64 = &mut x;  // ERROR -- only one mutable ref
    println!("{}", r1);
    println!("{}", x);
}
