// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    long long x = 5;
    long long* r1 = &x;    /* OK -- one mutable reference */
    /* long long* r2 = &x; */  /* ERROR -- only one mutable ref (not enforced in C) */
    printf("%lld\n", *r1);
    printf("%lld\n", x);
    return 0;
}
