# Auto-generated by a2p transpiler

def main():
    x = [5]
    r1 = x    # OK -- one mutable reference
    # r2 = x  # ERROR -- only one mutable ref (not enforced in Python)
    print(r1[0])
    print(x[0])

if __name__ == "__main__":
    main()
