// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    trpl::block_on(async {
        let (tx, mut rx) = trpl::channel();

        let tx_fut = async {
            let vals = vec![
                String::from("hello"),
                String::from("from"),
                String::from("the"),
                String::from("async"),
                String::from("channel"),
            ];
            for val in vals {
                tx.send(val).unwrap();
            }
        };

        let rx_fut = async {
            while let Some(received) = rx.recv().await {
                println!("Got: {}", received);
            }
        };

        trpl::join(tx_fut, rx_fut).await;
    })
}
