# Auto-generated by a2p transpiler

def main():
    x = 5           # stack
    s = "hello"     # stack (small string)
    list = [1, 2, 3] # heap (dynamic allocation)
    print(x)
    print(s)
    print(list)

if __name__ == "__main__":
    main()
