// Auto-generated by a2ts transpiler

function main(): void {
    const x: number = 5;           // stack
    const s: string = "hello";     // stack (small string)
    const list: number[] = [1, 2, 3]; // heap (dynamic allocation)
    console.log(x);
    console.log(s);
    console.log(list);
}

main();
