// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let x: i64 = 5;           // stack
    let s: String = String::from("hello");     // stack (small string)
    let list: Vec<i64> = vec![1, 2, 3]; // heap (dynamic allocation)
    println!("{}", x);
    println!("{}", s);
    println!("{:?}", list);
}
