// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    long long x = 5;           /* stack */
    const char* s = "hello";     /* stack (small string) */
    long long list[] = {1, 2, 3}; /* heap (dynamic allocation) */
    printf("%lld\n", x);
    printf("%s\n", s);
    printf("[%lld, %lld, %lld]\n", list[0], list[1], list[2]);
    return 0;
}
