// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Shape {
    Circle(f64),
    Rect(f64, f64),
}

fn area(s: Shape) -> f64 {
    match s {
        Shape::Circle(r) => 3.14159 * r * r,
        Shape::Rect(w, h) => w * h,
    }
}

fn main() {
    let mut c = Shape::Circle(5.0);
    println!("{}", area(c));
    let mut r = Shape::Rect(3.0, 4.0);
    println!("{}", area(r));
}
