# Auto-generated by a2p transpiler

from dataclasses import dataclass
from typing import Union

@dataclass
class Circle:
    radius: float

@dataclass
class Rect:
    width: float
    height: float

Shape = Union[Circle, Rect]

def area(s):
    if isinstance(s, Circle):
        return 3.14159 * s.radius * s.radius
    elif isinstance(s, Rect):
        return s.width * s.height

def main():
    c = Circle(radius=5.0)
    print(area(c))
    r = Rect(width=3.0, height=4.0)
    print(area(r))

if __name__ == "__main__":
    main()
