// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

typedef struct {
    double radius;
} ShapeCircle;

typedef struct {
    double width;
    double height;
} ShapeRect;

typedef enum {
    ShapeTag_Circle = 0,
    ShapeTag_Rect = 1,
} ShapeTag;

typedef struct {
    ShapeTag tag;
    union {
        ShapeCircle circle;
        ShapeRect rect;
    };
} Shape;

double area(Shape s) {
    switch (s.tag) {
        case ShapeTag_Circle:
            return 3.14159 * s.circle.radius * s.circle.radius;
        case ShapeTag_Rect:
            return s.rect.width * s.rect.height;
        default:
            return 0.0;
    }
}

int main(void) {
    Shape c = { .tag = ShapeTag_Circle, .circle = { .radius = 5.0 } };
    printf("%f\n", area(c));
    Shape r = { .tag = ShapeTag_Rect, .rect = { .width = 3.0, .height = 4.0 } };
    printf("%f\n", area(r));
    return 0;
}
