// Auto-generated by a2ts transpiler

class Circle {
    radius: number;
    constructor(radius: number) {
        this.radius = radius;
    }
}

class Rect {
    width: number;
    height: number;
    constructor(width: number, height: number) {
        this.width = width;
        this.height = height;
    }
}

type Shape = Circle | Rect;

function area(s: Shape): number {
    if (s instanceof Circle) {
        return 3.14159 * s.radius * s.radius;
    } else if (s instanceof Rect) {
        return s.width * s.height;
    }
    return 0;
}

function main(): void {
    let c: Shape = new Circle(5.0);
    console.log(area(c));
    let r: Shape = new Rect(3.0, 4.0);
    console.log(area(r));
}

main();
