// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Drawable {
    fn draw(&self);
}

struct Circle {
    radius: f64,
}

impl Circle {
    fn draw(&self) {
        println!("Drawing circle with radius {}", self.radius);
    }
}
