# Auto-generated by a2p transpiler

from abc import ABC, abstractmethod
from dataclasses import dataclass

class Drawable(ABC):
    @abstractmethod
    def draw(self):
        pass

@dataclass
class Circle:
    radius: float

    def draw(self):
        print(f"Drawing circle with radius {self.radius}")
