// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct {
    void (*draw)(const void*);
} DrawableVtable;

typedef struct {
    double radius;
    const DrawableVtable* vtable;
} Circle;

void Circle_draw(const void* self) {
    const Circle* c = (const Circle*)self;
    printf("Drawing circle with radius %f\n", c->radius);
}

static const DrawableVtable Circle_vtable = {
    .draw = Circle_draw,
};
