// Auto-generated by a2ts transpiler

interface Drawable {
    draw(): void;
}

class Circle implements Drawable {
    radius: number;

    constructor(radius: number) {
        this.radius = radius;
    }

    draw(): void {
        console.log(`Drawing circle with radius ${this.radius}`);
    }
}
