// Auto-generated by a2r transpiler

fn main() {

    let a: Vec<i64> = vec![1, 2, 3, 4, 5];
    let first: i64 = a[0].clone();
    let second: i64 = a[1].clone();
    println!("first = {}, second = {}", first, second);


    let b: Vec<i64> = vec![3, 3, 3, 3, 3];
    println!("b[0] = {}", b[0].clone());
}
