// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {

    let a: [i32; 5] = [1, 2, 3, 4, 5];
    let first: i32 = a[0];
    let second: i32 = a[1];
    println!("first = {}, second = {}", first, second);


    let b: [i32; 5] = [3, 3, 3, 3, 3];
    println!("b[0] = {}", b[0]);
}
