// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn maybe_value(x: i32) -> Option<i32> {
    if x > 0 {
        return Some(x);
    }
    return None;
}

fn main() {
    let result1 = maybe_value(10);
    let result2 = maybe_value(-5);
    println!("Done");
}
