// Auto-generated by a2r transpiler

fn maybe_value(x: i64) -> Option<i64> {
    if x > 0 {
        return Some(x);
    }
    return None;
}

fn main() {
    let result1 = maybe_value(10);
    let result2 = maybe_value(-5);
    println!("Done");
}
