// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let input: i32 = 42;
    let result = if input >= 0 {
        Some(input)
    } else {
        None
    };

    match result {
        Some(n) => println!("Valid guess: {}", n),
        None => println!("Invalid input"),
    }
}
