// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

void long_running_fn(char* result) {
    strcpy(result, "Done!");
}

int main(void) {
    char result[256];
    long_running_fn(result);
    printf("%s\n", result);
    return 0;
}
