// Auto-generated by a2ts transpiler

function longRunning(): Promise<string> {
    return new Promise((resolve) => {
        resolve("Done!");
    });
}

function main(): void {
    longRunning().then((result) => {
        console.log(result);
    });
}

main();
