// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

fn long_running(caller_tx: mpsc::Sender<String>) {
    let _ = caller_tx.send(String::from("Done!"));
}

fn main() {
    let (caller_tx, caller_rx) = mpsc::channel::<String>();

    std::thread::spawn(move || {
        long_running(caller_tx);
    });

    match caller_rx.recv() {
        Ok(result) => {
            println!("{}", result);
        }
        Err(_) => {}
    }
}
