# Auto-generated by a2p transpiler

import threading
import queue

def long_running(out_q):
    out_q.put("Done!")

def main():
    out_q = queue.Queue()
    t = threading.Thread(target=long_running, args=(out_q,))
    t.daemon = True
    t.start()
    try:
        result = out_q.get(timeout=2.0)
        print(result)
    except queue.Empty:
        pass
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
