// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

typedef enum JobKind {
    JobKind_Compute,
    JobKind_Done,
} JobKind;

typedef struct Job {
    JobKind kind;
    int value;
} Job;

void worker_fn(int id, Job job) {
    if (job.kind == JobKind_Compute) {
        printf("Worker %d computing %d\n", id, job.value);
    } else if (job.kind == JobKind_Done) {
        printf("Worker %d shutting down\n", id);
    }
}

int main(void) {
    worker_fn(1, (Job){ .kind = JobKind_Compute, .value = 42 });
    worker_fn(2, (Job){ .kind = JobKind_Compute, .value = 100 });
    worker_fn(3, (Job){ .kind = JobKind_Compute, .value = 7 });
    return 0;
}
