# Auto-generated by a2p transpiler

import threading
import queue
from enum import Enum

class JobType(Enum):
    Compute = 1
    Done = 2

class Job:
    def __init__(self, kind: JobType, value: int = 0):
        self.kind = kind
        self.value = value

def worker(id, q):
    while True:
        try:
            job = q.get(timeout=1.0)
            if job.kind == JobType.Compute:
                print("Worker " + str(id) + " computing " + str(job.value))
            elif job.kind == JobType.Done:
                print("Worker " + str(id) + " shutting down")
        except queue.Empty:
            break

def main():
    q1 = queue.Queue()
    q2 = queue.Queue()
    q3 = queue.Queue()
    t1 = threading.Thread(target=worker, args=(1, q1))
    t2 = threading.Thread(target=worker, args=(2, q2))
    t3 = threading.Thread(target=worker, args=(3, q3))
    t1.daemon = True
    t2.daemon = True
    t3.daemon = True
    t1.start()
    t2.start()
    t3.start()
    q1.put(Job(JobType.Compute, 42))
    q2.put(Job(JobType.Compute, 100))
    q3.put(Job(JobType.Compute, 7))
    t1.join(timeout=2.0)
    t2.join(timeout=2.0)
    t3.join(timeout=2.0)

if __name__ == "__main__":
    main()
