// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

enum Job {
    Compute(i64),
    Done,
}

fn worker(id: i64, rx: mpsc::Receiver<Job>) {
    for job in rx {
        match job {
            Job::Compute(n) => {
                println!("{}", "Worker ".to_string() + &id.to_string() + " computing " + &n.to_string());
            }
            Job::Done => {
                println!("{}", "Worker ".to_string() + &id.to_string() + " shutting down");
            }
        }
    }
}

fn main() {
    let (tx1, rx1) = mpsc::channel::<Job>();
    let (tx2, rx2) = mpsc::channel::<Job>();
    let (tx3, rx3) = mpsc::channel::<Job>();

    std::thread::spawn(move || { worker(1, rx1); });
    std::thread::spawn(move || { worker(2, rx2); });
    std::thread::spawn(move || { worker(3, rx3); });

    tx1.send(Job::Compute(42)).unwrap();
    tx2.send(Job::Compute(100)).unwrap();
    tx3.send(Job::Compute(7)).unwrap();
}
