// Auto-generated by a2ts transpiler

enum JobKind {
    Compute = "Compute",
    Done = "Done",
}

class Job {
    kind: JobKind;
    value: number;

    constructor(kind: JobKind, value: number = 0) {
        this.kind = kind;
        this.value = value;
    }
}

function worker(id: number, messages: Job[]): void {
    for (const job of messages) {
        switch (job.kind) {
            case JobKind.Compute:
                console.log("Worker " + id + " computing " + job.value);
                break;
            case JobKind.Done:
                console.log("Worker " + id + " shutting down");
                break;
        }
    }
}

function main(): void {
    worker(1, [new Job(JobKind.Compute, 42)]);
    worker(2, [new Job(JobKind.Compute, 100)]);
    worker(3, [new Job(JobKind.Compute, 7)]);
}

main();
