// Auto-generated by a2r transpiler

fn give_ownership() -> String {
    let s: String = String::from("yours");
    s
}

fn take_and_give_back(s: String) -> String {
    s
}

fn main() {
    let mut s1 = give_ownership();
    println!("s1 = {}", s1);

    let s2: String = String::from("hello");
    let mut s3 = take_and_give_back(s2.clone());
    println!("s3 = {}", s3);
}
