// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn give_ownership() -> String {
    let s: String = String::from("yours");
    s
}

fn take_and_give_back(s: String) -> String {
    s
}

fn main() {
    let s1 = give_ownership();
    println!("s1 = {}", s1);

    let s2: String = String::from("hello");
    let s3 = take_and_give_back(s2);
    println!("s3 = {}", s3);
}
