// Auto-generated by a2ts transpiler

function main(): void {
    const result = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        .filter((x: number) => x % 2 === 0)
        .map((x: number) => x * x)
        .reduce((acc: number, x: number) => acc + x, 0);
    console.log(result);
}

main();
