// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

int main(void) {
    int numbers[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    int len = 10;
    int result = 0;
    for (int i = 0; i < len; i++) {
        if (numbers[i] % 2 == 0) {
            result = result + numbers[i] * numbers[i];
        }
    }
    printf("%d\n", result);
    return 0;
}
