# Auto-generated by a2p transpiler

from functools import reduce

def main():
    numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    evens = [x for x in numbers if x % 2 == 0]
    squared = [x * x for x in evens]
    result = reduce(lambda acc, x: acc + x, squared, 0)
    print(result)

if __name__ == "__main__":
    main()
