// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let result: i32 = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        .iter()
        .filter(|x: &i32| x % 2 == 0)
        .map(|x: &i32| x * x)
        .fold(0, |acc: i32, x: &i32| acc + x);
    println!("{}", result);
}
