// Auto-generated by a2ts transpiler

function fetchUser(id: number): Promise<string> {
    return new Promise((resolve) => {
        resolve("User" + id);
    });
}

function fetchPosts(user: string): Promise<string> {
    return new Promise((resolve) => {
        resolve("Posts for " + user);
    });
}

async function main(): Promise<void> {
    const u = await fetchUser(1);
    const p = await fetchPosts(u);
    console.log("User: " + u);
    console.log("Posts: " + p);
}

main();
