# Auto-generated by a2p transpiler

import threading
import queue

def fetch_user(id, out_q):
    out_q.put("User" + str(id))

def fetch_posts(user, out_q):
    out_q.put("Posts for " + user)

def main():
    user_q = queue.Queue()
    t1 = threading.Thread(target=fetch_user, args=(1, user_q))
    t1.daemon = True
    t1.start()

    try:
        u = user_q.get(timeout=2.0)
    except queue.Empty:
        u = ""

    posts_q = queue.Queue()
    t2 = threading.Thread(target=fetch_posts, args=(u, posts_q))
    t2.daemon = True
    t2.start()

    try:
        p = posts_q.get(timeout=2.0)
        print("User: " + u)
        print("Posts: " + p)
    except queue.Empty:
        pass

    t1.join(timeout=2.0)
    t2.join(timeout=2.0)

if __name__ == "__main__":
    main()
