// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

void fetch_user_fn(int id, char* result) {
    sprintf(result, "User%d", id);
}

void fetch_posts_fn(const char* user, char* result) {
    sprintf(result, "Posts for %s", user);
}

int main(void) {
    char u[256];
    char p[256];
    fetch_user_fn(1, u);
    fetch_posts_fn(u, p);
    printf("User: %s\n", u);
    printf("Posts: %s\n", p);
    return 0;
}
