// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

fn fetch_user(id: i64, caller_tx: mpsc::Sender<String>) {
    let _ = caller_tx.send("User".to_string() + &id.to_string());
}

fn fetch_posts(user: String, caller_tx: mpsc::Sender<String>) {
    let _ = caller_tx.send("Posts for ".to_string() + &user);
}

fn main() {
    let (user_tx, user_rx) = mpsc::channel::<String>();

    std::thread::spawn(move || {
        fetch_user(1, user_tx);
    });

    match user_rx.recv() {
        Ok(u) => {
            let (posts_tx, posts_rx) = mpsc::channel::<String>();

            std::thread::spawn(move || {
                fetch_posts(u.clone(), posts_tx);
            });

            match posts_rx.recv() {
                Ok(p) => {
                    println!("{}", "User: ".to_string() + &u);
                    println!("{}", "Posts: ".to_string() + &p);
                }
                Err(_) => {}
            }
        }
        Err(_) => {}
    }
}
