// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef struct Config {
    const char* input_path;
    const char* output_path;
    bool verbose;
} Config;

typedef struct ResultInt {
    bool is_ok;
    long long ok_value;
    const char* err_value;
} ResultInt;

ResultInt read_file(const char* path) {
    ResultInt r;
    r.is_ok = false;
    r.ok_value = 0;
    r.err_value = NULL;
    return r;
}

const char* get_file_content(void) {
    return "line1\nline2\nhello world\nline3\nhello auto";
}

ResultInt process(Config config) {
    const char* content = get_file_content();
    char lines[16][256];
    int line_count = 0;
    char buf[1024];
    strncpy(buf, content, sizeof(buf) - 1);
    buf[sizeof(buf) - 1] = '\0';

    char* token = strtok(buf, "\n");
    while (token != NULL && line_count < 16) {
        strncpy(lines[line_count], token, 255);
        lines[line_count][255] = '\0';
        line_count++;
        token = strtok(NULL, "\n");
    }

    long long count = 0;
    for (int i = 0; i < line_count; i++) {
        if (strstr(lines[i], "hello") != NULL) {
            count = count + 1;
            if (config.verbose) {
                printf("Found: %s\n", lines[i]);
            }
        }
    }

    ResultInt r;
    r.is_ok = true;
    r.ok_value = count;
    r.err_value = NULL;
    return r;
}

int main(void) {
    Config config = { .input_path = "data.txt", .output_path = "result.txt", .verbose = true };
    ResultInt matches = process(config);
    if (!matches.is_ok) {
        fprintf(stderr, "Error: %s\n", matches.err_value);
        return 1;
    }
    printf("Found %lld matches\n", matches.ok_value);
    return 0;
}
