# Auto-generated by a2p transpiler

class Config:
    def __init__(self, input_path: str, output_path: str, verbose: bool):
        self.input_path = input_path
        self.output_path = output_path
        self.verbose = verbose

def read_file(path: str) -> str:
    return "line1\nline2\nhello world\nline3\nhello auto"

def process(config: Config) -> int:
    content = read_file(config.input_path)
    lines = content.split("\n")
    count = 0
    for line in lines:
        if "hello" in line:
            count = count + 1
            if config.verbose:
                print("Found: " + line)
    return count

def main():
    config = Config(input_path="data.txt", output_path="result.txt", verbose=True)
    matches = process(config)
    print("Found " + str(matches) + " matches")

if __name__ == "__main__":
    main()
