// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone)]
struct Config {
    input_path: String,
    output_path: String,
    verbose: bool,
}

fn read_file(path: &str) -> Result<String, String> {
    Ok(String::from("line1\nline2\nhello world\nline3\nhello auto"))
}

fn process(config: &Config) -> Result<i64, String> {
    let content = read_file(&config.input_path)?;
    let lines: Vec<String> = content.split('\n').map(|s| String::from(s)).collect();
    let mut count: i64 = 0;
    for line in &lines {
        if line.contains("hello") {
            count = count + 1;
            if config.verbose {
                println!("{}", "Found: ".to_string() + line);
            }
        }
    }
    Ok(count)
}

fn main() -> Result<(), String> {
    let config = Config { input_path: String::from("data.txt"), output_path: String::from("result.txt"), verbose: true };
    let matches = process(&config)?;
    println!("{}", "Found ".to_string() + &matches.to_string() + " matches");
    Ok(())
}
