// Auto-generated by a2ts transpiler

class Config {
    input_path: string;
    output_path: string;
    verbose: boolean;

    constructor(input_path: string, output_path: string, verbose: boolean) {
        this.input_path = input_path;
        this.output_path = output_path;
        this.verbose = verbose;
    }
}

function readFile(path: string): string {
    return "line1\nline2\nhello world\nline3\nhello auto";
}

function process(config: Config): number {
    const content = readFile(config.input_path);
    const lines = content.split("\n");
    let count = 0;
    for (const line of lines) {
        if (line.includes("hello")) {
            count = count + 1;
            if (config.verbose) {
                console.log("Found: " + line);
            }
        }
    }
    return count;
}

function main(): void {
    const config = new Config("data.txt", "result.txt", true);
    const matches = process(config);
    console.log("Found " + matches + " matches");
}

main();
