# Auto-generated by a2p transpiler

def parse_int(s: str) -> int:
    # returns int on success, error on failure
    return 42  # simplified for example

def main():
    result = parse_int("42")
    print(result)

if __name__ == "__main__":
    main()
