// Auto-generated by a2ts transpiler

function parseInt(s: string): number {
    // returns int on success, error on failure
    return 42; // simplified for example
}

function main(): void {
    const result = parseInt("42");
    console.log(result);
}

main();
