// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn parse_int(s: String) -> Result<i64, String> {
    // returns int on success, error on failure
    Ok(42) // simplified for example
}

fn main() {
    let mut result = parse_int(String::from("42")).unwrap();
    println!("{}", result);
}
