// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    long long value;
    int _ok;
    char error[256];
} IntResult;

IntResult parse_int(const char* s) {
    // returns int on success, error on failure
    IntResult r;
    r.value = 42; // simplified for example
    r._ok = 1;
    return r;
}

int main(void) {
    IntResult result = parse_int("42");
    if (result._ok) {
        printf("%lld\n", result.value);
    } else {
        printf("Error: %s\n", result.error);
    }
    return 0;
}
