// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn search_lines<T: Clone>(lines: Vec<String>, predicate: fn(&String) -> Option<T>) -> Vec<T> {
    let mut results: Vec<T> = Vec::new();
    for line in &lines {
        let result = predicate(line);
        if let Some(val) = result {
            results.push(val);
        }
    }
    results
}

fn main() {
    let lines = vec![String::from("hello world"), String::from("foo bar"), String::from("hello auto")];
    let found = search_lines(lines, |s: &String| -> Option<String> {
        if s.contains("hello") {
            Some(s.clone())
        } else {
            None
        }
    });
    for f in &found {
        println!("{}", f);
    }
}
