# Auto-generated by a2p transpiler

from typing import TypeVar, List, Callable, Optional

T = TypeVar('T')

def search_lines(lines: List[str], predicate: Callable[[str], Optional[T]]) -> List[T]:
    results: List[T] = []
    for line in lines:
        result = predicate(line)
        if result is not None:
            results.append(result)
    return results

def main():
    lines = ["hello world", "foo bar", "hello auto"]
    found = search_lines(lines, lambda s: s if "hello" in s else None)
    for f in found:
        print(f)

if __name__ == "__main__":
    main()
