// Auto-generated by a2ts transpiler

function searchLines<T>(lines: string[], predicate: (s: string) => T | null): T[] {
    const results: T[] = [];
    for (const line of lines) {
        const result = predicate(line);
        if (result !== null) {
            results.push(result);
        }
    }
    return results;
}

function main(): void {
    const lines = ["hello world", "foo bar", "hello auto"];
    const found = searchLines<string>(lines, (s: string): string | null => {
        if (s.includes("hello")) {
            return s;
        } else {
            return null;
        }
    });
    for (const f of found) {
        console.log(f);
    }
}

main();
