// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>
#include <stdbool.h>

typedef struct OptionStr {
    bool is_some;
    const char* some_value;
} OptionStr;

typedef struct StrVec {
    const char** data;
    int len;
    int cap;
} StrVec;

void strvec_push(StrVec* vec, const char* value) {
    if (vec->len < vec->cap) {
        vec->data[vec->len] = value;
        vec->len++;
    }
}

typedef struct OptionStrVec {
    bool is_some;
    OptionStr some_value;
} OptionStrVec;

typedef struct FoundVec {
    OptionStr* data;
    int len;
    int cap;
} FoundVec;

void foundvec_push(FoundVec* vec, OptionStr value) {
    if (vec->len < vec->cap) {
        vec->data[vec->len] = value;
        vec->len++;
    }
}

OptionStr find_predicate(const char* s) {
    OptionStr result;
    if (strstr(s, "hello") != NULL) {
        result.is_some = true;
        result.some_value = s;
    } else {
        result.is_some = false;
        result.some_value = NULL;
    }
    return result;
}

int main(void) {
    const char* lines[] = {"hello world", "foo bar", "hello auto"};
    int lines_len = 3;

    OptionStr found_data[3] = {0};
    FoundVec found = { .data = found_data, .len = 0, .cap = 3 };

    for (int i = 0; i < lines_len; i++) {
        OptionStr result = find_predicate(lines[i]);
        if (result.is_some) {
            foundvec_push(&found, result);
        }
    }

    for (int i = 0; i < found.len; i++) {
        printf("%s\n", found.data[i].some_value);
    }

    return 0;
}
