// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut greeting: String = String::from("Hello");
    let mut name: String = String::from("Auto");
    let mut message: String = format!("{}, {}!", greeting, name);
    println!("{}", message);
    let mut multi: String = String::from("This is a\nmultiline string");
    println!("{}", multi);
}
