// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    const char* greeting = "Hello";
    const char* name = "Auto";
    char message[256];
    snprintf(message, sizeof(message), "%s, %s!", greeting, name);
    printf("%s\n", message);
    const char* multi = "This is a\nmultiline string";
    printf("%s\n", multi);
    return 0;
}
