// Auto-generated by a2ts transpiler

function main(): void {
    let greeting: string = "Hello";
    let name: string = "Auto";
    let message: string = greeting + ", " + name + "!";
    console.log(message);
    let multi: string = `This is a
multiline string`;
    console.log(multi);
}

main();
