# Auto-generated by a2p transpiler

def main():
    greeting = "Hello"
    name = "Auto"
    message = greeting + ", " + name + "!"
    print(message)
    multi = """This is a
multiline string"""
    print(multi)

if __name__ == "__main__":
    main()
