// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let a: [i32; 5] = [1, 2, 3, 4, 5];
    let slice: i32 = a[1..3];
    println!("slice = {}", slice);
}
