// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn take_ownership(s: String) {
    println!("took ownership of: {}", s);
}

fn main() {
    let s: String = String::from("hello");
    take_ownership(s);


    let x: i32 = 5;
    make_copy(x);

}

fn make_copy(i: i32) {
    println!("made copy of: {}", i);
}
