// Auto-generated by a2r transpiler

fn take_ownership(s: String) {
    println!("took ownership of: {}", s);
}

fn main() {
    let s: String = String::from("hello");
    take_ownership(s.clone());


    let x: i64 = 5;
    make_copy(x);

}

fn make_copy(i: i64) {
    println!("made copy of: {}", i);
}
