// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut pair: (i64, String) = (1, String::from("hello"));
    println!("{}", pair.0);
    println!("{}", pair.1);
    let (a, b) = pair;
    println!("{}", a);
    println!("{}", b);
}
