// Auto-generated by a2ts transpiler

function main(): void {
    let pair: [number, string] = [1, "hello"];
    console.log(pair[0]);
    console.log(pair[1]);
    let [a, b]: [number, string] = pair;
    console.log(a);
    console.log(b);
}

main();
