// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct {
    long long _0;
    const char* _1;
} Tuple2;

int main(void) {
    Tuple2 pair = {1, "hello"};
    printf("%lld\n", pair._0);
    printf("%s\n", pair._1);
    long long a = pair._0;
    const char* b = pair._1;
    printf("%lld\n", a);
    printf("%s\n", b);
    return 0;
}
