// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use std::fs::read_to_string;
fn main() {
    println!("File reading example");
}
