// Auto-generated by a2ts transpiler

enum WorkResultKind {
    Success = "Success",
    Error = "Error",
}

class WorkResult {
    kind: WorkResultKind;
    value: string;

    constructor(kind: WorkResultKind, value: string) {
        this.kind = kind;
        this.value = value;
    }
}

function processData(data: string): WorkResult {
    if (data.length > 0) {
        return new WorkResult(WorkResultKind.Success, "Processed: " + data);
    } else {
        return new WorkResult(WorkResultKind.Error, "Empty data");
    }
}

function main(): void {
    const result1 = processData("hello world");
    if (result1.kind === WorkResultKind.Success) {
        console.log(result1.value);
    } else if (result1.kind === WorkResultKind.Error) {
        console.log("Error: " + result1.value);
    }

    const result2 = processData("");
    if (result2.kind === WorkResultKind.Success) {
        console.log(result2.value);
    } else if (result2.kind === WorkResultKind.Error) {
        console.log("Error: " + result2.value);
    }
}

main();
