# Auto-generated by a2p transpiler

import threading
import queue
from enum import Enum

class WorkResultKind(Enum):
    Success = 1
    Error = 2

class WorkResult:
    def __init__(self, kind: WorkResultKind, value: str):
        self.kind = kind
        self.value = value

def processor(in_q, out_q):
    while True:
        try:
            data = in_q.get(timeout=1.0)
            if len(data) > 0:
                out_q.put(WorkResult(WorkResultKind.Success, "Processed: " + data))
            else:
                out_q.put(WorkResult(WorkResultKind.Error, "Empty data"))
        except queue.Empty:
            break

def main():
    in_q = queue.Queue()
    out_q = queue.Queue()
    t = threading.Thread(target=processor, args=(in_q, out_q))
    t.daemon = True
    t.start()
    in_q.put("hello world")
    in_q.put("")
    result = out_q.get(timeout=2.0)
    if result.kind == WorkResultKind.Success:
        print(result.value)
    elif result.kind == WorkResultKind.Error:
        print("Error: " + result.value)
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
