// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef enum WorkResultKind {
    WorkResultKind_Success,
    WorkResultKind_Error,
} WorkResultKind;

typedef struct WorkResult {
    WorkResultKind kind;
    const char* value;
} WorkResult;

void process_data(const char* data, WorkResult* result) {
    if (strlen(data) > 0) {
        char buf[256];
        snprintf(buf, sizeof(buf), "Processed: %s", data);
        result->kind = WorkResultKind_Success;
        result->value = buf;
    } else {
        result->kind = WorkResultKind_Error;
        result->value = "Empty data";
    }
}

int main(void) {
    WorkResult result1, result2;

    process_data("hello world", &result1);
    process_data("", &result2);

    if (result1.kind == WorkResultKind_Success) {
        printf("%s\n", result1.value);
    } else if (result1.kind == WorkResultKind_Error) {
        printf("Error: %s\n", result1.value);
    }

    if (result2.kind == WorkResultKind_Success) {
        printf("%s\n", result2.value);
    } else if (result2.kind == WorkResultKind_Error) {
        printf("Error: %s\n", result2.value);
    }

    return 0;
}
