// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

enum WorkResult {
    Success(String),
    Error(String),
}

fn processor(rx: mpsc::Receiver<String>, main_tx: mpsc::Sender<WorkResult>) {
    for data in rx {
        if data.len() > 0 {
            let _ = main_tx.send(WorkResult::Success("Processed: ".to_string() + &data));
        } else {
            let _ = main_tx.send(WorkResult::Error(String::from("Empty data")));
        }
    }
}

fn main() {
    let (proc_tx, proc_rx) = mpsc::channel::<String>();
    let (main_tx, main_rx) = mpsc::channel::<WorkResult>();

    std::thread::spawn(move || {
        processor(proc_rx, main_tx);
    });

    proc_tx.send(String::from("hello world")).unwrap();
    proc_tx.send(String::from("")).unwrap();

    match main_rx.recv() {
        Ok(result) => {
            match result {
                WorkResult::Success(msg) => println!("{}", msg),
                WorkResult::Error(e) => println!("{}", "Error: ".to_string() + &e),
            }
        }
        Err(_) => {}
    }
}
