// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

mod server {
    pub fn start(port: i64) {
        println!("Server started on port {}", port);
    }
}

mod client {
    pub fn connect(host: String) {
        println!("Connecting to {}", host);
    }
}

fn main() {
    server::start(8080);
    client::connect(String::from("localhost"));
}
