// Auto-generated by a2ts transpiler

function serverStart(port: number): void {
    console.log(`Server started on port ${port}`);
}

function clientConnect(host: string): void {
    console.log(`Connecting to ${host}`);
}

function main(): void {
    serverStart(8080);
    clientConnect("localhost");
}

main();
