# Auto-generated by a2p transpiler

def server_start(port: int) -> None:
    print(f"Server started on port {port}")

def client_connect(host: str) -> None:
    print(f"Connecting to {host}")

def main():
    server_start(8080)
    client_connect("localhost")

if __name__ == "__main__":
    main()
