// Auto-generated by a2c transpiler

#include <stdio.h>

void server_start(long long port) {
    printf("Server started on port %lld\n", port);
}

void client_connect(const char* host) {
    printf("Connecting to %s\n", host);
}

int main(void) {
    server_start(8080);
    client_connect("localhost");
    return 0;
}
