# Auto-generated by a2p transpiler

import threading
import queue
from dataclasses import dataclass

class MessageKind:
    Connect = "Connect"
    Disconnect = "Disconnect"
    Chat = "Chat"
    PrivateMsg = "PrivateMsg"
    System = "System"
    JoinRoom = "JoinRoom"
    LeaveRoom = "LeaveRoom"
    RoomMsg = "RoomMsg"

@dataclass
class Message:
    kind: str
    field1: str = ""
    field2: str = ""
    field3: str = ""

def broadcast(clients, rooms, msg):
    print(f"[broadcast] {len(clients)} clients")

def broadcast_room(rooms, room_name, msg):
    members = rooms.get(room_name, [])
    print(f"[#{room_name}] delivered to {len(members)}")

def server(in_q, out_q):
    clients = {}
    rooms = {"general": [], "random": []}
    while True:
        try:
            msg = in_q.get(timeout=1.0)
            if msg.kind == MessageKind.Connect:
                name = msg.field1
                if name in clients:
                    out_q.put(Message(kind=MessageKind.System, field1=f"Name already taken: {name}"))
                else:
                    clients[name] = 1
                    rooms["general"].append(name)
                    out_q.put(Message(kind=MessageKind.System, field1=f"Welcome, {name}!"))
                    out_q.put(Message(kind=MessageKind.System, field1=f"{name} joined. Online: {len(clients)}"))
            elif msg.kind == MessageKind.Disconnect:
                name = msg.field1
                clients.pop(name, None)
                for members in rooms.values():
                    if name in members:
                        members.remove(name)
                out_q.put(Message(kind=MessageKind.System, field1=f"{name} left. Online: {len(clients)}"))
            elif msg.kind == MessageKind.Chat:
                broadcast(clients, rooms, msg)
            elif msg.kind == MessageKind.PrivateMsg:
                if msg.field2 in clients:
                    print(f"[PM] {msg.field1} -> {msg.field2}: {msg.field3}")
                else:
                    print(f"[SYS] User {msg.field2} not found")
            elif msg.kind == MessageKind.JoinRoom:
                name, room_name = msg.field1, msg.field2
                if room_name in rooms:
                    rooms[room_name].append(name)
                    broadcast_room(rooms, room_name, Message(kind=MessageKind.System, field1=f"{name} joined #{room_name}"))
            elif msg.kind == MessageKind.LeaveRoom:
                name, room_name = msg.field1, msg.field2
                if name in rooms.get(room_name, []):
                    rooms[room_name].remove(name)
                broadcast_room(rooms, room_name, Message(kind=MessageKind.System, field1=f"{name} left #{room_name}"))
            elif msg.kind == MessageKind.RoomMsg:
                broadcast_room(rooms, msg.field1, msg)
            elif msg.kind == MessageKind.System:
                print(f"[SYS] {msg.field1}")
        except queue.Empty:
            break

def client_handler(name, server_q):
    print(f"Welcome, {name}! Commands: /msg, /join, /leave, /rooms, /quit")
    inputs = ["Hello everyone!", "/join random", "/rooms", "/quit"]
    for inp in inputs:
        if inp == "/quit":
            print(f"Goodbye, {name}!")
            return
        elif inp.startswith("/msg "):
            parts = inp.split(" ")
            if len(parts) >= 3:
                target = parts[1]
                text = " ".join(parts[2:])
                print(f"[PM] {name} -> {target}: {text}")
        elif inp.startswith("/join "):
            room_name = inp.split(" ")[1]
            print(f"[SYS] {name} joined #{room_name}")
        elif inp.startswith("/leave "):
            room_name = inp.split(" ")[1]
            print(f"[SYS] {name} left #{room_name}")
        elif inp == "/rooms":
            print("[SYS] Available rooms: general, random")
        elif len(inp) > 0:
            print(f"{name}: {inp}")

def main():
    port = 8080
    print("=== AutoChat Server v1.0 ===")
    print(f"Starting on port {port}...")
    server_in = queue.Queue()
    server_out = queue.Queue()
    t_server = threading.Thread(target=server, args=(server_in, server_out))
    t_server.daemon = True
    t_server.start()
    t1 = threading.Thread(target=client_handler, args=("Alice", server_in))
    t2 = threading.Thread(target=client_handler, args=("Bob", server_in))
    t1.daemon = True
    t2.daemon = True
    t1.start()
    t2.start()
    print("Server running. Press Ctrl+C to stop.")
    t1.join(timeout=2.0)
    t2.join(timeout=2.0)
    t_server.join(timeout=2.0)

if __name__ == "__main__":
    main()
