// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <pthread.h>

#define MAX_CLIENTS 64
#define MAX_ROOM_MEMBERS 64
#define MAX_ROOMS 8
#define MAX_NAME 64
#define MAX_FIELD 256

typedef enum MessageKind {
    MsgKind_Connect,
    MsgKind_Disconnect,
    MsgKind_Chat,
    MsgKind_PrivateMsg,
    MsgKind_System,
    MsgKind_JoinRoom,
    MsgKind_LeaveRoom,
    MsgKind_RoomMsg,
} MessageKind;

typedef struct Message {
    MessageKind kind;
    char field1[MAX_FIELD];
    char field2[MAX_FIELD];
    char field3[MAX_FIELD];
} Message;

typedef struct {
    char name[MAX_NAME];
    char members[MAX_ROOM_MEMBERS][MAX_NAME];
    int member_count;
} Room;

static Room rooms[MAX_ROOMS];
static int room_count = 0;
static int client_count = 0;
static pthread_mutex_t server_lock = PTHREAD_MUTEX_INITIALIZER;

Room* find_room(const char* name) {
    for (int i = 0; i < room_count; i++) {
        if (strcmp(rooms[i].name, name) == 0) return &rooms[i];
    }
    return NULL;
}

void add_room(const char* name) {
    strncpy(rooms[room_count].name, name, MAX_NAME - 1);
    rooms[room_count].member_count = 0;
    room_count++;
}

void broadcast(int count) {
    printf("[broadcast] %d clients\n", count);
}

void broadcast_room(const char* room_name, int count) {
    printf("[#%s] delivered to %d\n", room_name, count);
}

void* client_handler(void* arg) {
    const char* name = (const char*)arg;
    printf("Welcome, %s! Commands: /msg, /join, /leave, /rooms, /quit\n", name);

    const char* inputs[] = {
        "Hello everyone!",
        "/join random",
        "/rooms",
        "/quit"
    };

    for (int i = 0; i < 4; i++) {
        const char* input = inputs[i];
        if (strcmp(input, "/quit") == 0) {
            printf("Goodbye, %s!\n", name);
            return NULL;
        } else if (strncmp(input, "/msg ", 5) == 0) {
            char buf[MAX_FIELD];
            strncpy(buf, input, MAX_FIELD - 1);
            char* parts[4];
            int count = 0;
            char* tok = strtok(buf, " ");
            while (tok != NULL && count < 4) {
                parts[count++] = tok;
                tok = strtok(NULL, " ");
            }
            if (count >= 3) {
                printf("[PM] %s -> %s: %s\n", name, parts[1], parts[2]);
            }
        } else if (strncmp(input, "/join ", 6) == 0) {
            char room_name[MAX_NAME];
            sscanf(input + 6, "%s", room_name);
            printf("[SYS] %s joined #%s\n", name, room_name);
        } else if (strncmp(input, "/leave ", 7) == 0) {
            char room_name[MAX_NAME];
            sscanf(input + 7, "%s", room_name);
            printf("[SYS] %s left #%s\n", name, room_name);
        } else if (strcmp(input, "/rooms") == 0) {
            printf("[SYS] Available rooms: general, random\n");
        } else if (strlen(input) > 0) {
            printf("%s: %s\n", name, input);
        }
    }
    return NULL;
}

int main(void) {
    int port = 8080;
    printf("=== AutoChat Server v1.0 ===\n");
    printf("Starting on port %d...\n", port);
    add_room("general");
    add_room("random");

    pthread_t thread1, thread2;
    static char name1[] = "Alice";
    static char name2[] = "Bob";
    pthread_create(&thread1, NULL, client_handler, name1);
    pthread_create(&thread2, NULL, client_handler, name2);
    pthread_join(thread1, NULL);
    pthread_join(thread2, NULL);

    printf("Server running. Press Ctrl+C to stop.\n");
    return 0;
}
