// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;
use std::collections::HashMap;

enum Message {
    Connect(String),
    Disconnect(String),
    Chat(String, String),
    PrivateMsg(String, String, String),
    System(String),
    JoinRoom(String, String),
    LeaveRoom(String, String),
    RoomMsg(String, String, String),
}

fn broadcast(clients: &HashMap<String, i64>, _rooms: &HashMap<String, Vec<String>>, msg: &Message) {
    println!("[broadcast] {} clients", clients.len());
}

fn broadcast_room(rooms: &HashMap<String, Vec<String>>, room_name: &str, _msg: &Message) {
    let members = rooms.get(room_name).map(|m| m.len()).unwrap_or(0);
    println!("[#{}] delivered to {}", room_name, members);
}

fn server(rx: mpsc::Receiver<Message>, main_tx: mpsc::Sender<Message>) {
    let mut clients: HashMap<String, i64> = HashMap::new();
    let mut rooms: HashMap<String, Vec<String>> = HashMap::new();
    rooms.insert(String::from("general"), Vec::new());
    rooms.insert(String::from("random"), Vec::new());
    for msg in rx {
        match msg {
            Message::Connect(name) => {
                if clients.contains_key(&name) {
                    let _ = main_tx.send(Message::System(format!("Name already taken: {}", name)));
                } else {
                    clients.insert(name.clone(), 1);
                    rooms.get_mut("general").unwrap().push(name.clone());
                    let _ = main_tx.send(Message::System(format!("Welcome, {}!", name)));
                    let _ = main_tx.send(Message::System(format!("{} joined. Online: {}", name, clients.len())));
                }
            }
            Message::Disconnect(name) => {
                clients.remove(&name);
                for (_room_name, members) in rooms.iter_mut() {
                    members.retain(|m| m != &name);
                }
                let _ = main_tx.send(Message::System(format!("{} left. Online: {}", name, clients.len())));
            }
            Message::Chat(from, text) => {
                broadcast(&clients, &rooms, &Message::Chat(from.clone(), text.clone()));
            }
            Message::PrivateMsg(from, to, text) => {
                if clients.contains_key(&to) {
                    println!("[PM] {} -> {}: {}", from, to, text);
                } else {
                    println!("[SYS] User {} not found", to);
                }
            }
            Message::JoinRoom(name, room_name) => {
                if let Some(members) = rooms.get_mut(&room_name) {
                    members.push(name.clone());
                    broadcast_room(&rooms, &room_name, &Message::System(format!("{} joined #{}", name, room_name)));
                } else {
                    println!("[SYS] Room #{} does not exist", room_name);
                }
            }
            Message::LeaveRoom(name, room_name) => {
                if let Some(members) = rooms.get_mut(&room_name) {
                    members.retain(|m| m != &name);
                }
                broadcast_room(&rooms, &room_name, &Message::System(format!("{} left #{}", name, room_name)));
            }
            Message::RoomMsg(room_name, from, text) => {
                broadcast_room(&rooms, &room_name, &Message::RoomMsg(room_name.clone(), from.clone(), text.clone()));
            }
            Message::System(text) => {
                println!("[SYS] {}", text);
            }
        }
    }
}

fn client_handler(name: String) {
    println!("Welcome, {}! Commands: /msg, /join, /leave, /rooms, /quit", name);
    // Simulated input processing
    let inputs = vec![
        String::from("Hello everyone!"),
        String::from("/join random"),
        String::from("/rooms"),
        String::from("/quit"),
    ];
    for input in inputs {
        if input == "/quit" {
            println!("Goodbye, {}!", name);
            return;
        } else if input.starts_with("/msg ") {
            let parts: Vec<&str> = input.split_whitespace().collect();
            if parts.len() >= 3 {
                let target = parts[1];
                let text = parts[2..].join(" ");
                println!("[PM] {} -> {}: {}", name, target, text);
            }
        } else if input.starts_with("/join ") {
            let room_name = input.split_whitespace().nth(1).unwrap_or("");
            println!("[SYS] {} joined #{}", name, room_name);
        } else if input.starts_with("/leave ") {
            let room_name = input.split_whitespace().nth(1).unwrap_or("");
            println!("[SYS] {} left #{}", name, room_name);
        } else if input == "/rooms" {
            println!("[SYS] Available rooms: general, random");
        } else if input.len() > 0 {
            println!("{}: {}", name, input);
        }
    }
}

fn main() {
    let port: i64 = 8080;
    println!("=== AutoChat Server v1.0 ===");
    println!("Starting on port {}...", port);
    let (tx, rx) = mpsc::channel::<Message>();
    let (main_tx, main_rx) = mpsc::channel::<Message>();
    std::thread::spawn(move || {
        server(rx, main_tx);
    });
    let tx1 = tx.clone();
    let tx2 = tx.clone();
    std::thread::spawn(move || {
        client_handler(String::from("Alice"));
    });
    std::thread::spawn(move || {
        client_handler(String::from("Bob"));
    });
    println!("Server running. Press Ctrl+C to stop.");
}
