// Auto-generated by a2ts transpiler

type Message =
    | { kind: "Connect"; field1: string }
    | { kind: "Disconnect"; field1: string }
    | { kind: "Chat"; field1: string; field2: string }
    | { kind: "PrivateMsg"; field1: string; field2: string; field3: string }
    | { kind: "System"; field1: string }
    | { kind: "JoinRoom"; field1: string; field2: string }
    | { kind: "LeaveRoom"; field1: string; field2: string }
    | { kind: "RoomMsg"; field1: string; field2: string; field3: string };

const clients = new Map<string, number>();
const rooms = new Map<string, string[]>();
rooms.set("general", []);
rooms.set("random", []);

function broadcast(msg: Message): void {
    console.log(`[broadcast] ${clients.size} clients`);
}

function broadcastRoom(roomName: string, msg: Message): void {
    const members = rooms.get(roomName) || [];
    console.log(`[#${roomName}] delivered to ${members.length}`);
}

function server(messages: Message[]): void {
    for (const msg of messages) {
        switch (msg.kind) {
            case "Connect": {
                if (clients.has(msg.field1)) {
                    console.log(`[SYS] Name already taken: ${msg.field1}`);
                } else {
                    clients.set(msg.field1, 1);
                    rooms.get("general")!.push(msg.field1);
                    console.log(`[SYS] Welcome, ${msg.field1}!`);
                    console.log(`[SYS] ${msg.field1} joined. Online: ${clients.size}`);
                }
                break;
            }
            case "Disconnect": {
                clients.delete(msg.field1);
                for (const [, members] of rooms) {
                    const idx = members.indexOf(msg.field1);
                    if (idx >= 0) members.splice(idx, 1);
                }
                console.log(`[SYS] ${msg.field1} left. Online: ${clients.size}`);
                break;
            }
            case "Chat":
                broadcast(msg);
                break;
            case "PrivateMsg":
                if (clients.has(msg.field2)) {
                    console.log(`[PM] ${msg.field1} -> ${msg.field2}: ${msg.field3}`);
                } else {
                    console.log(`[SYS] User ${msg.field2} not found`);
                }
                break;
            case "JoinRoom": {
                rooms.get(msg.field2)?.push(msg.field1);
                broadcastRoom(msg.field2, { kind: "System", field1: `${msg.field1} joined #${msg.field2}` });
                break;
            }
            case "LeaveRoom": {
                const members = rooms.get(msg.field2);
                if (members) {
                    const idx = members.indexOf(msg.field1);
                    if (idx >= 0) members.splice(idx, 1);
                }
                broadcastRoom(msg.field2, { kind: "System", field1: `${msg.field1} left #${msg.field2}` });
                break;
            }
            case "RoomMsg":
                broadcastRoom(msg.field1, msg);
                break;
            case "System":
                console.log(`[SYS] ${msg.field1}`);
                break;
        }
    }
}

function clientHandler(name: string): void {
    console.log(`Welcome, ${name}! Commands: /msg, /join, /leave, /rooms, /quit`);
    const inputs = ["Hello everyone!", "/join random", "/rooms", "/quit"];
    for (const input of inputs) {
        if (input === "/quit") {
            console.log(`Goodbye, ${name}!`);
            return;
        } else if (input.startsWith("/msg ")) {
            const parts = input.split(" ");
            if (parts.length >= 3) {
                const target = parts[1];
                const text = parts.slice(2).join(" ");
                console.log(`[PM] ${name} -> ${target}: ${text}`);
            }
        } else if (input.startsWith("/join ")) {
            const roomName = input.split(" ")[1];
            console.log(`[SYS] ${name} joined #${roomName}`);
        } else if (input.startsWith("/leave ")) {
            const roomName = input.split(" ")[1];
            console.log(`[SYS] ${name} left #${roomName}`);
        } else if (input === "/rooms") {
            console.log("[SYS] Available rooms: general, random");
        } else if (input.length > 0) {
            console.log(`${name}: ${input}`);
        }
    }
}

function main(): void {
    const port = 8080;
    console.log("=== AutoChat Server v1.0 ===");
    console.log(`Starting on port ${port}...`);
    console.log("Server running. Press Ctrl+C to stop.");
    clientHandler("Alice");
    clientHandler("Bob");
}

main();
