// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[cfg(target_os = "linux")]
fn os_name() -> &'static str {
    "Linux"
}

#[cfg(target_os = "macos")]
fn os_name() -> &'static str {
    "macOS"
}

#[cfg(target_os = "windows")]
fn os_name() -> &'static str {
    "Windows"
}

fn main() {
    println!("Running on: {}", os_name());
}
