// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

#if defined(__linux__)
const char* os_name() {
    return "Linux";
}
#elif defined(__APPLE__)
const char* os_name() {
    return "macOS";
}
#elif defined(_WIN32)
const char* os_name() {
    return "Windows";
}
#endif

int main(void) {
    printf("Running on: %s\n", os_name());
    return 0;
}
