// Auto-generated by a2ts transpiler

import * as os from "os";

function osName(): string {
    switch (os.platform()) {
        case "linux": return "Linux";
        case "darwin": return "macOS";
        case "win32": return "Windows";
        default: return "Unknown";
    }
}

function main(): void {
    console.log("Running on: " + osName());
}

main();
