# Auto-generated by a2p transpiler

import sys

def os_name():
    if sys.platform == "linux":
        return "Linux"
    elif sys.platform == "darwin":
        return "macOS"
    elif sys.platform == "win32":
        return "Windows"

def main():
    print("Running on: " + os_name())

if __name__ == "__main__":
    main()
