// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Message {
    Quit,
    Write(String),
}


impl Message {
    fn call(&self) {
        println!("Message called");
    }
}

fn main() {
    let msg = Message::Write("hello".to_string());
    msg.call();
}
