// Auto-generated by a2ts transpiler

enum Command {
    Increment = "Increment",
    GetCount = "GetCount",
    Reset = "Reset",
}

function counter(messages: Command[]): void {
    let count = 0;
    for (const cmd of messages) {
        switch (cmd) {
            case Command.Increment:
                count = count + 1;
                break;
            case Command.GetCount:
                // send caller count
                break;
            case Command.Reset:
                count = 0;
                break;
        }
    }
}

function main(): void {
    const messages: Command[] = [
        Command.Increment,
        Command.Increment,
        Command.Increment,
        Command.GetCount,
    ];
    counter(messages);
}

main();
