// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

typedef enum Command {
    Command_Increment,
    Command_GetCount,
    Command_Reset,
} Command;

void counter_fn(void) {
    int count = 0;
    // Simulated message loop
    count = count + 1;
    count = count + 1;
    count = count + 1;
}

int main(void) {
    counter_fn();
    return 0;
}
