// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

enum Command {
    Increment,
    GetCount,
    Reset,
}

fn counter(rx: mpsc::Receiver<Command>) {
    let mut count: i64 = 0;
    for _cmd in rx {
        match _cmd {
            Command::Increment => {
                count = count + 1;
            }
            Command::GetCount => {
                // send caller count
            }
            Command::Reset => {
                count = 0;
            }
        }
    }
}

fn main() {
    let (tx, rx) = mpsc::channel::<Command>();
    std::thread::spawn(move || {
        counter(rx);
    });
    tx.send(Command::Increment).unwrap();
    tx.send(Command::Increment).unwrap();
    tx.send(Command::Increment).unwrap();
    tx.send(Command::GetCount).unwrap();
}
