# Auto-generated by a2p transpiler

import threading
import queue
from enum import Enum

class Command(Enum):
    Increment = 1
    GetCount = 2
    Reset = 3

def counter(q):
    count = 0
    while True:
        try:
            cmd = q.get(timeout=1.0)
            if cmd == Command.Increment:
                count = count + 1
            elif cmd == Command.GetCount:
                pass  # send caller count
            elif cmd == Command.Reset:
                count = 0
        except queue.Empty:
            break

def main():
    q = queue.Queue()
    t = threading.Thread(target=counter, args=(q,))
    t.daemon = True
    t.start()
    q.put(Command.Increment)
    q.put(Command.Increment)
    q.put(Command.Increment)
    q.put(Command.GetCount)
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
