// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

use trpl::{block_on, get, Html, Either};

async fn page_title(url: &str) -> Option<String> {
    let response_text = trpl::get(url).await.text().await;
    Html::parse(&response_text)
        .select_first("title")
        .map(|title| title.inner_html())
}

fn main() {
    block_on(async {
        let title_fut_1 = page_title("https://example.com");
        let title_fut_2 = page_title("https://example.org");

        let (url, maybe_title) = match trpl::select(title_fut_1, title_fut_2).await {
            Either::Left((url, title)) => (url, title),
            Either::Right((url, title)) => (url, title),
        };
        match maybe_title {
            Some(title) => println!("{url}: {title}"),
            None => println!("{url}: no title found"),
        }
    })
}
