# Auto-generated by a2p transpiler

def main():
    i = 0
    while i < 10:
        i = i + 1
        if i == 3:
            continue
        if i == 7:
            break
        print(i)

if __name__ == "__main__":
    main()
