// Auto-generated by a2c transpiler

#include <stdio.h>

int main(void) {
    long long i = 0;
    while (i < 10) {
        i = i + 1;
        if (i == 3) {
            continue;
        }
        if (i == 7) {
            break;
        }
        printf("%lld\n", i);
    }
    return 0;
}
