// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdlib.h>

void process(void) {
    for (long long i = 0; i < 1000000; i++) {
        long long* data = malloc(3 * sizeof(long long));
        data[0] = i;
        data[1] = i + 1;
        data[2] = i + 2;
        /* no GC pauses -- deterministic deallocation */
        free(data);
    }
    printf("Done processing 1M items\n");
}

int main(void) {
    process();
    return 0;
}
