// Auto-generated by a2ts transpiler

function process(): void {
    for (let i = 0; i < 1000000; i++) {
        const data = [i, i + 1, i + 2];
        // no GC pauses -- deterministic deallocation
    }
    console.log("Done processing 1M items");
}

function main(): void {
    process();
}

main();
