# Auto-generated by a2p transpiler

def process() -> None:
    for i in range(1000000):
        data = [i, i + 1, i + 2]
        # no GC pauses -- deterministic deallocation
    print("Done processing 1M items")

def main():
    process()

if __name__ == "__main__":
    main()
