// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn process() {
    for i in 0..1000000 {
        let data = vec![i, i + 1, i + 2];
        // no GC pauses -- deterministic deallocation
    }
    println!("Done processing 1M items");
}

fn main() {
    process();
}
