// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdlib.h>

typedef struct Item {
    long long value;
    struct Item* next;
} Item;

Item* item_new(long long value, Item* next) {
    Item* node = (Item*)malloc(sizeof(Item));
    node->value = value;
    node->next = next;
    return node;
}

int main(void) {
    Item* third = item_new(30, NULL);
    Item* second = item_new(20, third);
    Item* first = item_new(10, second);
    Item* current = first;
    while (current != NULL) {
        printf("%lld\n", current->value);
        current = current->next;
    }
    return 0;
}
