# Auto-generated by a2p transpiler

class Item:
    def __init__(self, value=0, next=None):
        self.value = value
        self.next = next

def main():
    third = Item(value=30, next=None)
    second = Item(value=20, next=third)
    first = Item(value=10, next=second)
    current = first
    while current is not None:
        print(current.value)
        current = current.next

if __name__ == "__main__":
    main()
