// Auto-generated by a2ts transpiler

class Item {
    value: number;
    next: Item | null;

    constructor(value: number, next: Item | null = null) {
        this.value = value;
        this.next = next;
    }
}

function main(): void {
    let third: Item = new Item(30, null);
    let second: Item = new Item(20, third);
    let first: Item = new Item(10, second);
    let current: Item | null = first;
    while (current !== null) {
        console.log(current.value);
        current = current.next;
    }
}

main();
