// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

trait Summary {
    fn summarize(&self) -> String;
}

struct NewsArticle {
    headline: String,
    author: String,
}

impl Summary for NewsArticle {
    fn summarize(&self) -> String {
        format!("{}, by {}", self.headline, self.author)
    }
}

fn notify(item: Box<dyn Summary>) {
    println!("Breaking news!");
    println!("{}", item.summarize());
}

fn main() {
    let article = NewsArticle { headline: String::from("Big News"), author: String::from("Alice") };
    notify(Box::new(article));
}
