// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn add(a: i32, b: i32) -> i32 {
    a + b
}

#[test]
fn it_adds_two() {
    let result = add(2, 2);
    assert_eq!(result, 4);
}
