// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

#[derive(Clone, Debug, PartialEq)]
enum IpAddr {
    V4(String),
    V6(String),
}


fn main() {
    let home = IpAddr::V4("127.0.0.1");
    let loopback = IpAddr::V6("::1");
    println!("IP addresses created");
}
