// Auto-generated by a2ts transpiler

function takeOwnership(s: string): void {
    console.log(s);
}

function main(): void {
    const greeting = "Hello";
    takeOwnership(greeting);
    // console.log(greeting);  // ERROR: greeting was moved
}

main();
