// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

void take_ownership(char* s) {
    printf("%s\n", s);
    free(s);
}

int main(void) {
    char* greeting = strdup("Hello");
    take_ownership(greeting);
    /* printf("%s\n", greeting); */  /* ERROR: greeting was moved (freed) */
    return 0;
}
