# Auto-generated by a2p transpiler

def take_ownership(s: str) -> None:
    print(s)

def main():
    greeting = "Hello"
    take_ownership(greeting)
    # print(greeting)  # ERROR: greeting was moved

if __name__ == "__main__":
    main()
