// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    println!("Guess the number!");
    let secret_number: i32 = 7;
    println!("The secret number is: {}", secret_number);
    println!("Please input your guess.");

    let guess: i32 = 4;

    if guess < secret_number {
        println!("Too small!");
    } else if guess > secret_number {
        println!("Too big!");
    } else {
        println!("You win!");
    }

}
