// Auto-generated by a2r transpiler

fn main() {
    println!("Guess the number!");
    let secret_number: i64 = 7;
    println!("The secret number is: {}", secret_number);
    println!("Please input your guess.");

    let guess: i64 = 4;

    if guess < secret_number {
        println!("Too small!");
    } else if guess > secret_number {
        println!("Too big!");
    } else {
        println!("You win!");
    }

}
