// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn risky() -> Result<i64, String> {
    Ok(42)
}

fn main() {
    let mut result = risky();
    match result {
        Ok(v) => println!("Got: {}", v),
        Err(e) => println!("Error: {}", e),
    }
}
