// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    long long value;
    int _ok;
    char error[256];
} IntResult;

IntResult risky(void) {
    IntResult r;
    r.value = 42;
    r._ok = 1;
    return r;
}

int main(void) {
    IntResult result = risky();
    if (result._ok) {
        printf("Got: %lld\n", result.value);
    } else {
        printf("Error: %s\n", result.error);
    }
    return 0;
}
