# Auto-generated by a2p transpiler

def risky() -> int:
    return 42

def main():
    try:
        result = risky()
        print(f"Got: {result}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()
