// Auto-generated by a2ts transpiler

function risky(): number {
    return 42;
}

function main(): void {
    try {
        const result = risky();
        console.log(`Got: ${result}`);
    } catch (e: unknown) {
        console.log(`Error: ${e}`);
    }
}

main();
