// Auto-generated by a2ts transpiler

function fetchData(): Promise<string> {
    return new Promise((resolve) => {
        resolve("data");
    });
}

function main(): void {
    fetchData().then((data) => {
        console.log("Got: " + data);
    });
}

main();
