# Auto-generated by a2p transpiler

import threading
import queue

def fetch_data(in_q, out_q):
    try:
        result = in_q.get(timeout=2.0)
        out_q.put(result)
    except queue.Empty:
        pass

def main():
    in_q = queue.Queue()
    out_q = queue.Queue()
    t = threading.Thread(target=fetch_data, args=(in_q, out_q))
    t.daemon = True
    t.start()
    try:
        data = out_q.get(timeout=2.0)
        print("Got: " + data)
    except queue.Empty:
        pass
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
