// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

fn fetch_data(rx: mpsc::Receiver<String>, main_tx: mpsc::Sender<String>) {
    if let Ok(result) = rx.recv() {
        let _ = main_tx.send(result);
    }
}

fn main() {
    let (fetcher_tx, fetcher_rx) = mpsc::channel::<String>();
    let (main_tx, main_rx) = mpsc::channel::<String>();

    std::thread::spawn(move || {
        fetch_data(fetcher_rx, main_tx);
    });

    match main_rx.recv() {
        Ok(data) => {
            println!("{}", "Got: ".to_string() + &data);
        }
        Err(_) => {}
    }
}
