// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

void fetch_data_fn(const char** result) {
    *result = "data";
}

int main(void) {
    const char* data = NULL;
    fetch_data_fn(&data);
    if (data) {
        printf("Got: %s\n", data);
    }
    return 0;
}
