// Auto-generated by a2ts transpiler

function makeMultiplier(factor: number): (n: number) => number {
    return (n: number) => n * factor;
}

function main(): void {
    const triple = makeMultiplier(3);
    console.log(triple(5));
    console.log(triple(10));
}

main();
