# Auto-generated by a2p transpiler

def make_multiplier(factor):
    def inner(n):
        return n * factor
    return inner

def main():
    triple = make_multiplier(3)
    print(triple(5))
    print(triple(10))

if __name__ == "__main__":
    main()
