// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn make_multiplier(factor: i32) -> impl Fn(i32) -> i32 {
    move |n: i32| -> i32 { n * factor }
}

fn main() {
    let mut triple = make_multiplier(3);
    println!("{}", triple(5));
    println!("{}", triple(10));
}
