// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

typedef struct {
    int factor;
} ClosureMultiplier;

int multiplier_call(ClosureMultiplier* env, int n) {
    return n * env->factor;
}

ClosureMultiplier* make_multiplier(int factor) {
    ClosureMultiplier* env = (ClosureMultiplier*)malloc(sizeof(ClosureMultiplier));
    env->factor = factor;
    return env;
}

int main(void) {
    ClosureMultiplier* triple = make_multiplier(3);
    printf("%d\n", multiplier_call(triple, 5));
    printf("%d\n", multiplier_call(triple, 10));
    free(triple);
    return 0;
}
