// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

enum Atom {
    Int(i32),
    Char(char),
    Float(f64),
}


fn main() {
    let atom = Atom::Int(11);

    match atom {
        Atom::Int(i) => println!("Got Int: {}", i),
        Atom::Char(c) => println!("Got Char: {}", c),
        Atom::Float(f) => println!("Got Float: {}", f),
    }
}
