// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

typedef struct {
    char message[256];
    long long line;
} ParseError;

typedef struct {
    long long value;
    int _ok;
    char error[512];
} IntResult;

IntResult parse(const char* s) {
    IntResult r;
    if (strlen(s) == 0) {
        ParseError err;
        strcpy(err.message, "empty input");
        err.line = 0;
        r._ok = 0;
        snprintf(r.error, sizeof(r.error), "%s at line %lld", err.message, err.line);
        return r;
    } else {
        r.value = 42;
        r._ok = 1;
    }
    return r;
}

int main(void) {
    IntResult result = parse("hello");
    if (result._ok) {
        printf("%lld\n", result.value);
    } else {
        printf("Error: %s\n", result.error);
    }
    return 0;
}
