// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct ParseError {
    message: String,
    line: i64,
}

fn parse(s: String) -> Result<i64, String> {
    if s.is_empty() {
        let err = ParseError {
            message: String::from("empty input"),
            line: 0,
        };
        Err(format!("{} at line {}", err.message, err.line))
    } else {
        Ok(42)
    }
}

fn main() {
    let mut result = parse(String::from("hello")).unwrap();
    println!("{}", result);
}
