# Auto-generated by a2p transpiler

from dataclasses import dataclass

@dataclass
class ParseError:
    message: str
    line: int

def parse(s: str) -> int:
    if s == "":
        raise ValueError(f"ParseError: {ParseError(message='empty input', line=0)}")
    else:
        return 42

def main():
    result = parse("hello")
    print(result)

if __name__ == "__main__":
    main()
