// Auto-generated by a2ts transpiler

class ParseError {
    message: string;
    line: number;

    constructor(message: string, line: number) {
        this.message = message;
        this.line = line;
    }
}

function parse(s: string): number {
    if (s === "") {
        throw new Error(`ParseError: ${new ParseError("empty input", 0)}`);
    } else {
        return 42;
    }
}

function main(): void {
    const result = parse("hello");
    console.log(result);
}

main();
