# Auto-generated by a2p transpiler

def longest(a: str, b: str) -> str:
    if len(a) > len(b):
        return a
    else:
        return b

def main():
    s1 = "hello"
    s2 = "world!"
    result = longest(s1, s2)
    print(result)

if __name__ == "__main__":
    main()
