// Auto-generated by a2ts transpiler

function longest(a: string, b: string): string {
    if (a.length > b.length) {
        return a;
    } else {
        return b;
    }
}

function main(): void {
    const s1 = "hello";
    const s2 = "world!";
    const result = longest(s1, s2);
    console.log(result);
}

main();
