// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

const char* longest(const char* a, const char* b) {
    if (strlen(a) > strlen(b)) {
        return a;
    } else {
        return b;
    }
}

int main(void) {
    const char* s1 = "hello";
    const char* s2 = "world!";
    const char* result = longest(s1, s2);
    printf("%s\n", result);
    return 0;
}
