// Auto-generated by a2r transpiler

fn area(width: i64, height: i64) -> i64 {
    width * height
}

fn main() {
    let rect1_width: i64 = 30;
    let rect1_height: i64 = 50;
    println!("The area of the rectangle is {} square pixels.", area(rect1_width, rect1_height));
}
