// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

typedef struct MapEntry {
    char key[256];
    long long value;
    struct MapEntry* next;
} MapEntry;

typedef struct {
    MapEntry* head;
    int size;
} HashMap;

void map_insert(HashMap* map, const char* key, long long value) {
    MapEntry* entry = map->head;
    while (entry != NULL) {
        if (strcmp(entry->key, key) == 0) {
            entry->value = value;
            return;
        }
        entry = entry->next;
    }
    MapEntry* new_entry = (MapEntry*)malloc(sizeof(MapEntry));
    strcpy(new_entry->key, key);
    new_entry->value = value;
    new_entry->next = map->head;
    map->head = new_entry;
    map->size++;
}

long long map_get(HashMap* map, const char* key) {
    MapEntry* entry = map->head;
    while (entry != NULL) {
        if (strcmp(entry->key, key) == 0) {
            return entry->value;
        }
        entry = entry->next;
    }
    return 0;
}

int main(void) {
    HashMap scores = {NULL, 0};
    map_insert(&scores, "Alice", 90);
    map_insert(&scores, "Bob", 85);
    map_insert(&scores, "Charlie", 92);
    printf("%lld\n", map_get(&scores, "Alice"));
    map_insert(&scores, "Dave", 88);
    printf("%d\n", scores.size);
    return 0;
}
