# Auto-generated by a2p transpiler

def main():
    scores = {"Alice": 90, "Bob": 85, "Charlie": 92}
    print(scores["Alice"])
    scores["Dave"] = 88
    print(len(scores))

if __name__ == "__main__":
    main()
