// Auto-generated by a2r transpiler

use std::collections::HashMap;

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let mut scores: HashMap<String, i64> = HashMap::new();
    scores.insert(String::from("Alice"), 90);
    scores.insert(String::from("Bob"), 85);
    scores.insert(String::from("Charlie"), 92);
    println!("{}", scores.get("Alice").unwrap());
    scores.insert(String::from("Dave"), 88);
    println!("{}", scores.len());
}
