// Auto-generated by a2ts transpiler

function main(): void {
    let scores: { [key: string]: number } = { "Alice": 90, "Bob": 85, "Charlie": 92 };
    console.log(scores["Alice"]);
    scores["Dave"] = 88;
    console.log(Object.keys(scores).length);
}

main();
