// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

typedef enum WorkKind {
    WorkKind_Process,
    WorkKind_Result,
} WorkKind;

typedef struct Work {
    WorkKind kind;
    const char* value;
} Work;

void worker_fn(int id, Work work, Work* result) {
    if (work.kind == WorkKind_Process) {
        char buf[256];
        snprintf(buf, sizeof(buf), "Processed: %s", work.value);
        result->kind = WorkKind_Result;
        result->value = buf;
    }
}

int main(void) {
    Work result1, result2;

    worker_fn(1, (Work){ .kind = WorkKind_Process, .value = "task-a" }, &result1);
    worker_fn(2, (Work){ .kind = WorkKind_Process, .value = "task-b" }, &result2);

    if (result1.kind == WorkKind_Result) {
        printf("%s\n", result1.value);
    }
    if (result2.kind == WorkKind_Result) {
        printf("%s\n", result2.value);
    }

    return 0;
}
