// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

enum Work {
    Process(String),
    Result(String),
}

fn worker(id: i64, rx: mpsc::Receiver<Work>, main_tx: mpsc::Sender<Work>) {
    for work in rx {
        match work {
            Work::Process(data) => {
                let result = "Processed: ".to_string() + &data;
                let _ = main_tx.send(Work::Result(result));
            }
            Work::Result(_) => {}
        }
    }
}

fn main() {
    let (tx1, rx1) = mpsc::channel::<Work>();
    let (tx2, rx2) = mpsc::channel::<Work>();
    let (main_tx, main_rx) = mpsc::channel::<Work>();

    std::thread::spawn(move || { worker(1, rx1, main_tx.clone()); });
    std::thread::spawn(move || { worker(2, rx2, main_tx); });

    tx1.send(Work::Process(String::from("task-a"))).unwrap();
    tx2.send(Work::Process(String::from("task-b"))).unwrap();

    match main_rx.recv() {
        Ok(result) => {
            match result {
                Work::Result(msg) => println!("{}", msg),
                Work::Process(_) => {}
            }
        }
        Err(_) => {}
    }
}
