# Auto-generated by a2p transpiler

import threading
import queue
from enum import Enum

class WorkKind(Enum):
    Process = 1
    Result = 2

class Work:
    def __init__(self, kind: WorkKind, value: str = ""):
        self.kind = kind
        self.value = value

def worker(id, in_q, out_q):
    while True:
        try:
            work = in_q.get(timeout=1.0)
            if work.kind == WorkKind.Process:
                result = "Processed: " + work.value
                out_q.put(Work(WorkKind.Result, result))
            elif work.kind == WorkKind.Result:
                pass
        except queue.Empty:
            break

def main():
    q1 = queue.Queue()
    q2 = queue.Queue()
    out_q = queue.Queue()

    t1 = threading.Thread(target=worker, args=(1, q1, out_q))
    t2 = threading.Thread(target=worker, args=(2, q2, out_q))
    t1.daemon = True
    t2.daemon = True
    t1.start()
    t2.start()

    q1.put(Work(WorkKind.Process, "task-a"))
    q2.put(Work(WorkKind.Process, "task-b"))

    try:
        result = out_q.get(timeout=2.0)
        if result.kind == WorkKind.Result:
            print(result.value)
        elif result.kind == WorkKind.Process:
            pass
    except queue.Empty:
        pass

    t1.join(timeout=2.0)
    t2.join(timeout=2.0)

if __name__ == "__main__":
    main()
