// Auto-generated by a2ts transpiler

enum WorkKind {
    Process = "Process",
    Result = "Result",
}

class Work {
    kind: WorkKind;
    value: string;

    constructor(kind: WorkKind, value: string = "") {
        this.kind = kind;
        this.value = value;
    }
}

function worker(id: number, work: Work): Work | null {
    if (work.kind === WorkKind.Process) {
        return new Work(WorkKind.Result, "Processed: " + work.value);
    }
    return null;
}

function main(): void {
    const result1 = worker(1, new Work(WorkKind.Process, "task-a"));
    const result2 = worker(2, new Work(WorkKind.Process, "task-b"));

    if (result1 && result1.kind === WorkKind.Result) {
        console.log(result1.value);
    }
    if (result2 && result2.kind === WorkKind.Result) {
        console.log(result2.value);
    }
}

main();
