// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn print_length(s: &String) {
    println!("{}", s.len());
}

fn main() {
    let name = String::from("Hello, Auto!");
    print_length(&name);
    println!("{}", name);  // still valid -- view doesn't consume
}
