// Auto-generated by a2c transpiler

#include <stdio.h>
#include <string.h>

void print_length(const char* s) {
    printf("%zu\n", strlen(s));
}

int main(void) {
    const char* name = "Hello, Auto!";
    print_length(name);
    printf("%s\n", name);  /* still valid -- view doesn't consume */
    return 0;
}
