# Auto-generated by a2p transpiler

def print_length(s: str) -> None:
    print(len(s))

def main():
    name = "Hello, Auto!"
    print_length(name)
    print(name)  # still valid -- view doesn't consume

if __name__ == "__main__":
    main()
