// Auto-generated by a2ts transpiler

function printLength(s: string): void {
    console.log(s.length);
}

function main(): void {
    const name = "Hello, Auto!";
    printLength(name);
    console.log(name);  // still valid -- view doesn't consume
}

main();
