// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn main() {
    let s: String = String::from("hello");

    let r1: &str = &s;
    let r2: &str = &s;
    println!("r1 = {}, r2 = {}", r1, r2);

}
