// Auto-generated by a2ts transpiler

function greeter(messages: string[]): void {
    for (const msg of messages) {
        console.log("Greeting: " + msg);
    }
}

function main(): void {
    const messages: string[] = [];
    // In a real implementation, greeter would run as a worker
    greeter(["Hello from main!", "Auto is awesome!"]);
}

main();
