// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;
use std::sync::mpsc;

fn greeter(rx: mpsc::Receiver<String>) {
    for msg in rx {
        println!("{}", "Greeting: ".to_string() + &msg);
    }
}

fn main() {
    let (tx, rx) = mpsc::channel::<String>();
    std::thread::spawn(move || {
        greeter(rx);
    });
    tx.send(String::from("Hello from main!")).unwrap();
    tx.send(String::from("Auto is awesome!")).unwrap();
}
