# Auto-generated by a2p transpiler

import threading
import queue

def greeter(q):
    while True:
        try:
            msg = q.get(timeout=1.0)
            print("Greeting: " + msg)
        except queue.Empty:
            break

def main():
    q = queue.Queue()
    t = threading.Thread(target=greeter, args=(q,))
    t.daemon = True
    t.start()
    q.put("Hello from main!")
    q.put("Auto is awesome!")
    t.join(timeout=2.0)

if __name__ == "__main__":
    main()
