// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use auto_lang::a2r_std::*;

struct Color {
    red: i32,
    green: i32,
    blue: i32,
}

struct Point {
    x: i32,
    y: i32,
    z: i32,
}

fn main() {
    let black = Color { red: 0, green: 0, blue: 0 };
    let origin = Point { x: 0, y: 0, z: 0 };
    println!("black: {}, {}, {}", black.red, black.green, black.blue);
    println!("origin: {}, {}, {}", origin.x, origin.y, origin.z);
}
