// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Color {
    pub red: i64,
    pub green: i64,
    pub blue: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Point {
    pub x: i64,
    pub y: i64,
    pub z: i64,
}

fn main() {
    let black = Color { red: 0, green: 0, blue: 0 };
    let origin = Point { x: 0, y: 0, z: 0 };
    println!("black: {}, {}, {}", black.red, black.green, black.blue);
    println!("origin: {}, {}, {}", origin.x, origin.y, origin.z);
}
