// Auto-generated by a2c transpiler

#include <stdio.h>

typedef struct {
    double value;
    int _ok;
    char error[256];
} FloatResult;

FloatResult divide(double a, double b) {
    FloatResult r;
    if (b == 0.0) {
        r._ok = 0;
        snprintf(r.error, sizeof(r.error), "division by zero");
    } else {
        r.value = a / b;
        r._ok = 1;
    }
    return r;
}

typedef struct {
    double value;
    int _some;
} FloatOption;

FloatOption safe_divide(double a, double b) {
    FloatResult result = divide(a, b);
    FloatOption opt;
    if (result._ok) {
        opt.value = result.value;
        opt._some = 1;
    } else {
        opt._some = 0;
    }
    return opt;
}

int main(void) {
    FloatOption r1 = safe_divide(10.0, 3.0);
    if (r1._some) {
        printf("%f\n", r1.value);
    } else {
        printf("None\n");
    }
    FloatOption r2 = safe_divide(10.0, 0.0);
    if (r2._some) {
        printf("%f\n", r2.value);
    } else {
        printf("None\n");
    }
    return 0;
}
