// Auto-generated by a2ts transpiler

function divide(a: number, b: number): number {
    if (b === 0.0) {
        throw new Error("division by zero");
    } else {
        return a / b;
    }
}

function safeDivide(a: number, b: number): number | null {
    try {
        return divide(a, b);
    } catch {
        return null;
    }
}

function main(): void {
    const r1 = safeDivide(10.0, 3.0);
    console.log(r1);
    const r2 = safeDivide(10.0, 0.0);
    console.log(r2);
}

main();
