// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn divide(a: f64, b: f64) -> Result<f64, String> {
    if b == 0.0 {
        Err(String::from("division by zero"))
    } else {
        Ok(a / b)
    }
}

fn safe_divide(a: f64, b: f64) -> Option<f64> {
    let mut result = divide(a, b);
    match result {
        Ok(v) => Some(v),
        Err(_) => None,
    }
}

fn main() {
    let mut r1 = safe_divide(10.0, 3.0);
    println!("{:?}", r1);
    let mut r2 = safe_divide(10.0, 0.0);
    println!("{:?}", r2);
}
