# Auto-generated by a2p transpiler

from typing import Optional

def divide(a: float, b: float) -> float:
    if b == 0.0:
        raise ValueError("division by zero")
    else:
        return a / b

def safe_divide(a: float, b: float) -> Optional[float]:
    try:
        return divide(a, b)
    except ValueError:
        return None

def main():
    r1 = safe_divide(10.0, 3.0)
    print(r1)
    r2 = safe_divide(10.0, 0.0)
    print(r2)

if __name__ == "__main__":
    main()
