// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Rectangle {
    pub width: i64,
    pub height: i64,
}

fn area(rect: Rectangle) -> i64 {
    rect.width * rect.height
}

fn main() {
    let rect1 = Rectangle { width: 30, height: 50 };
    println!("The area of the rectangle is {} square pixels.", area(rect1.clone()));
}
