// Auto-generated by a2c transpiler

#include <stdio.h>
#include <stdbool.h>

typedef struct ResultString {
    bool is_ok;
    const char* ok_value;
    const char* err_value;
} ResultString;

ResultString read_file(const char* path) {
    // reads file content, returns !String
    ResultString r;
    r.is_ok = true;
    r.ok_value = "Hello from file!";
    r.err_value = NULL;
    return r;
}

int main(void) {
    ResultString content = read_file("input.txt");
    if (!content.is_ok) {
        fprintf(stderr, "Error: %s\n", content.err_value);
        return 1;
    }
    printf("%s\n", content.ok_value);
    return 0;
}
