// Auto-generated by a2ts transpiler

function readFile(path: string): string {
    // reads file content, returns !String
    return "Hello from file!";
}

function main(): void {
    const content = readFile("input.txt");
    console.log(content);
}

main();
