# Auto-generated by a2p transpiler

class FileNotFoundError(Exception):
    pass

def read_file(path: str) -> str:
    # reads file content, returns !String
    return "Hello from file!"

def main():
    content = read_file("input.txt")
    print(content)

if __name__ == "__main__":
    main()
