// Auto-generated by a2r transpiler

#[allow(unused_imports)]
use auto_lang::a2r_std::*;

fn read_file(path: &str) -> Result<String, String> {
    // reads file content, returns !String
    Ok(String::from("Hello from file!"))
}

fn main() -> Result<(), String> {
    let content = read_file("input.txt")?;
    println!("{}", content);
    Ok(())
}
